### ISSUE TITLE
Missing support for ActiveRecord::Enum (Rails 4.1)

### ISSUE THREAD

**Issue by tbk303** [CanCanCommunity/cancancan#102]
Rails 4.1 introduced support for enums, represented by integers in the database. Currently, defining abilities matching enum values becomes tedious, as the actual enum value is required (for matching abilities on model instances) as well as the respective integer value (for matching abilities in database queries, i.e. accessible_by).

Example:

    can :read, FooBar, state: ['active', FooBar.states['active']]

Checking the ability against an instance with `authorize! :read, @foobar` requires the `'active'` value in the ability definition while fetching accessible foobars with `FooBar.all.accessible_by(current_ability)` requires the actual integer value (given via `FooBar.states`).

Maybe it is possible for CanCanCan to detect enum columns and extend the ability definition automatically.

**Comment by markpmitchell** [comment]
@bryanrite, is there anything I can do to help with the process of reviewing my pull request for this issue?

**Comment by bryanrite** [comment]
No.. sorry Mark, just been preoccupied with other things lately. Your PR looks good, I'll take a look at merging it tomorrow.

**Comment by bryanrite** [comment]
Closing this in favour of #196

**Comment by markpmitchell** [comment]
Thanks!

--
Mark Mitchell

**Comment by markpmitchell** [comment]
Bryan —

It doesn’t look like you’ve had a chance to merge this PR yet. Is there anything I can do to help?

Thank you,

--
Mark Mitchell

**Comment by bryanrite** [comment]
Sorry Mark, been having a hard time finding hours to continuing heading CCC maintainership. Looking for a new maintainer if you're interested :smile: 

Check out: #209
