### ISSUE TITLE
attributes_for not giving the full hash of conditions

### ISSUE THREAD

**Issue by Crystark** [CanCanCommunity/cancancan#108]
Hi,

I've been playing around with `attributes_for` and it seems this doesn't give back the real hash of conditions one can expect.

For instance, I've defined a rule like:

```
can :manage, [OwnedObject], { owner: { parent_id: @user.id } }
```

I've been the calling 

```
@user.ability.attributes_for(:index, OwnedObject)
```

And i get back an empty Hash.
However, if i define the following rule: 

```
can :manage, [OwnedObject], { owner_id: @user.id }
```

I will get the expected hash.

I think this is due to `rule.attributes_from_conditions` which is called by `attributes_for` which adds the rule `unless [Array, Range, Hash].include? value.class`.

FYI, the reason i would like to use `attributes_for` is that I'm using the elasticsearch-rails gem as an alternate source of data and i'd like to apply to my searches the same conditions as my models' queries. For that i need the hash of conditions declared in my ability class.

Thanks

**Comment by Senjai** [comment]
@Crystark Thank you for the report.
