### ISSUE TITLE
Getting Status Code 500 on Access Denied

### ISSUE THREAD

**Issue by ghost** [CanCanCommunity/cancancan#111]
I'm getting this header:
# Status Code:500 Internal Server Error

for this response:
# CanCan::AccessDenied at /exercise_descriptions.json
# 

> You are not authorized to access this page.
## cancancan (1.9.1) lib/cancan/ability.rb, line 219

``` ruby
  214         if args.last.kind_of?(Hash) && args.last.has_key?(:message)
  215           message = args.pop[:message]
  216         end
  217         if cannot?(action, subject, *args)
  218           message ||= unauthorized_message(action, subject)
> 219           raise AccessDenied.new(message, action, subject)
  220         end
  221         subject
  222       end
  223   
  224       def unauthorized_message(action, subject)
```

**Comment by mameier** [comment]
The wiki move do docs.  
The new link is  
https://github.com/CanCanCommunity/cancancan/blob/develop/docs/handling_access_denied.md
