### ISSUE TITLE
Provide a custom authorization action on parent resources

### ISSUE THREAD

**Issue by phallguy** [CanCanCommunity/cancancan#115]
Currently, when authorizing nested resources, the parent resource is always authorized with the :show action. This makes a great deal of sense and is a good default but there are occasions when are more restrictive option is needed for more complex permissions.

I'd like to be able to specify the action that cancan uses to authorize the parent object as well 

``` ruby
class Controller
  load_and_authorize_resource :library, parent: true, parent_action: :sort
end
```

**Comment by Senjai** [comment]
@phallguy I know it's been a while, but I think this is a fair suggestion. Would you consider submitting a pull request?

**Comment by phallguy** [comment]
Sure thing see #216
