### ISSUE TITLE
Context based abilities [discussion prior to PR]

### ISSUE THREAD

**Issue by KensoDev** [CanCanCommunity/cancancan#119]
Hey,

Recently, I encountered the need for a context based ability system.

The current way that abilities are built is relying heavily on a coupling between the user to some object.

If you have 2 objects that are decoupled and relations only defined by context objects or other classes you basically can't use the ability class.

Here's what I needed

```ruby
class Board
  def users_invited_by(user)
    # multiple operations here including different data sources
  end
end
```

```ruby
class User
end
```

Basically, I want to ask "CAN user X remove user Y from this board"

The board is the context here, without it, user X can't do anything with user Y on any other object.

If I invited the user to the board, I can re-invite the user, I can remove him from the board and so on.

Question is: Would that be something you want to include in the project (it's definitely something that people might need in the future IMHO)?

I have implemented this feature but didn't want to open a PR before discussing whether you want this functionality in or not.

LMK if so, and I would open a PR and we can continue the discussion there

Thanks

**Comment by Senjai** [comment]
I agree with Bryan. The ability to pass in a block, a user, and a model or more should allow you accomplish any kind of complex logic here.

If you still disagree, could you provide a code example of what currently is required to make your situation work versus what you think should be required?
