### ISSUE TITLE
Different redirects

### ISSUE THREAD

**Issue by hcarver** [CanCanCommunity/cancancan#123]
Disclaimer: This might be a lack of documentation in the wiki, or it might be a feature request, or it might be that there's a good way to accomplish it without any change to CanCanCan.

The text below is pretty much copied from my [StackOverflow question about this](http://stackoverflow.com/questions/25992684/different-redirects-using-cancan).

Broadly, I want to be able to distinguish between different 'types' of permission. E.g. if an average user accesses `/adminpanel`, that should end up with a redirect to `/` and an error flash. But if an average user accesses `/paid_feature`, I'd like to redirect them to `/payments/paid_feature/new`. It's the second one that's causing me difficulties.

Obviously I can tell CanCan to let all users access `paid_feature` in ability.rb, and then confirm that they've paid (and redirect if necessary) in the `paid_feature` controller. But that seems unclean. It's an authorization question, so I want it to be in my ability.rb. How can I do that?

**Comment by Yanchek99** [comment]
It appears @bryanrite 's solution doesn't work when using ```load_and_authorize_resource``` but rather only when you declare ```authorize! :read, @object``` in each method and only use ```load_resource``` on the controller.

**Comment by smaziano** [comment]
@hcarver Had the same issue... but I've created a method that verifies the controller_name using a case statement and return wherever I want... In my case I wanted to redirect to the index of the current resource.

**Comment by jeremywadsack** [comment]
As @Yanchek99 points out, `rescue` inside the action body can't recover from an exception raised by the `load_and_authorize_resource` class method call. But you can use `rescue_from` in your controller for that.

```
class PaidFeature < ActionController::Base
  load_and_authorize_resource

  rescue_from CanCan::AccessDenied do
    redirect_to action: :new
  end

  def show
    # blah blah
  end

  def new
  end
end
```
