### ISSUE TITLE
Cannot test shallow nested controllers

### ISSUE THREAD

**Issue by ikido** [CanCanCommunity/cancancan#126]
When testing controller index action that has following decalration:

     load_and_authorize_resource :company
     load_and_authorize_resource :contact, through: :company, shallow: true

I have to explicitly pass parent resource to action like this in order to make test to pass, like this

     @ability = Object.new.extend(CanCan::Ability)
     allow(@controller).to receive(:current_ability).and_return(@ability)

     @parent = FactoryGirl.build_stubbed(:company)
     allow(Company).to receive(:find).with("1").and_return(@parent)

     @ability.can :read, @parent
     @ability.can :read, Contact

     get :index , company_id: '1'

But I want to test if index action works without passing parent company, which always results in failing test. I appreciate any help or direction what to look for.

**Comment by bryanrite** [comment]
Closing as this seems to be abandoned. Feel free to reopen if you are still having issues.
