### ISSUE TITLE
Change param_name to sanitizer

### ISSUE THREAD

**Issue by heaven** [CanCanCommunity/cancancan#136]
This looks a bit less awkwardly:
```ruby
load_and_authorize_resource sanitizer: :custom_sanitizer
```
There could also be a default sanitizer which will permit everything except `:id`, `:updated_at`, and `:created_at` attributes, which, I think, may work well for many simple controllers. Just an idea.

**Comment by Senjai** [comment]
@heaven Thank you for the suggestion, but I think this can add confusion and hint that there should be some sort of Sanitizer class provided. Perhaps the readme shouldn't name the method `my_sanitizer` as that's not actually an accurate description.

Permitting everything by default is generally a bad idea, and I wouldn't want to encourage it. It's generally best to be explicit about what is allowed to come through.
