### ISSUE TITLE
load_and_authorize_resource doesn't assign attributes for update action

### ISSUE THREAD

**Issue by rywall** [CanCanCommunity/cancancan#139]
Even though the docs suggest that this is so. The strong parameters section even mentions that it checks for an update_params method.

**Comment by bryanrite** [comment]
Can you give me an example? There should be no issues with strong params and the update method.

**Comment by caleb** [comment]
This is a bug I'm seeing as well, I can't believe I didn't see it until now (I guess in the rest of my application I'm manually calling `update` with the parameters method.

Is this a bug and a feature?

**Comment by rywall** [comment]
See #184
