### ISSUE TITLE
Shouldn't cancancan also manage strong parameters?

### ISSUE THREAD

**Issue by coorasse** [CanCanCommunity/cancancan#143]
That is a question more then an issue.

In my opinion if you have cancancan in your project it should also take care of the model attributes that users are allowed to edit.

We already have `load_and_authorize_resource` call in controllers and they automatically call the correct sanitizing method for parameters.

I would like to have a file like `ability.rb` (like `parameters.rb`) where I can define the parameters allowed for models with exactly the same syntax. kind of:
```
can? :create, User, :email
can? :update, User, :email, :address, :city
if (user.admin?)
  can? :update, User, :role
end
```

what's your opinion?

**Comment by designgrill** [comment]
The ability to limit what attributes can be updated by a role has enough use cases. Having the flexibility to specify which are those attributes falls perfectly under scope of an authorization project.

**Comment by darbs** [comment]
:+1:

**Comment by TMaYaD** [comment]
Why was this issue closed? Is it implemented or was it decided it does not lie within the scope of the project?

**Comment by stevenpetryk** [comment]
@TMaYaD I think it was because it was labelled as a "question", and the question was technically answered.
