### ISSUE TITLE
Extract Adapter Specific Code

### ISSUE THREAD

**Issue by bryanrite** [CanCanCommunity/cancancan#15]
In `lib/cancan/rule.rb:114`, there is ActiveRecord specific code which should really be in a adapter. The context of the code is too complex to refactor it into the adapter though... so that whole method needs to be broken down as well.

As discovered in #13 ... I guarded it so that datamapper and mongoid would work as a temporary solution.

**Comment by coorasse** [comment]
is this still a valid issue? would you send a PR eventually? Otherwise can be closed. Thanks
