### ISSUE TITLE
Problem using cancancan in engine

### ISSUE THREAD

**Issue by kagutsuchii** [CanCanCommunity/cancancan#151]
I want to use cancancan in an engine. So I added it to my gemspec file like this:

    s.add_dependency "cancancan"

In the engines dummy app and in a test app i load my engine and I'm getting always errors about undefined methods for every cancancan method.

    undefined local variable or method `load_and_authorize_resource'
    undefined local variable or method `can?'
    [...]

This is my `ability.rb`file in the main app:

    class Ability
      include CanCan::Ability

      def initialize(user)
        user ||= User.new # guest user (not logged in)
        can :manage, :all
      end
    end

I tried several solutions for using cancancan in engines but I found no solution. Here are some examples:
* http://mx.kelsin.net/2011/08/10/using-cancan-in-a-engine-and-your-app/
* https://github.com/CanCanCommunity/cancancan/wiki/Authorization-for-Namespaced-Controllers
* https://github.com/CanCanCommunity/cancancan/wiki/Admin-Namespace

Where is my fault? Is there a good tutorial to use cancancan in an engine?

**Comment by swobspace** [comment]
I'm using cancancan in an engine: https://github.com/swobspace/wobauth. My abilities are namespaces like this:

```ruby
module Wobauth
  class AdminAbility
    include CanCan::Ability

    def initialize(user)
      ...
    end
  end
end

```

**Comment by cheeyeo** [comment]
Hi

does anybody know if this is still an issue as I have having the same problems in a Rails 4 api engine?

**Comment by tyler-king** [comment]
If anyone is Googling this issue... it must've been my tired brain because I feel stupid ha. I forgot to add `gem 'cancan'` to `lib/yourenginename.rb`.

For abilities, you'd store the models under `app/models/yourenginename/ability.rb` for example and the file would need to contain:

```ruby
module Yourenginename
  class Ability
    include CanCan::Ability

    def initialize(user)
        # your init code
    end
  end
end
```

**Comment by shqear93** [comment]
I had this issue, I installed **cancancan** and I created **Ability** class using generator and I was very confused why it's happening, but it solved once I restarted rails server!!
