### ISSUE TITLE
[Mongoid] The condition-hash in a rule gets wrapped in a 'OR' when used in accessible_by

### ISSUE THREAD

**Issue by pranav-g10** [CanCanCommunity/cancancan#156]
I haven't checked the issue in ActiveRecord, I am assuming this is a Mongoid adapter issue only.

The use-case consists a User, who belongs_to a Plant, and the Plant has multiple Order objects.

    class User
        belongs_to :plant
    end

    class Plant
        has_many :users
        has_many :orders
    end

    class Order
        field :status
        field :priority
        belongs_to :plant
    end

The ability is defined such that a user can access all the orders of his plants via the plant_id:

    class Ability
        def initialize(user)
            can :read, Order, plant_id: user.plant_id
        end
    end

If I look at the rules for an ability object, the condition looks fine:

    <Ability:0x00000101e69c70
     @rules=
      [<CanCan::Rule:0x00000101d19280
        @actions=[:read],
        @base_behavior=true,
        @block=nil,
        @conditions={:plant_id=>BSON::ObjectId('54740b6d67313002cf010000')},
        @match_all=false,
        @subjects=[Order]>]>

But when I try to use this ability via Order.accessible_by(current_ability), the condition gets wrapped inside a '$or' as seen below:

    Order.accessible_by(current_ability)
    => #<Mongoid::Criteria
      selector: {"$or"=>[{"plant_id"=>BSON::ObjectId('54740b6d67313002cf010000')}]}
      options:  {}
      class:    Order
      embedded: false>

This is a big security flaw, because this means that if I try to combine the ability criteria with another condition which also has a '$or', the 2 would just merge and generate loophole in the ability restriction.

For example, say I want to read my orders which are either open (status: 'open') OR have a high priority (priority: 3), I would do something like : `Order.accessible_by(current_ability).where('$or' => [{status: 'open'}, {priority: 3}])`, but because of the '$or' put in by `accessible_by` when the 2 conditions merge I gain access to all order the belong to my plant OR are open OR have high priority.

Either this is a security-bug, or this should be documented somewhere.

**Comment by Senjai** [comment]
@pranav-g10 Thanks for the report. Would you be willing on writing a small example application to reproduce this with a regression spec?

**Comment by Senjai** [comment]
@pranav-g10 I believe this is also reported in #132. Closing to consolidate discussion there.
