### ISSUE TITLE
spec_helper requires additional activesupport components for development?

### ISSUE THREAD

**Issue by gdpelican** [CanCanCommunity/cancancan#157]
Trying to set up a dev environment, after running `bundle install` and `appraisal install`, I was still getting a ton of test failures; turns out cancancan doesn't include all of the Rails components it needs by default.

I had to add the following to the gemspec and the spec_helper to get it working:

```
s.add_development_dependency 'activesupport'
```

```
require 'active_support/core_ext/hash/indifferent_access'
require 'active_support/core_ext/object'
```

Anyone know why this is the case?

**Comment by bryanrite** [comment]
I haven't had this issue, even in a newly setup environment... anybody else?

**Comment by bryanrite** [comment]
How did you run the tests? `appraisal rake` or `appraisal xxx rake`?

You might see problems running just `bundle rake` or `rspec`

**Comment by gdpelican** [comment]
Ahah, that'd do it; sorry for not being a sufficiently good doc-reader. Closing this.
