### ISSUE TITLE
ActiveRecord named scope support

### ISSUE THREAD

**Issue by sbonami** [CanCanCommunity/cancancan#164]
Is there current support for ActiveRecord named scopes? It would be great to add and chain scopes with `can` definitions in the `Ability` model.

If not, I have a few implementation ideas after a quick glance at the code, but would appreciate any direction or input from the community.

**Comment by sergiotapia** [comment]
Any ideas? Even if you don't support name scopes, how can I filter permissions on more than 1 field?

**Comment by bryanrite** [comment]
Yes: https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities-with-Blocks#block-conditions-with-scopes
