### ISSUE TITLE
Accessible by scope problem when having model for ability also in hash conditions

### ISSUE THREAD

**Issue by kreintjes** [CanCanCommunity/cancancan#165]
Hi,

I have a strange problem when defining a can rule for same model and then joining on that model in the hash conditions as well. In my setup, I have an `Organisation` model, an `User` model and an `OrganisationUser` model, in which the latter is a simple join model/table which also includes a role field (the role the user has on the organisation). This way a user can belong to multiple organisations and an organisation can belong to multiple users (many to many).

Now I have an ability which is defined as follows:

`can :manage, OrganisationUser, organisation: { organisation_users: { user_id: user.id, role: :admin } }`

The idea is that the user can manage all OrganisationUsers for which its Organisation's OrganisationUsers includes the user with role admin.

This works perfectly when checking the abilities using the can? method. However, it does not work correctly with the accessible_by scope. When using this scope, there is always only one OrganisationUser returned, namely the OrganisationUser of the current_user itself. I believe this is due to an error in the generated SQL, which is as follows:

```
SELECT ... FROM "organisation_users"
LEFT OUTER JOIN "organisations" ON "organisations"."id" = "organisation_users"."organisation_id"
LEFT OUTER JOIN "organisation_users" "organisation_users_organisations" ON "organisation_users_organisations"."organisation_id" = "organisations"."id"
WHERE "organisation_users"."organisation_id" = $1
AND "organisation_users"."user_id" = 1
AND "organisation_users"."role" = 'admin'
AND "organisation_users"."id" IN (1)
```

I believe the problem is in the WHERE conditions. The following part `"organisation_users"."user_id" = 1 AND "organisation_users"."role" = 'admin'` should be `"organisation_users_organisations"."user_id" = 1 AND "organisation_users_organisations"."role" = 'admin'`.

I do not understand the last part of the query `AND "organisation_users"."id" IN (1)` and believe this should be omitted completely.

Am I doing something wrong or is this a bug in CanCan? Thanks in advance for any help.

Kevin

**Comment by coorasse** [comment]
+1

**Comment by coorasse** [comment]
I'm facing a similar issue with the following situation:
```
class Group
  has_many :forums, class_name: 'Frm::Forum', foreign_key: 'group_id', dependent: :destroy
  has_many :topics, through: :forums, class_name: 'Frm::Topic', source: :topics
end
```
the following statement

```
@group.topics.accessible_by(Ability.new(current_user))
```
generates this query:
```
SELECT  DISTINCT "frm_topics"."id", "frm_topics"."created_at" AS alias_0 FROM "frm_topics" LEFT OUTER JOIN "frm_forums" "forums_frm_topics" ON "forums_frm_topics"."id" = "frm_topics"."forum_id" LEFT OUTER JOIN "groups" ON "groups"."id" = "frm_forums"."group_id" LEFT OUTER JOIN "group_participations" ON "group_participations"."group_id" = "groups"."id" LEFT OUTER JOIN "frm_categories" ON "frm_categories"."id" = "frm_forums"."category_id" INNER JOIN "frm_forums" ON "frm_topics"."forum_id" = "frm_forums"."id" WHERE "frm_forums"."group_id" = $1 AND ...
```

at the moment I solved with:
```
Frm::Topic.accessible_by(Ability.new(current_user)).where(groups: {id: @group})
```

but I don't really like it.

This is how I defined the ability:

```
can :read, Frm::Topic, forum: {group: {group_participations: {user_id: user.id}}}
```

**Comment by Senjai** [comment]
@coorasse @kreintjes Thank you for the report.

**Comment by coorasse** [comment]
The problem should be easily solvable using scopes. 
Please see the following example: https://gist.github.com/coorasse/f1174b618651fcee8c65525d38b36120

this looks like a valid solution, therefore I am going to close this issue. If the problem persists, please feel free to comment again
