### ISSUE TITLE
Specification of rule semantics?

### ISSUE THREAD

**Issue by mbrock** [CanCanCommunity/cancancan#166]
Hello! Is there a semi-formal specification of the exact rules for matching abilities? I want to create an adapter for NoBrainer (the RethinkDB ORM), but I feel unsure about exactly how to implement the `database_records` method.

It doesn't seem obvious that the existing adapters even implement the same semantics. For example, the `DataMapperAdapter` seems like the simplest implementation, but it processes "unions first, then differences" in a way that my limited brain has difficulty figuring out whether it's equivalent to the logic performed by other adapters.

Since the `DataMapperAdapter` has the least database-specific cruft, I would like to use it as a basis, but I'm not sure.

Maybe it would be a good idea to have a generic test suite that validates the rule semantics for each ORM adapter, so that you can implement an adapter without writing your own test suite.

**Comment by Senjai** [comment]
@mbrock From the looks of things, the adapter code is pretty rough currently after the rails 4 upgrade and I haven't had a chance to look at it. I'd be willing to ping you on any work I do on it and get your input if you have any suggestions that would make this implementation easier for you.
