### ISSUE TITLE
List current_user abilities

### ISSUE THREAD

**Issue by devaroop** [CanCanCommunity/cancancan#169]
A list of current_user's abilities would really help client side apps(like AngularJS, EmberJS) to paint the UI based on that. The list could include default CRUD operations along with custom options from the ability class.

Please let know if this is desired, I will be happy to develop and raise a pull-request.

**Comment by Abdenasser** [comment]
+1

**Comment by Stormcore** [comment]
Awesome! Really need this feature!

**Comment by caseywatts** [comment]
This sounds really useful!

**Comment by giedriusr** [comment]
@devaroop I just wanted to create a new issue/feature regarding this. This is really useful in case you described above. Will you start working on this?

**Comment by devaroop** [comment]
Sure, will be happy to contribute. Starting...

**Comment by giedriusr** [comment]
:+1: awesome

**Comment by Senjai** [comment]
Closing to focus additional conversation on #208
