### ISSUE TITLE
Include extra args in AccessDenied exceptions

### ISSUE THREAD

**Issue by phallguy** [CanCanCommunity/cancancan#172]
We have certain permissions that are only enabled after the user has entered there password for a given session. This allows us to remember the user and show some limited info without them entering a password on each visit while also protecting the user's important information with their password.

To do this we catch the CanCan::AccessDenied exception and test if they would have been authorized had they entered their password. This works well for most authorization checks. It only fails if there are additional args int the authorize! block like so

``` ruby
authorize! :show, :named_feature, user_id: user.id
```

We can't recheck this demand because the AccessDenied exception does not include the `user_id: user.id` hash.

**Comment by blackst0ne** [comment]
I would like to this feature implemented in Cancancan.   
Any plans on this?

**Comment by coorasse** [comment]
I'd be willing to accept a PR related to this issue

**Comment by kraflab** [comment]
:wave: I put up a PR for this, here: https://github.com/CanCanCommunity/cancancan/pull/482

**Comment by coorasse** [comment]
will be release in 2.2.0
