### ISSUE TITLE
Defining a combined complex ability rule

### ISSUE THREAD

**Issue by miegs3** [CanCanCommunity/cancancan#175]
I have a complex rule that I can't seem to define, a user can read their own letters or if they have permission they can read letters of others that aren't linked to any type (if they are then the type controls who sees it).

```ruby
class Letter < ActiveRecord::Base
  belongs_to :letter_template
  has_one    :letter_template_type, through: :letter_template
end

class LetterTemplateType < ActiveRecord::Base
  has_and_belongs_to_many :types
end
```

I have tried this, thinking it would cover it but looking at the resulting sql it does an "or (not letter matching rule)" instead of "and (not letter matching rule)".

```ruby
can :read, Letter
cannot :read, Letter, letter_template_type: { types: { active: [true, false] } } # the active [true, false] is just to find any type
```

The other way I tried was with a block/scope but then it complains
"CanCan::Error:
       Unable to merge an Active Record scope with other conditions. Instead use a hash or SQL for read Letter ability."

```ruby
can :read, Letter, Letter.without_type do |l|
  l.letter_template_type.nil? || l.letter_template_type.types.empty?
end
```

Can anyone help me define a rule for this situation?

**Comment by dgilperez** [comment]
:+1:

**Comment by bryanrite** [comment]
Since this isn't an issue with Cancancan, please take it to the mailing list or SO.

Thanks!
