### ISSUE TITLE
specific columns?

### ISSUE THREAD

**Issue by cj** [CanCanCommunity/cancancan#176]
Hi, is it currently possible to do this in the develop branch? https://github.com/CanCanCommunity/cancancan/wiki/CanCan-2.0#resource-attributes

Many thanks!

**Comment by bryanrite** [comment]
Unfortunately not, the Cancan2.0 branch is an unfinished branch by Ryan that I have not had a chance to dig into. I have been told it is used by people but I do not use it myself. I don't imagine adding that functionality as its described there but a comparative idea is being discussed here: https://github.com/CanCanCommunity/cancancan/issues/143
