### ISSUE TITLE
Rule#matches_conditions_hash: return used in enumerable.all? block

### ISSUE THREAD

**Issue by eLod** [CanCanCommunity/cancancan#177]
In `Rule#matches_conditions_hash` [there's](https://github.com/CanCanCommunity/cancancan/blob/75b9de36796ba0291710f33295780e1f15aa4ac8/lib/cancan/rule.rb#L111) a `return` statement in a block for `Enumerable#all?`, which causes it to not check other conditions (introduced by 7a60774a5076ec09f7185d3cff217ac0557544f8). Did i miss something? I guess the fix is just to replace it with an if-else.

**Comment by Senjai** [comment]
@eLod While I agree that this is confusing, this is just a short circuit and I dont think it changed the behaviour from the original diff.

Before it was represented https://github.com/CanCanCommunity/cancancan/commit/7a60774a5076ec09f7185d3cff217ac0557544f8#diff-5e5b3568dd7bbc904edf396ab78919ccL110 which would return the adapter version, as it does here.

I would accept a pull request for a change to make it more clear.

**Comment by eLod** [comment]
@Senjai i'm not sure if there's a miscommunication, i'm saying the new code is not working right, because it uses a `return` statement in `Enumerable.all?` effectively short-circuiting, so whatever is in conditions only the first is checked, whether it allows or refuses determines the return of the full expression and this is wrong (IMHO), this was not like that before.

**Comment by Senjai** [comment]
@eLod Sorry, I misread. You're correct, this should cause a local jump error. Would you be willing to send a PR for this?

**Comment by eLod** [comment]
@Senjai i'm willing to try, however i need a little assistance regarding to specs, as i'm not sure what to test exactly (looking at the current test suite it does not seem that you have specs specifically for `matches_conditions_hash?` or `adapter.override_conditions_hash_matching?` and `adapter.override_condition_matching?`).
