### ISSUE TITLE
AbstractAdapter.find raises exception when id doesn't exist on ActiveRecord object

### ISSUE THREAD

**Issue by cjeffries** [CanCanCommunity/cancancan#182]
At the moment the ```AbstractAdapter.find``` method raises an error in a Rails project if a user navigates to an ID of a model that is authenticated by CanCan. For example if you try to navigate to ```/resource/:id``` and a resource with that id does not exist, an exception is raised.

This error is different to the standard error that is usually raised. I've extended the gem in my project to use the method ```.find_by(id: id)``` instead. This exception is no longer raised, which is great!

I realise that not all 'models' that use this method will be ActiveRecord ones. I've implemented a change that allows models being passed to the method that respond to ```find_by``` to use it in order to suppress the exceptions raised by ```find```.

I imagine the implementation of this method is intentionally simplistic. That being said, would there be a point to me submitting a PR for the changes I've made?

Thanks for the work on the gem thus far, it's great!

**Comment by bryanrite** [comment]
Thank you! Yes, it is an issue others have seen, started in rails 4 with `find_by` being added: #193

**Comment by walterdavis** [comment]
I have just suffered through a rash of 500 errors in place of 404s, where I had to go through a large application replacing find_by() with find_by!() to get the expected RecordMissing error. I wonder if the "pave the cowpaths" crowd will change this behavior in Rails core at any point.

Walter
