### ISSUE TITLE
is cancancan a direct replacement for cancan?

### ISSUE THREAD

**Issue by dwaynemac** [CanCanCommunity/cancancan#183]
I'm using CanCan on some projects. version 1.6.8

Is cancancan a direct replacement or should I make changes to my code to migrate to cancancan?

**Comment by freemanoid** [comment]
I experienced some issues after the migration but it wasn't too hard to fix. Having a good test suite will help you to migrate smoother.

**Comment by dwaynemac** [comment]
ok. thxs.
