### ISSUE TITLE
Error on scoped controller

### ISSUE THREAD

**Issue by leosmeira** [CanCanCommunity/cancancan#185]
My APP:

```
class Client::ApplicationController < ApplicationController

  # Devise
  before_action :authenticate_client!

  # Cancan
  def current_ability
    @current_ability ||= AbilityClient.new(current_client)
  end

end
```
```
class Client::ClientsController < Client::ApplicationController

  # CanCan
  load_and_authorize_resource

  .
  .
  .
end
```
ERROR:
undefined local variable or method `current_user' for #<Client::ClientsController:0x007fb71153a550>

cancancan (1.10.1) lib/cancan/controller_additions.rb:357:in `current_ability'
cancancan (1.10.1) lib/cancan/controller_resource.rb:215:in `current_ability'
cancancan (1.10.1) lib/cancan/controller_resource.rb:77:in `load_collection?'
cancancan (1.10.1) lib/cancan/controller_resource.rb:33:in `load_resource'
cancancan (1.10.1) lib/cancan/controller_resource.rb:25:in `load_and_authorize_resource'
cancancan (1.10.1) lib/cancan/controller_resource.rb:10:in `block in add_before_filter'

**Comment by freemanoid** [comment]
I see `current_client` in the code not `current_user` (as cancancan expect). That's not a cancancan problem. Anyway you can easily fix it by delegating `current_user` to `current_client`:
```ruby
def current_user
  current_client
end
```

**Comment by leosmeira** [comment]
Good idea!

I remember when I used the cancan gem that I did not set current_user to function properly.

Thank's for your help.
