### ISSUE TITLE
eager loading on nested resource

### ISSUE THREAD

**Issue by casertap** [CanCanCommunity/cancancan#188]
I have the nested resource 

````
       resources :clubs do
            resources :members
        end
```

in members_controller
```
class AdminClubs::MembersController < AdminClubs::SecureController
    load_and_authorize_resource :club
    load_and_authorize_resource :users, :through => :club, :class => User
````
my ability
```
def initialize(user)
   can :manage, Club do |club|
       user.club_admin?(club.id)
   end
   can :manage, User, id: user.club_id
````
when I ask for: admin_clubs/clubs/196
user.club_admin?(club.id) generate only one SQL query

When I ask for the members:  admin_clubs/clubs/196
user.club_admin?(club.id) generate one SQL query for each user displayed on the page but it did not make sense to check each displayed user if they are club_admin or not.

**Comment by bryanrite** [comment]
You can easily eager load an association in your controller without involving Cancancan.

Cancancan will return an AR scope, which you can keep chaining to, so in your index action, you could do:

```ruby
load_and_authorize_resource :club
load_and_authorize_resource :users, :through => :club, :class => User

def index
  @clubs = @clubs.includes(:users)
end
```

Same sort of thing if you were paging a collection action.

**Comment by casertap** [comment]
great. thanks.
