### ISSUE TITLE
What's the best way to write a negative condition?

### ISSUE THREAD

**Issue by marnen** [CanCanCommunity/cancancan#191]
I'd like to put a negative condition in my Ability definition. What I'd ideally like is something like 
```
cannot :update, TimeEntry, not(invoice_id: nil)
```
or a Squeel hook so I could do
```
cannot :update, TimeEntry, { :invoice_id.not_eq => nil }
```

It's not practical to reverse the sense of the conditional here, because the `cannot` is being used to restrict a previous `can`. If I change it to
```
can :update, TimeEntry, invoice_id: nil
```
then it won't interact correctly with the previous broader `can`. Help?

**Comment by bryanrite** [comment]
I would suggest using ability with a block. You can specify a scope and/or more control at the instance level: https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities-with-Blocks#block-conditions-with-scopes

**Comment by marnen** [comment]
@bryanrite I thought about a block, but my understanding was that it wouldn't translate into a direct database query, and so it would be far more inefficient than the hash form. Am I wrong about this?

FWIW, Rails 4 supports `where.not(conditions_hash)`, so ideally I'd love to see cancancan interface with that. Obviously, the problem is that we pass a hash straight to `where`, so there's no way to express `where.not`. Hmm. Maybe I'll figure out some sort of patch for that if there's no good way for the time being.

**Comment by bryanrite** [comment]
It uses the scope part on collection routes so it is efficient for multiple records, and uses the block part for instance routes, where the instance is already loaded... so you shouldn't have any issues with efficiency. In fact, if you only specify a block and try to authorize a collection-type route, it'll complain.

I agree it would be nice to be able to use some of the new Rails 4 query functionality.

**Comment by marnen** [comment]
That also means I have to write the same query twice, once in the scope definition and once as a block. I really, really don't like that.

I'm currently trying to patch `ActiveRecord4Adapter`.

**Comment by marnen** [comment]
Pull request at #192.
