### ISSUE TITLE
Add default load_resource :through behaviour

### ISSUE THREAD

**Issue by waissbluth** [CanCanCommunity/cancancan#194]
I wonder if it would be a good idea to allow this:

      class BooksController < ApplicationController
        load_resource :author
        load_resource :book, :through => :author
      end

To be written as:

      class BooksController < ApplicationController
        load_resource :book, :through => :author
      end

So that the default case (when `:author` does not need any further configuration) is more succinct.

**Comment by bryanrite** [comment]
I think I prefer the more explicit way.

Automatically assuming we want to load and/or authorize a resource when using `through` would break things like: `load_resource :book, through: :current_user`, and often times you don't need to authenticate/load the parent object and doing so automatically would be confusing or problem-causing.

I agree, it would be convenient for a lot of cases, but when dealing with authorization, I feel like being explicit is a bit better than not.
