### ISSUE TITLE
List of things user can?

### ISSUE THREAD

**Issue by firedev** [CanCanCommunity/cancancan#195]
Hi,

This is probably related to #169. How one would list everything user `can? :manage` for example?

Here is a concern for `Ability` I came up with, but I am sure there must be a better way:

```ruby
# models/concerns/can_tell_what_it_can_do
module CanTellWhatItCanDo
  extend ActiveSupport::Concern

  def can_do(action)
    rules.map do |r|
      next unless r.actions.include? action
      r.subjects.flat_map(&:name)
    end.flatten.compact.uniq
  end
end

current_ability.can_do(:manage)
=> ["Page", "User"]
```

**Comment by nicolas-besnard** [comment]
Is `current_ability` the response ?

**Comment by firedev** [comment]
Thanks. Anything I can improve apart from that?

**Comment by alperkokmen** [comment]
hi @firedev, have you made any progress with your implementation? i am looking for something similar to use on client-side?

**Comment by firedev** [comment]
Nope, that's what I am using at the moment.

**Comment by ogerman** [comment]
Here is small code snippet, which implements abilities map.
https://github.com/runemadsen/cancan-backbone/blob/master/README.md#setup

**Comment by Senjai** [comment]
Closing to focus discussion on #208
