### ISSUE TITLE
load_and_authorize_resource with inherited controller 

### ISSUE THREAD

**Issue by Yoshyn** [CanCanCommunity/cancancan#197]
Hi, 

I got a very simple concern with load_resource and 2 models. Let's see the code

```ruby
MyModel.count => 4
MyParentModel.first.my_model.count => 1
```

```ruby
class MyModelsController < ApplicationController
  load_and_authorize_resource :my_model

  def index
    raise @my_models.count # => 4, all is good
  end
end
```
```ruby
class ParentNamespace::MyModelsController < Admin::MyModelsController
  load_and_authorize_resource :my_parent_model
  load_resource :my_model, through: :my_parent_model,

  def index
    raise @my_models.count # => 4. It's keep the inherited load_and_authorize_resource 
    # I except that it's override the parent load_ressource 
  end
end
```

Of course, if i inherit directly from ApplicationController, it's work :

```ruby
class ParentNamespace::MyModelsController < ApplicationController
  load_and_authorize_resource :my_parent_model
  load_resource :my_model, through: :my_parent_model,

  def index
    raise @my_models.count # => 1
  end
end
```

I've try all options available for the load_and_authorize_resource and event try to use the skip_load_and_authorize_resource but i did not success to make it work as i wanted.

Is it a bug or is it the nominal behavior?

**Comment by Yoshyn** [comment]
Ok, find a begin of answer

I modify the load_ressource like this :

```ruby
    def load_resource
      unless skip?(:load)
        if load_instance?
          self.resource_instance = load_resource_instance # was : ||= load_resource_instance
        elsif load_collection?
          self.collection_instance = load_collection # was : ||= load_collection
        end
      end
    end
```

It's work as i expect now but i make fail the following test :
```ruby
    it "does not load resource into an instance variable if already set" do
      controller.instance_variable_set(:@model, :some_model)
      resource = CanCan::ControllerResource.new(controller)
      resource.load_resource
      expect(controller.instance_variable_get(:@model)).to eq(:some_model)
    end
```
So this is the nominal behavior. Why?

Is it conceivable to add a parameter like : `override` (with false by default) or something like that to fix my concern :

```ruby
class ParentNamespace::MyModelsController < ApplicationController
  load_and_authorize_resource :my_parent_model
  load_resource :my_model, through: :my_parent_model, override: true

  def index
    raise @my_models.count # => 1
  end
end
```

Or this behaviors is here to prevent some errors i don't see at first look?

**Comment by Senjai** [comment]
@Yoshyn, I don't think you should be changing how your parent has loaded that resource, if you're subclassing from that controller. 

`skip_load_and_authorize_resource` should work correctly for skipping the behavior of the parent, but when you try and redefine that behaviour, there may be some issues with memoization there. 

I haven't had enough time to become very familiar with the controller additions module just yet but I would suggest coming up with an architecture where you don't have to perform this kind of override.
