### ISSUE TITLE
Rescue AccessDenied in ApplicationController with automatic redirect to controllers index

### ISSUE THREAD

**Issue by ginolon** [CanCanCommunity/cancancan#198]
Hi at all! Thanks for your beautiful job!

The title is clear enough, I think.

I'm using in my app in **ApplicationController** this code:

```
class ApplicationController < ActionController::Base
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end
end
```

instead of root_url I want to redirect to the **controller index** based on which controller is raising the error.

How to?

**Comment by Yoshyn** [comment]
You have the controller_name available in the block, you can send all path you want.

For example : ```redirect_to send("something_#{controller_name}"_path)```
You can maybe also write : ```redirect_to action: :index```

But take care of this, if you don't have permission on your index page, you will loop on the error.

**Comment by ginolon** [comment]
None of these works. How to?

**Comment by Yoshyn** [comment]
Cause i write my comment to fast. Try ```redirect_to send("something_#{controller_name}_path")```

**Comment by ginolon** [comment]
Great! So good!
