### ISSUE TITLE
Feature: accessible_by with includes vs joins (ActiveRecord 4+)

### ISSUE THREAD

**Issue by arambert** [CanCanCommunity/cancancan#203]
Take for instance : 

    Project belongs_to :team
    Team has_many :teams_users

    # and in ability.rb
    can :read, Project, team: { teams_users: {user_id: @user.id}}

    projects = Project.accessible_by(current_ability)

In this query, Cancancan will load all the teams associated with the user (and all the TeamsUser objects) [see: https://github.com/CanCanCommunity/cancancan/blob/develop/lib/cancan/model_adapters/active_record_4_adapter.rb#L17].
The user may belong to hundreds of teams, the team object could be big... This could create a huge memory footprint for no real reason.

Sometimes we do not want to load all the associated objects, we could do so by using joins instead of includes+references.
What is your opinion on this ? Is there any other cancancaner interested in such feature ?

**Comment by Senjai** [comment]
@arambert I'm not sure this is still an issue or not for you. It is to the best interest of the community to use includes versus joins here. There may be room for improvement on CanCan's side here, as a stopgap you can define your ability with a block, and specify your condition yourself:

https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities-with-Blocks

**Comment by arambert** [comment]
This is not an issue for me anymore. Like you're suggesting, I have set my abilities with blocks and defined «Policy» classes (à la Pundit) to be used in ability blocks and handle optimized accessible_by methods.

**Comment by Senjai** [comment]
@arambert We will be moving to joins, apologies. I'm glad you have a workaround. There are a few other issues and PR's about this, I'll close this one in favor of those. See https://github.com/CanCanCommunity/cancancan/pull/171
