### ISSUE TITLE
How does CanCan's nested resources handle update and destroy?

### ISSUE THREAD

**Issue by geralddzx** [CanCanCommunity/cancancan#207]
class TasksController < ApplicationController 
  load_and_authorize_resource :project 
  load_and_authorize_resource :task, :through => :project 
end

Based on the above demo from CanCan's official github page. It is first loading the project, and then using the project's read permission to authorize the tasks. How does this work for update and destroy? In update and destroy, there is no params[:project_id] because the route is PUT: tasks/:id. Therefore, it is impossible to load the project to authorize the tasks.

**Comment by jpmermoz** [comment]
I have the same question.
Also, is there any chance to load the project object automatically?

For example, if I go into /tasks/1 it would be nice to have the @project object loaded.

**Comment by coorasse** [comment]
Please refer to [StackOverflow for questions](http://stackoverflow.com/questions/ask?tags=cancancan&title=How%20does%20CanCan%27s%20nested%20resources%20handle%20update%20and%20destroy?). Thank you! :)
