### ISSUE TITLE
New Maintainer Needed!

### ISSUE THREAD

**Issue by bryanrite** [CanCanCommunity/cancancan#209]
Hey all,

As you've noticed, there has been no significant progress made recently on Cancancan... on integrating pull requests or the next major version. Unfortunately things in my personal life have made it difficult to find time to continue working on Cancancan. For the last few months I always think I'll find the time but it doesn't seem to be happening and a lot of great contributions are going un-merged.

Instead of letting it stagnate further, I'm hoping I can find a person or two (or many) to take over the reigns of the project. Cancancan is still very relevant in today's Rails ecosphere and I love for someone else to keep it alive.

I would still like to stay involved in the ongoing discussions as CCC evolves but need someone else to manage the roadmap and development going forward.

Thanks so much!

**Comment by Kiloreux** [comment]
I can help with that , got some free time these days , i can use it to help with it 
.

**Comment by anthonylewis** [comment]
I've never contributed to CCC, but I'm a long time user. I'd be happy to help keep this project going.

I'll try to verify some of the open pull requests tomorrow and hopefully get things moving again.

**Comment by maxhm10** [comment]
I'd love to help out. I'm gonna spend the next week getting familiar with the codebase and check issues/PRs. Think of it as a helping hand, not as a lead though :)

**Comment by sleungcy** [comment]
I'd love to join the team too.

**Comment by rywall** [comment]
I'd be willing to help out as well. :)

**Comment by markpmitchell** [comment]
I can't take primary responsibility, but I would be happy to review the occasional patch.

**Comment by bronislav** [comment]
I also would like to became member of the team. By the way, there is one my unmerged pull requests (#135).

**Comment by bryanrite** [comment]
Thanks for all the interest everyone! Its so nice to work with such a great community.

My next dilemma is how to hand off the project... I guess just giving everyone admin rights to @CanCanCommunity might cause a bit of a traffic jam :smile: 

Could someone take leadership by reviewing the outstanding PRs or get a start getting a release ready or something? I can give this person admin rights and then they can start to manage from there. Please feel free to ask any questions you might have.

**Comment by Senjai** [comment]
@bryanrite I'd be willing to take the project. We use it for all of our clients and in Spree so it's pretty important to us. However, as I work during the week, I wouldn't be able to pick this up until the weekend.

**Comment by Senjai** [comment]
I can go through the outstanding pull requests this afternoon if that works.

**Comment by itsmechlark** [comment]
Count me in @bryanrite! :+1:

**Comment by Senjai** [comment]
Hey guys. I've decided to help out with the load. I've gone through all of the issues and am still going through the PR's. I've marked and identified a few high priority bugs if anyone would like to start poking at those. Don't worry if its assigned to me, it's just so I can sort lists more efficiently.
