### ISSUE TITLE
Update action doesn't get sanitized

### ISSUE THREAD

**Issue by joostliketoast** [CanCanCommunity/cancancan#212]
activity.rb
----
```ruby
belongs_to :organization
```

ability.rb
----
```ruby
can [:create, :update], Activity, state: ['inserted', 'drafted'], organization_id: user.organizations.map(&:id)
can [:new, :preview], Activity, organization_id: user.organizations.first.id
```

activity_controller strong params
----
```ruby
def activity_params
    params.require(:activity).permit(:organization_id)
end
```

activity_controller create
----
```ruby
def create
    @activity.assign_attributes(activity_params)
end
```
This one works properly and get caught by the sanitizer when an a invalid *organization_id* was send

activity_controller update
----
```ruby
def update
    @activity.assign_attributes(activity_params)
end
```

This one doesn't get caught by the sanitizer if an invalid *organization_id* is send and happily updates the record. after it has been edited to the invalid *id* it does get caught by the *edit* action when trying to access the record again.

Any idea why this might be happending?

**Comment by Senjai** [comment]
Attributes are assigned automatically with the create action. They are not assigned automatically on the update action. This is confusing I know. After assigning the attributes, and calling authorize! manually, does that work?
