### ISSUE TITLE
Devise wiki update

### ISSUE THREAD

**Issue by obduk** [CanCanCommunity/cancancan#213]
I wanted to check first before modifying the wiki instructions on Devise.

A good idea rather than doing:

```ruby
redirect_to login_url, :alert => "You have to log in to continue."
```

when the user is not logged in, is to do:

```ruby
throw(:warden)
```

as this will then be handled by Devise, and any customization for what to do for the login process will get applied.

**Comment by Senjai** [comment]
@obduk While I don't doubt that you're correct that this could trigger the behavior you've described, it's not really clear what it's meant to do unless you understand the intricacies behind both devise and warden. 

The primary purpose of that entry is just to provide a example of how to rescue from an authorization failure. Not that its always the right choice for every application, just a means of doing so. The existing example is actually really terrible and could use some cleaning if anyone would like to.
