### ISSUE TITLE
"Cannot" with association hash conditions : accessible_by generates incorrect SQL (Postgres / ActiveRecord)

### ISSUE THREAD

**Issue by mjonckiere** [CanCanCommunity/cancancan#214]
First of all, thanks for this gem of a gem ;)

I just stumbled into something that I think might be an edge case, resulting in a bug (at least on postgresql).

I have the following setup (a bit modified for clarity) : 

``` ruby
class Organization < ActiveRecord::Base

   belongs_to :owner, class_name: :Account
   has_many :staff_memberships

end

class StaffMembership < ActiveRecord::Base

  belongs_to :organization
  belongs_to :account

end

class Ability
  include CanCan::Ability

  def initialize(user)
    can :manage, Organization, owner_id: user.id
    can :manage, Organization, staff_memberships: {account_id: user.id}
    # here is the offending line
    cannot :discuss_as, Organization, staff_memberships: {account_id: user.id}
  end

end
```

When I run `Organization.accessible_by(Ability.new(Account.find 1))`, the following SQL is generated (modified for clarity) : 

``` sql

SELECT organizations.*
FROM    organizations
LEFT OUTER JOIN staff_memberships
ON staff_memberships.organization_id = organizations.id
WHERE not (staff_memberships.account_id = 1)
AND ((staff_memberships.account_id = 1) OR (organizations.owner_id=1));

```

The problem here lies with `not (staff_memberships.account_id = 1)`.

If no staff_membership is joined to the record, `staff_memberships.account_id` is `NULL`, so the conditions evaluates to `NULL` and the record is filtered out, which it shouldn't.

Moreover, this SQL would incorrectly select an organization where a staff_membership with account_id 1 exists, if other staff_memberships exist (because of the left outer join)

The correct SQL would use an anti-join, for example : 

``` sql
WHERE NOT EXISTS (
  SELECT FROM staff_memberships 
  WHERE account_id = 1 
  AND organization_id = ?
)
```

**Is there something i'm doing wrong, or is it a feature that is not supported by CCC ? Do I have to use a scope condition in this case ?**

note: I tracked the origin of the offending SQL down to this line : https://github.com/CanCanCommunity/cancancan/blob/develop/lib/cancan/model_adapters/active_record_adapter.rb#L106

note : for the record, here is a workaround using SQL fragments: 

``` ruby
# This is the relevant SQL fragment, generated using AREL
has_membership = StaffMembership.where(account: user).where(organization_id: Organization.arel_table[:id]).exists.to_sql
# matching block
block = ->(organization){ organization.staff_memberships.any?{|m| m.account_id == user_id }}

cannot :discuss_as, Organization, has_membership, &block
```

**Comment by mjonckiere** [comment]
For the record, using raw SQL seems to be an adequate workaround (does not require to use a scope) :

```ruby 
cannot :discuss_as, Organization, StaffMembership.where(account: user).exists.to_sql
# the last argument produces "EXISTS (SELECT FROM staff_memberships WHERE account_id = 1)"
# final where condition is "not (EXISTS...)"
```

**Comment by Senjai** [comment]
@mjonckiere Would you be able to take a look at https://github.com/tiokksar/cancancan/commit/0a9f7d4236410a91125a3136465fda60edc7c231 which claims to solve this problem?

**Comment by mjonckiere** [comment]
@Senjai Haven't tested that yet, but from what I've seen in the code, this should address the problem. Will get back to you when I have time to test this, hopefully before the end of the week

**Comment by 0llirocks** [comment]
I would like to reopen this issue since the behavior is still unchanged. I think the proposed commit was never merged, but might fix the issue.

The commit addresses the issue at its root by checking for _IS NULL_. PostgreSQL can't compare null values with any other value.
