### ISSUE TITLE
undefined method `authorize!' for #<UsersController:0x007f925afb1ed8>

### ISSUE THREAD

**Issue by mcshakes** [CanCanCommunity/cancancan#217]
It can't seem to find 'authorize!'

I added the gem to the gemfile:
gem 'cancancan', "~> 1.10"

Ran:

$ rails g cancan:ability

And filled in that file with this:

class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    can :read, User, id: user.id
  end
end

In my UsersController#Show:

def show
    @user = User.find(params[:id])
    authorize! :read, @user
end

What am I missing here? I had current_user established prior to the gem. 

Thank you

**Comment by anthonylewis** [comment]
Did you restart the Rails server after making these changes?  Are you running Spring?  A `bin/spring stop` never hurts when things aren't showing up correctly.

Also, does your `UsersController` inherit `ApplicationController`? If you type `UsersController.ancestors` in a Rails console you should see `CanCan::ControllerAdditions` in the list. Also, you can try `UsersController.instance_methods` and look for `authorize!`.

**Comment by ThadeuBrito** [comment]
@mcshakes If you're using the rails-api gem, you'll need to manually include the controller methods for CanCan

```ruby 
class ApplicationController < ActionController::API
  include CanCan::ControllerAdditions
end
```

**Comment by Senjai** [comment]
Closing as stale.

**Comment by sina-s** [comment]
Shouldn't this be in the documents?

**Comment by coorasse** [comment]
that's not necessary with the latest version
