### ISSUE TITLE
Wiki - respond_to instead of explicit redirect

### ISSUE THREAD

**Issue by akolomiychuk** [CanCanCommunity/cancancan#218]
I think suggesting using redirect explicitly isn't best option in wiki...

From https://github.com/CanCanCommunity/cancancan/wiki/Exception-Handling :
```ruby
class ApplicationController < ActionController::Base
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to main_app.root_url, :alert => exception.message
  end
end
```

Because there is an issue with ajax requests: if I request a url (to which I don't have access) via ajax I get redirected to the front page inside ajax request and get status 200 OK. This leads to triggering jQuery  ajax success callback, but it shouldn't. I expecting to get `403 Forbidden` instead of `200 OK` in that case.

I think much better will be update wiki to suggest using something like that in order to get correct behavior.

```ruby
rescue_from CanCan::AccessDenied do |exception|
  respond_to do |format|
    format.json { render nothing: true, status: :forbidden }
    format.html { redirect_to main_app.root_url, :alert => exception.message }
    format.js   { render nothing: true, status: :forbidden }
  end
end
```

**Comment by anthonylewis** [comment]
Have you seen the [Authorization in Web Services](https://github.com/CanCanCommunity/cancancan/wiki/Authorization-in-Web-Services) page? I think that would be a good place for your suggestion.

But, ajax requests are so common these days it should probably be mentioned on the [Exception Handing](https://github.com/CanCanCommunity/cancancan/wiki/Exception-Handling) page, too.

**Comment by Senjai** [comment]
I'm fine with either of these. Remember that the example here is to illustrate how to rescue from an AccessDenied exception, not exactly what to do when you do. We should make the assumption the reader knows how to redirect and render based on format in rails, as that is out of scope for this gem.

But I dont mind it being there. Just that we shouldn't focus on it.

**Comment by anthonylewis** [comment]
@Senjai I know from experience that many developers copy and paste from documentation. I agree that this is an example, but I'll bet this exact code is in many apps. I'll update the wiki page in a bit and try to incorporate @akolomiychuk's suggestion.

**Comment by anthonylewis** [comment]
@Senjai @akolomiychuk I updated the two wiki pages mentioned above. Let me know what you think.

**Comment by akolomiychuk** [comment]
Thanks for your feedback. The change is seems pretty well as for me.

Just want to note, that recently (couple of months ago) rails `$.ajax()` is not set-up `Content-Type` header to json by default. So that `format.html` will be triggered for these requests. I'm not sure that is the same behavior is currently there, but I don't see any reasons why it can be changed.

In other hand - requests sent by browser directly always set-up `Content-Type` to `text/html`.

I would suggest put `format.json` before `format.html`, so the json will be a standard response.
```ruby
respond_to do |format|
  format.json { render nothing: true, status: :forbidden }
  format.html { redirect_to main_app.root_url, :alert => exception.message }
end
```

**Comment by anthonylewis** [comment]
@akolomiychuk I reordered the formats as you suggested. Good call. Can we close this issue now?

**Comment by akolomiychuk** [comment]
Looks good for me. Thanks!
