### ISSUE TITLE
Issue with rule precedence when using blocks

### ISSUE THREAD

**Issue by MasterSlowPoke** [CanCanCommunity/cancancan#220]
I noticed that in one of my projects I had my rules in the wrong order, but everything was working anyway. I wrote a quick repro of this here: https://github.com/MasterSlowPoke/cancantest

Example: Given the following Ability file:
```ruby
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    can :manage, User do |user|
        puts "in manage"
        true
    end
    can :read, User do |user|
        puts "in read"
        false
    end
end
```
You would expect a user to be able to do everything but Read a User object.

However, when testing, the rules are evaluated as such:
```ruby
001 > a = Ability.new(User.new)
 => #<Ability:0x007f98012ea130 ...> 
002 > a.can? :read, User.new
in read
in manage
 => true 
003 > 
```
The rules are not being evaluated top to bottom.

**Comment by ericgascoine** [comment]
@MasterSlowPoke 

The privileges described in cancancan are cumulative, so I believe you would have to define it like detailed in https://github.com/CanCanCommunity/cancancan/wiki/Ability-Precedence, and use the cannot option to revoke the rights.

In short can: true, and then can: false is not the same as a can and cannot call.

```ruby
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    can :manage, User do |user|
        puts "in manage"
        true
    end
    cannot :read, User do |user|
        puts "in read"
        true
    end
end
```

**Comment by MasterSlowPoke** [comment]
Ah, I didn't see where can rules where ORed together. If that's the case then everything is working as intended. Closing.

So, if I want to use blocks, I need to make them so that they cascade up instead of down. Biggest filters on the bottom. Makes sense.

**Comment by ericgascoine** [comment]
@MasterSlowPoke 

Not quite... My understanding is that Can Cannot are evaluated in order with respect to each other, but that a can :false will not cancel a can :true, and once you can do something that there are some open issues / pull requests on short circuiting further evaluations.

Block evaluation orders may still be an issue with can / cannot if it's evaluating in the incorrect order, but your Ability as originally specified should never produce the effect you were looking for.

I'm sorry, but I didn't have time to test the ordering as yet, but having hit the same effects you had in my own work, I thought it was worth responding.
