### ISSUE TITLE
load_and_authorize_resource fails with module scope

### ISSUE THREAD

**Issue by TheRealGuardDogGPS** [CanCanCommunity/cancancan#222]
I build mongoid classes on the fly. One class is called Contact. Since I build them on the fly, I place the class in a module so it doesn't conflict with a global class name. The problem is when the controller action is called, load_and_authorize_resource looks for Contact, not MyModule::Contact and fails. How can I pass a module into load_and_authorize_resource so it looks for the class in the module?

**Comment by anthonylewis** [comment]
Would the `class` option help?
```
load_and_authorize_resource class: 'MyModule::Contact'
```
Or is the class name different every time?

**Comment by Senjai** [comment]
What @anthonylewis said, that should fix the issue. Let us know if it doesn't.
