### ISSUE TITLE
Cannot Access Nested Attribute Using Block

### ISSUE THREAD

**Issue by ThinkADRIAN** [CanCanCommunity/cancancan#223]
I was able to get a user (aka thriver) to access their own journal.

Example: Current User is 3 and use http://localhost:3000/thrivers/3/journals works

However, I have pro users with an attribute that contains an array of clients.  I cannot get http://localhost:3000/thrivers/19/journals even if journal.user_id = 19 is in the clients array for current_user.id = 3.

abilty.rb

```
class Ability
  include CanCan::Ability

  def initialize(user)
    ...
    # handle guest user (not logged in)
    user ||= User.new()
    ...

    # the following code works
    can :manage, User, id: user.id
    can :manage, Mood, :user => { id: user.id }
    can :manage, Sleep, :user => { id: user.id }
    can :manage, SelfCare, :user => { id: user.id }
    can :manage, Journal, :user => { id: user.id }

    # the following code does not work
    if user.is? :pro
      can :read, Mood do |mood|
        user.clients.include? mood.user_id
      end

      can :read, Sleep do |sleep|
        user.clients.include? sleep.user_id
      end

      can :read, SelfCare do |self_care|
        user.clients.include? self_care.user_id
      end
      can :read, Journal do |journal|
       user.clients.include? journal.user_id
      end
    end
    ...
  end
end
```

journals_controller.rb

```
class JournalsController < ApplicationController
  ...
  load_and_authorize_resource :user
  load_and_authorize_resource :journal, through: :user, shallow: true
  ...
end
```

routes.rb

```
  resources :users, :path => 'thrivers' do
    resources :moods
    resources :sleeps
    resources :self_cares
    resources :journals
  end
```

schema.rb

```
create_table "users", force: true do |t|
    ...
    t.integer  "clients",                default: [],              array: true
    ...
  end
```

Assistance would be greatly appreciated.

**Comment by Senjai** [comment]
@ThinkADRIAN Please see #200. Does that cover your issue?

**Comment by ThinkADRIAN** [comment]
@Senjai Unfortunately no.  I think the i understand that there is no instance since I am using the index action.

Route:

user_journals GET       /thrivers/:user_id/journals(.:format)            journals#index

I tried

```
can :read, Journal if user.clients.include? :user_id
```

This did not work.  Access is still not granted.

**Comment by nated** [comment]
@ThinkADRIAN According to the [docs here](https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities-with-Blocks#only-for-object-attributes), you can't do this level of permission inspection without passing an instance variable (_relationship dependent_ conditions don't actually make sense without an instance).

If you put add some logging output within the block you'll see it is never run unless an instance variable is passed.

On an aside, I've never seen this syntax before with cancan:
`can :manage, Journal, :user => { id: user.id }`

What I think you meant is (for the same reason above, you need access to the journal instance):
```ruby
can :manage, Journal do |journal|
  journal.user_id == user.id
end
```

**Comment by coorasse** [comment]
Please refer to [Stackoverflow for questions](http://stackoverflow.com/questions/ask?tags=cancancan). Thanks.
