### ISSUE TITLE
Is this logic intended? Is there a better way to do this?

### ISSUE THREAD

**Issue by Honeybunch** [CanCanCommunity/cancancan#224]
What If I want a `can` to pass if:
 - The "Project" instance has an priority < 3 OR
 - The user is an admin
If no instance is passed I still want it to pass if the user is an admin.

The end goal is:
```ruby
# user is admin
can? :edit, Project    # true

# project.priority < 3
can? :edit, @project    #true

# user is not admin
can? :edit, Project     #false

#user is not admin but project priority < 3
can? :edit, @project   #true
```

The logic here gets weird. You may think you can do:
```ruby
if user.admin?
  can :edit, Project do |project|
    project.priority < 3
  end
end
```
But this doesn't work as the `can` won't even get declared unless the user is an admin. You might think you can try:
```ruby
can :edit, Project do |project|
  project.priority < 3
end
can :edit, Project if user.admin?
```
However this doesn't work either. If you DO pass a project it will NEVER check if the user is an admin. The next logical step would be:
```ruby
can :edit, Project do |project|
  project.priority < 3 || user.admin?
end
can :edit, Project if user.admin?
```
Yet if you attempt `can? :edit, Project` it will ALWAYS pass even if the user isn't an admin because the first `can` will default to passing if there is no instance sent and then according to ![Ability Precedence](https://github.com/CanCanCommunity/cancancan/wiki/Ability-Precedence) the second `can` will logically OR with the previous `can`. 

The solution I came up with (that feels really wrong) is:
```ruby
can :edit, Project do |project|
  project.priority < 3 || user.admin?
end
cannot :edit, Project do |project|
  project.priority >= 3 && !user.admin?
end
can :edit, Project if user.admin?
```
The logic here for `can? :edit, Project` is:
 - The first `can` allows the Project to pass by default
 - The `cannot` will revert that and cause it to fail by default
 - The second `can` is now the piece of logic that will determine if the Project passes or fails

So now `can? :edit, Project` will only pass if the user is an admin and `can?: edit, @project` will pass only if the user is an admin OR the project has a priority < 3

Is there an easier way to get this logic? I feel like I'm attempting something unintended for CanCanCan yet I also feel this should be not only possible but easier to do.

**Comment by Senjai** [comment]
@Honeybunch

```ruby
  if user.admin?
    can :edit, Project
  else
    can :edit, Project do |project|
      project.priority >= 3
    end
  end
```

Would be your best solution. You shouldn't be checking for `can? :edit, Project`, you should always be passing an instance of Project seeing as though you have to load one anyway. See #200 for a deeper explination
