### ISSUE TITLE
unauthorized! method not present in cancancan

### ISSUE THREAD

**Issue by swijal** [CanCanCommunity/cancancan#226]
I have ability class as follows:

class Ability
  include CanCan::Ability
  def initialize(role)
    @role = role
    if @role == "guest_user"
      can :read, :all
    end
    if @role == "business_member"
      can :update, Business
    end
    if @role == "payment_member"
      can :update, payment
    end
    if @role == "admin"
      can :manage, :all
    end
  end
end

And in haml it is 

  -if can? :update, Business
    = link_to 'Edit this Business'

Now this is working properly and hiding the link.
But if I try to hit the URL with ../edit then it opens the page.
I want to restrict the functionality. 
i tried using unauthorized! but it says we are not allowed to use it any more.
Any ideas as how can I restrict user to access the edit link (if he tries to hit it manually in absence of edit button from the address bar) if he is not authorized to?

**Comment by bryanrite** [comment]
You must use `load_and_authorize_resource` checks in your controller to enforce your Ability file permissions in the controller. `can?` is just a view helper.

https://github.com/CanCanCommunity/cancancan/wiki/Authorizing-controller-actions
