### ISSUE TITLE
Eager loading on member resource

### ISSUE THREAD

**Issue by lowjoel** [CanCanCommunity/cancancan#228]
Hi there!

I'm using the [Bullet](https://github.com/flyerhzm/bullet) gem which warns when my resources omit includes.

For collection resources, the collections are lazy-loaded, so I can still call `@collection = @collection.includes(:relation)` in any given action.

For member resources, the resource is already loaded by the time is action is called. Is there any way to specify that the resource should have certain things eager loaded without resorting to loading it manually?

Maybe, `load_resource :resource_name, eager_load: :relation`... and it would be loaded for both collection and member resources? It would appear that modifying `ControllerResource#resource_base` would be sufficient to implement this.

I find duplicating Cancancan's logic for determining whether it is a collection or member route, then remembering the resources to load through, isn't particularly DRY.

Comments/ideas on how to move ahead?

**Comment by Senjai** [comment]
Closing in favor of all the other eager loading related PR's open.
