### ISSUE TITLE
CanCan defines the method 'merge' on nil

### ISSUE THREAD

**Issue by sgringwe** [CanCanCommunity/cancancan#229]
Maybe not a bug - could be intended - but CanCan is currently defining 'merge' on nil objects (maybe all objects?). This was discovered while debugging an issue with rails 4.2.3 integration test post requests. There is a line ```default_headers.respond_to?(:merge)``` which returns true because of the merge definition when it was not expected to. I will be submitting a PR to rails soon, but figured it'd be valuable to raise this concern here as well.

**Comment by Senjai** [comment]
@sgringwe Merge is defined here https://github.com/CanCanCommunity/cancancan/blob/develop/lib/cancan/ability.rb#L248

It is not adding the merge method to any object that does not explicitly `include CanCan::Ability`. I would argue this should be more aptly named to avoid using a name like `merge` which has an implied meaning in ruby. That said, people typically use separate plain ruby objects to represent their abilities:

```ruby
class Ability
   include CanCan::Ability
  def initialize(user)
    #....
  end
end
```

So this issue should not raise itself within rails, unless there is something I'm missing.

**Comment by sgringwe** [comment]
@Senjai thanks for the direction. it indeed turned out that a spec had a random ```include CanCan::Ability``` in it which was causing the issue.
