### ISSUE TITLE
Can class defined for authorizing action be accessed to be used for Internationalization?

### ISSUE THREAD

**Issue by swijal** [CanCanCommunity/cancancan#235]
As per the https://github.com/CanCanCommunity/cancancan/wiki/Authorizing-controller-actions#custom-class, if the model class is namespaced differently than the controller you will need to specify the :class option.
Now I have used :class as option.

But while doing exception handling, as per  https://github.com/CanCanCommunity/cancancan/wiki/Exception-Handling, I want to customized message through internationalization.

like below:

*en:
  unauthorized:
    manage:
      (some class which I have used above): "msg what should be loaded once access denied exception is raised"*

Can somebody tell how exactly we can use the class here in internationalization?

**Comment by coorasse** [comment]
Please refer to [Stackoverflow for questions](http://stackoverflow.com/questions/ask?tags=cancancan&title=Can%20class%20defined%20for%20authorizing%20action%20be%20accessed%20to%20be%20used%20for%20Internationalization?). Thanks.
