### ISSUE TITLE
Using with single page apps/javascript frameworks

### ISSUE THREAD

**Issue by fullofcaffeine** [CanCanCommunity/cancancan#236]
Hi!

I'm using EmberJS (through ember-cli) and I'm wondering if there's already a pattern for using `cancancan` with client-side javascript frameworks. I'm sure that the rules need to be defined on the server, which `cancancan` already does well. What I'm wondering is how to properly serialize those rules to the client while keeping things DRY? 

It doesn't sound like something that'd be too hard to generalize and do, but I wanted to see if there's something out there already.

Thanks!

**Comment by coorasse** [comment]
I would just put the result of `can? :do_that, @object` calls into js variables using a good naming convention.

**Comment by Senjai** [comment]
I wouldn't do that. Your frontend should only receive information the backend authorizes you to see. Things like menus and resources should be dynamic. E.g. loading the navigation menu for your frontend app can be authorized via `accessible_by` on the backend and the frontend should only ever see what it needs to see. You shouldn't have to manually check authorization in the frontend, your frontend should just expect anything it gets from the backend is authorized for use for the current user.

**Comment by coorasse** [comment]
Well, the frontend may build itself if is written with a frontend framework like Angular. Then it may needs informations on how to build itself as well and what it can show or not to the user, right?
So the backend will give only objects accessible to the user, you are right.
But is also true that can receive a boolean variable if it has to show a menu option or not.

**Comment by Senjai** [comment]
Sure, but that is an endpoint on the backend for a menu.

e.g. GET /api/navigation/menu_items would return the name and the url of each menu item that the user is allowed to access. The application itself shouldn't have to understand authorization at all. There is another viewpoint that authorization should be dumped to the frontend app so it can make decisions, but I dont believe that should be duplicated.

The counter argument here is that there shouldnt be an API for display purposes. In that I argue the lesser of the evils.

**Comment by coorasse** [comment]
I close this since is not an issue. Please refer to Stackoverflow for questions.
