### ISSUE TITLE
cancancan not work when can :action, :subject

### ISSUE THREAD

**Issue by oncelife** [CanCanCommunity/cancancan#240]
def matches_subject?(subject)                                           
@subjects.include?(:all) || @subjects.include?(subject.name.to_sym) || matches_subject_class?(subject)
end

subject.name.to_sym ,  otherwise can subject not work.

in ablility.rb #can? mechod, i dump the subject params:
"can? subject= [{\"id\"=>41, \"vehicle_type_id\"=>5, \"fleet_id\"=>23, \"driver_id\"=>28, \"plate_no\"=>\"京C12345\", \"enabled\"=>false, \"note\"=>nil, \"created_at\"=>\"2015-08-10T08:09:53.000Z\", \"updated_at\"=>\"2015-08-13T09:02:12.000Z\"}], show   

i'm confused why this info will pass as subject......

**Comment by oncelife** [comment]
anyone ?

**Comment by coorasse** [comment]
what's the question?

**Comment by oncelife** [comment]
add can :action_name, :subject_name in ability.rb file, but not work;     

then i look into the source code, it works after change matches_subject method from subject to subject.name.to_sym

**Comment by coorasse** [comment]
Is it solved for you? 
Do you think there is an issue in cancancan? If that is the case: can you provide steps to reproduce the error?

Thanks!

**Comment by oncelife** [comment]
sorry, may be i use in the wrong way. as i'm not use it.
