### ISSUE TITLE
Join for nested hashes

### ISSUE THREAD

**Issue by gilbertquri** [CanCanCommunity/cancancan#243]
According to the wiki for hash of conditions (https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities#hash-of-conditions) the query will perform an INNER JOIN but my observation is LEFT OUTER JOIN instead. Is this a bug?

**Comment by coorasse** [comment]
This is wrong in the docs. Cancancan actually perform outer joins

**Comment by Senjai** [comment]
I'm going to have to eventually restrict edit access to the wiki to prevent stuff like this going forward. I'd like to add some people as maintainers of the wiki if anyone is interested.

**Comment by gilbertquri** [comment]
BTW, the docs should probably point out that keys in hash of conditions must be symbols (as opposed to strings).
