### ISSUE TITLE
Nested resource authorization fails with mongoid

### ISSUE THREAD

**Issue by zeitnot** [CanCanCommunity/cancancan#248]
I am using `rails ~> 4.2.3`, `mongoid ~> 4.0.1` and `cancancan ~> 1.12.0`. 

The following implementation fails and throws 403 status code.

```ruby
load_and_authorize_resource :project
load_and_authorize_resource :task, through: :project_id, class: Project::Task
```

There a `Project` and it has many `Task`. I want to reach `task` record through `project` but I could not. Maybe I am wrong somewhere and I need some help.

**Comment by d4rk5eed** [comment]
What error do u get?

**Comment by zeitnot** [comment]
403
