### ISSUE TITLE
RSpec 3 Compatilbity

### ISSUE THREAD

**Issue by NekoNova** [CanCanCommunity/cancancan#250]
Hello,

Running CanCanCan under RSpec 3 produces some deprecation warnings:

```
Deprecation Warnings:

`failure_message_for_should_not` is deprecated. Use `failure_message_when_negated` instead. Called from /var/lib/jenkins/.rvm/gems/ruby-2.2.2@riskmethods/gems/cancancan-1.7.1/lib/cancan/matchers.rb:19:in `block in <top (required)>'.

`failure_message_for_should` is deprecated. Use `failure_message` instead. Called from /var/lib/jenkins/.rvm/gems/ruby-2.2.2@riskmethods/gems/cancancan-1.7.1/lib/cancan/matchers.rb:15:in `block in <top (required)>'.
```

Would be cool to have these switched into the new methods.
was originally reported here as well : https://github.com/ryanb/cancan/issues/997

**Comment by Senjai** [comment]
@NekoNova Could you submit a PR?

**Comment by NekoNova** [comment]
Will make one tommorrow!

**Comment by NekoNova** [comment]
running some tests, then I will open the PR if it does what it's supposed to be doing.

**Comment by NekoNova** [comment]
https://github.com/CanCanCommunity/cancancan/pull/251

**Comment by abhishekbose87** [comment]
@Senjai This issue can be closed as PR https://github.com/CanCanCommunity/cancancan/pull/251 has been merged.

**Comment by NekoNova** [comment]
will close it myself ;)
