### ISSUE TITLE
check_authorization with multiple authorize! calls

### ISSUE THREAD

**Issue by obduk** [CanCanCommunity/cancancan#256]
So we have the following problem which I am intending to add as a new feature to CanCan to fix, however I thought I would check first before proceeding with work.

Say you have an application where you have `check_authorization` enabled.

Different pages check various authorization, e.g. `authorize! :read, @article`

There is also a admin area that has

```
before_action :authorize_admin_area

def authorize_admin_area
  authorize! :read, :admin_area
end
```

However, each admin page also want's to authorize.

We were thinking of adding an option that would not make the `check_authorization` pass, so it would force the programmer to call `authorize!` in their action, e.g.

```
authorize! :read, :admin_area, require_further_auth: true
```

or

```
pre_authorize! :read, :admin_area
```

Questions:
* Would this be useful to other people
* Which method is better, an option or a different method

Thanks

**Comment by coorasse** [comment]
To me is not very clear what you are trying to achieve, sorry :(
Why you want to force the call to `authorize!` ?

**Comment by obduk** [comment]
Sorry not very clear, here is a better example

```
class ApplicationController
  check_authorization
end

class CommentController < ApplicationController
  def show
    authorize! :show, @comment
  end
end

class Admin::ApplicationController < ApplicationController
  before_action :authorize_admin_area

  def authorize_admin_area
    authorize! :read, :admin_area
  end
end

class Admin::CommentController < Admin::ApplicationController
  def delete
    authorize! :delete, @comment
  end
end
```

Because we have `authorize! :read, :admin_area` in `Admin::ApplicationController`, every action in any admin controller will authorize, so if the programmer misses of the `authorize! :delete, @comment` the `check_authorization` will still pass.

**Comment by Senjai** [comment]
I would not support something like this, mostly because this just works in Solidus.

https://github.com/solidusio/solidus/blob/master/backend/app/controllers/spree/admin/base_controller.rb#L16-L24

Would that example not work for you? We authorize our entire backend with that.
