### ISSUE TITLE
Restricting ability based on current user. 

### ISSUE THREAD

**Issue by zwarburg** [CanCanCommunity/cancancan#259]
In my app I have a concept of system notes. What I am trying to do is make is so that users can only edit notes that:
1) Are less than 1 week old
2) They themselves created. 

The first one is trivial, the second one is proving difficult. Given the method shown below `editable_by?(user)`, how can I call it in the ability passing in a user, specifically `current_user`.

**notes.rb (note model)**
```
module Admin
  class Note < ActiveRecord::Base
    .....
    def editable_by?(user)
      self.created_at > 1.week.ago && note.user_id == user.id
    end
  end
end
```

**ability.rb**
```
class Ability
   include CanCan::Ability
   def initialize(user)
      ....
      can :update, Note, "editable_by?(user)" => true
   end
end
```

**Comment by Senjai** [comment]
```ruby
can :update, Note, Admin::Note.old_notes
can :update, Note, user: { id: user.id }
```

Where old_notes is a rails scope on the model. You could add the second statement in the same scope, but I would avoid that as they're two separate scenarios.

**Comment by zwarburg** [comment]
@Senjai thanks!!

**Comment by dgynn** [comment]
I believe doing multiple can statements would cause the conditions to be OR-ed rather than AND-ed.

You probably need to do this as a block like...
```ruby
can :update, Note do |note|
  note.editable_by?(user)
end
```
That won't work if you are using your rules with scopes but would work for simple checking.

**Comment by coorasse** [comment]
Hi everybody, 
as a watcher of this gem I would like to point out again to not use issues for questions.
Is really annoying for watchers and I think questions do not belong to github issues but to stackoverflow instead. Please post questions there.
