### ISSUE TITLE
Inconsistency with checking and defining abilities using the array syntax.

### ISSUE THREAD

**Issue by Senjai** [CanCanCommunity/cancancan#261]
Source: https://github.com/solidusio/solidus/pull/445

While:

``` ruby
can [:admin, :create], Spree::User
```

Is valid in the ability to declare that a user can be created or admin'd, checking it the same way does not work. 

It worked before because in testing we had stated that users with the user management role can manage users which makes any check pass, regardless of the validity of the check. We do still need to check for admin privileges here as well because all users can create users when they sign up.

Example:

``` ruby
require_relative "config/environment"

class MyAbility
  include CanCan::Ability

  def initialize user
    can [:admin, :create], user
  end
end

user = Spree::User.last
ability = MyAbility.new(user)

p ability.can? :admin, user # true
p ability.can? :create, user # true
p ability.can? [:admin, :create], user #false

ability.can :manage, user

p ability.can? [:admin, :create], user #true
```

If we can define permissions using an array, we should be able to check them using an array. Is there an issue that prevents this?

**Comment by Mohit-Pawar** [comment]
hi @Senjai can you please check the pull request for can? with multiple action for above issue

**Comment by Senjai** [comment]
The can statement defines the admin and create actions for the user class seperately. It does not insert an array object as a an action to be checked against later. If anything, we should probably enforce that can? simply take a symbol or list of symbols.

**Comment by coorasse** [comment]
A PR is welcome about that. I close the issue since is an enhancement IMHO
