### ISSUE TITLE
Index action is not aliasing to read. 

### ISSUE THREAD

**Issue by zwarburg** [CanCanCommunity/cancancan#264]
I have the following permissions setup in my `ability.rb` model yet my user is not able to use the index action. I found that if I added `can :index, :all` then the user was able to hit the index action. My understanding was that `:index` is already aliased to `:read`...

```
alias_action :create, :read, :update, :destroy, :to => :crud
can :crud, :all
```

**Comment by zwarburg** [comment]
@acvwilson

**Comment by dgynn** [comment]
Aliases only work for one level of aliasing. That may not be documented anywhere. So the best thing would be to add `:index` to your `:crud` alias.
```ruby
alias_action :create, :read, :update, :destroy, :index, :to => :crud
can :crud, :all
```

Or, you can use the `:manage` action if you want to define a rule that allows the user to perform *any* action rather than defining a `:crud` alias as a catch-all.
```ruby
can :manage, :all
```

**Comment by zwarburg** [comment]
@dgynn  I specifically did not want to use manage all because of some custom permissions I have setup. Additionally aliases actually do work across multiple levels, turns out the issue was with how I was calling `can?`:
```
redirect_to root_path unless can?(params[:action], User)
```

Apparently `can?` is unable to process strings. As soon as I changed it to:
```
redirect_to root_path unless can?(params[:action].to_sym, User)
```

It worked just fine. Would be nice to have the ability to pass in a string, not require a symbol.

**Comment by dgynn** [comment]
Oh. You are absolutely right about the alias expansion. Sorry about that misinformation.

**Comment by Senjai** [comment]
@zwarburg You can use strings.

If you define your ability with strings, you can check them with strings. If you define your ability with symbols, you can check them with symbols. We want to perform as little transformations on the action in the effort to "guess" what the developer wants as possible. The choice is yours here. Guessing leads to maintenance issues in the future, and guessing wrong leads to bugs.

Also, you can use the `action` method, within a controller instance, which returns a symbol. You don't need to look in the params.
