### ISSUE TITLE
Ability check on submitted parameters

### ISSUE THREAD

**Issue by denisemauldin** [CanCanCommunity/cancancan#267]
How do I get cancancan to check an parameter to see if the user can update?

Controller gets:

Parameters: {"offer"=>{"revoked"=>"1", "user_id"=>"14"}, "id"=>"53"}

ability.rb:

can :update, Offer, :user_id => user.id
cannot :update, Offer, { :revoked => nil }   

controller code:

@offer.update(params)

This is giving me a Cancancan error saying that the user is not authorized. @offer.update(params) should change revoked to 1, so it should allow the action because the user can update their Offer information.  Do I need to update @offer before I call @offer.update?  Do I need to check the parameters hash somehow?  How do I see what query cancancan is attempting to run?

Thanks!

**Comment by coorasse** [comment]
Please use StackOverflow for questions. Thanks! :)
