### ISSUE TITLE
Should I use 1.13.1 or 2.0?

### ISSUE THREAD

**Issue by hundsim** [CanCanCommunity/cancancan#268]
I wonder what version is recommended to install (october 2015): 1.13.1 or 2.0?

When I read the documentation, it's referencing to 1.6, 1.5, 14 etc.

Aswell I wonder if it's the docs at cancan or cancancan I should follow?

**Comment by Senjai** [comment]
1.13.1, cancan (which had many of the docs ported) was on version 1.6 before the project was abandoned. 2.0 was a prerelease that never was released.

**Comment by hundsim** [comment]
Thanks a lot for the clarification. Now everything makes more sense! :)
