### ISSUE TITLE
can? ignores conditions when the subject is a class

### ISSUE THREAD

**Issue by rsutphin** [CanCanCommunity/cancancan#277]
Say I have a model `Hat`. With a rule like this:

`can :see, Hat, color: "red"`

The following is true but it seems to me like it should be false:

`can?(:see, Hat) # => true`

I.e., the rule says that I can see only red hats, but the `can?` check allows me to see any. I've checked and this is not a recent regression: all versions of `cancancan` behave like this, as well as all the versions of `cancan` I could easily test (back to 1.3).

Similarly, while `can?(:see, Hat.new(color: "blue"))` returns false, `can?(:see, Hat, color: "blue")` unexpectedly returns true.

I've posted a [gist](https://gist.github.com/rsutphin/d4bf91bef5f24b7bc3d9) to demonstrate more precisely what I mean.

I'm happy to try to fix this if desired. Since it's a long-standing behavior, I wanted to make sure first that it's considered a bug.

**Comment by Senjai** [comment]
This is desired behavior. can? expects an instance of the class. There is no way we can make an assertion about the color (being an instance value) without an instance of hat. That wouldn't make sense. So this reads as `can :see, Hat` when not using an instance.

Try:

```ruby
can :see, Hat, color: "red"
cannot :see, Hat
```

Which I've long looked for a better interface for, but have come up dry.

**Comment by rsutphin** [comment]
Thanks for clarifying that it's behaving as intended. 

> There is no way we can make an assertion about the color (being an instance value) without an instance of hat

`can :see, Hat, color: "red"` means something like "this user can see red hats". `can?(:see, Hat)` is ambiguous. Cancan interprets it as "can this user see some hat?" But it could equally well mean "can this user see every hat?", which is how I understood it. I think I interpreted it that way because the corresponding declaration — `can :see, Hat` — means "this user can see every hat". Also, I think I expect security-oriented libraries to resolve ambiguity in the most restrictive way possible.

Anyway, if people are relying on the existing behavior it's much too late to change it. Thanks for the workaround suggestion. Instead of requiring that for every rule, I think I'll override `can?` in my abilities to disallow class subjects when the corresponding rule has conditions.

**Comment by rsutphin** [comment]
And now I see this is [in the documentation](https://github.com/CanCanCommunity/cancancan/wiki/Checking-Abilities), even. Sorry I missed it earlier.
