### ISSUE TITLE
Table aliases not are used in WHERE clause

### ISSUE THREAD

**Issue by kxmbrian** [CanCanCommunity/cancancan#284]
I am working on a gamified learning platform where students in courses can earn experience points and am trying to allow admins of a particular course to view `ExperiencePointsRecord`s of students from that same course, but ran into Coursemology/coursemology2#706.

When a table has to be joined twice, the second instance of the table in aliased is the `FROM` clause, but the conditions in the `WHERE` clause does not use the alias. 

Models

``` ruby
def Course
    has_many :course_users
end

def User
    has_many :course_users
end

def CourseUser
    belongs_to :user
    belongs_to :course
end

def ExperiencePointsRecord
    belongs_to :course_user
end
```

Ability definition

``` ruby
read_hash = { course_user: { course: { course_users: { user_id: user.id, role: 'admin' } } } }
can :read, ExperiencePointsRecord, read_hash
```

Calling `accessible_by` generates a query like:

``` sql
...
FROM
    "experience_points_records" 
        LEFT OUTER JOIN "course_users"
            ON "course_users" . "id" = "experience_points_records" . "course_user_id" 
        LEFT OUTER JOIN "courses"
            ON "courses" . "id" = "course_users" . "course_id"
                AND "courses" . "instance_id" = $1 
        LEFT OUTER JOIN "course_users" "course_users_courses"
            ON "course_users_courses" . "course_id" = "courses" . "id"
WHERE
    "experience_points_records" . "course_user_id" = $2
    AND (
        "course_users" . "user_id" = $3
        AND "course_users" . "role" = $4
    )  [["instance_id", 1], ["course_user_id", 4], ["user_id", 9], ["role", "admin"]]
```

which is incorrect.  `course_users` should be generated as `course_users_courses` in the WHERE clause:

``` sql
WHERE
    "experience_points_records" . "course_user_id" = $2
    AND (
        "course_users_courses" . "user_id" = $3
        AND "course_users_courses" . "role" = $4
    )  [["instance_id", 1], ["course_user_id", 4], ["user_id", 9], ["role", "admin"]]
```

Is this a bug?

**Comment by inclooder** [comment]
Hi, I'm currently working on this one.

**Comment by inclooder** [comment]
I wrote a failing test for this issue here https://github.com/netguru/cancancan/commit/038d7640af6ce68c4b9e678b72eb020eceda2b3d
I found out that this is not a bug and the problem is actually in ability definition.
Condition is defined like this 
```ruby 
{ course_user: { course: { course_users: { user_id: user.id, role: 'admin' } } } }
```
but should defined be like that instead
```ruby
{ course_user: { course: { course_users: { user_id: user.id, user: { role: 'admin' } } } } }
```

**Comment by coorasse** [comment]
Thanks for the update
