### ISSUE TITLE
using can? in controller test works in some cases by not in others

### ISSUE THREAD

**Issue by jstoebel** [CanCanCommunity/cancancan#287]
In my app I frequently need to filter records authorized to the current_user. I achieve this by doing `.select {|r| can? :read, r }`.  This works find in my controllers

 In my controller tests (using MiniTest) however the code `MyModel.all.select {|r| can? :read, r }` throws an error. For example:

```
  1) Error:
ClinicalAssignmentsControllerTest#test_should_get_index:
NoMethodError: undefined method `can?' for #<ClinicalAssignmentsControllerTest:0x007f2687885540>
    test/controllers/clinical_assignments_controller_test.rb:15:in `block (3 levels) in <class:ClinicalAssignmentsControllerTest>'
    test/controllers/clinical_assignments_controller_test.rb:15:in `block (2 levels) in <class:ClinicalAssignmentsControllerTest>'
    test/controllers/clinical_assignments_controller_test.rb:6:in `each'
    test/controllers/clinical_assignments_controller_test.rb:6:in `block in <class:ClinicalAssignmentsControllerTest>'
```

However the following code works fine `MyModel.where(<some condition>).select {|r| can? :read, r }`

Any idea why? If this isn't actually a bug, sorry in advance and please enlighten me as to what I am missing.

**Comment by christoshrousis** [comment]
Did you try the controller method load_and_authorize_resource?

https://github.com/CanCanCommunity/cancancan/wiki/Authorizing-controller-actions

According to the above you could also write the following `load_and_authorize_resource :only => [:index, :show]`. If you only want to do it on some actions and will take into account individual loading of records based on ability,

**Comment by jstoebel** [comment]
Yes that will work as well.
