### ISSUE TITLE
Deep nested controllers

### ISSUE THREAD

**Issue by musixite** [CanCanCommunity/cancancan#288]
Hi there,

I've been scratching my head the last few days with the following issue.

My routes:
```
namespace :backend do
  resources :dashboard
  scope 'contacts', :module => 'contacts' do
    resources :users
  end
end
```

My controllers have the following hierarchy:
controllers/backend/dashboard_controller.rb
controllers/backend/contacts/users_controller.rb

All my models are on the top folder (i.e. models/user.rb)

My ability class :
```
class Ability
  include CanCan::Ability

  def initialize(user)

    user ||= User.new # in case of guest

    if user.has_role? :sysadmin
      can :manage, :all
    end

    if user.has_role? :admin
      can :manage, Backend::DashboardController
    end

  end
end
```

Controller backend/dashboard_controller.rb
```
module Backend
  class DashboardController < BackendController
    load_and_authorize_resource :class => DashboardController
    ...
  end
end
```

The authorization for the dashboard controller works fine.

However I can't make the authorization work for the nested controllers (ex. backend/contacts/users_controller.rb). I've tried different ways but I get a mismatch class error or undefined constant.

I'm sure I'm missing something obvious but can't figure out what to do in the controller to make it work.

Any ideas to put me in the right direction?

Thanks!
- Vincent

**Comment by Senjai** [comment]
For nested controllers you'll need multiple `load_and_authorize_resource` statements. With subsequent ones loading through previously loaded resources. At this point it can get rather perplexing to use load_and_authorize_resource. Often I prefer explicit authorize! calls and load my resources using accessible_by in before filters.
