### ISSUE TITLE
Rule with polymorphic relationship fails

### ISSUE THREAD

**Issue by mrloop** [CanCanCommunity/cancancan#290]
Here's a test which fails https://github.com/mrloop/cancancan/commit/aba0a064838366739b3f1f1576f5ec2aa337a4b1. Initial error for polymorphic test was `uninitialized constant VideoEncoding::VideoEncodable`. 
Solving this with this commit, https://github.com/mrloop/cancancan/commit/79079125d07571a3a67571bf2068ed7eae6c7a1a, and now have a problem eagerly loading polymorphic relationship. `Can not eagerly load the polymorphic association :video_encodable`
Thinking I need to update https://github.com/mrloop/cancancan/blob/polymorphic/lib/cancan/model_adapters/active_record_4_adapter.rb#L15 somehow, any suggestions welcome.

**Comment by coorasse** [comment]
Closed because of starvation. 
Please feel free to reopen if this issue is still valid or interested in solving with a PR.
Thank you.
