### ISSUE TITLE
Exception Access Denied

### ISSUE THREAD

**Issue by lucasmazzetto** [CanCanCommunity/cancancan#293]
I'm having a little problem. When i create some ability and then i try to access the resource (who i'd passed to the ability), it's giving Exception Access Denied, but i don't know why.

**Comment by lucasmazzetto** [comment]
I have debugged every ability (following https://github.com/CanCanCommunity/cancancan/wiki/Debugging-Abilities), but still giving Access Denied exception and i don't know why.

**Comment by tejasbubane** [comment]
Can you give some code? Maybe your debugging session as well. This would be of great help in knowing the issue.

**Comment by Senjai** [comment]
We can't help you debug without code. Please also consider posting questions on stackoverflow with the cancan tag.
