### ISSUE TITLE
load_and_authorize_resource :through always filter for the parent despite having shallow:true

### ISSUE THREAD

**Issue by mustela** [CanCanCommunity/cancancan#295]
Using `Rails 4.2.5` and `cancancan 1.13.1` and having the following controller: 

```ruby
    class JobsController < AccountController
      load_and_authorize_resource :user
      load_and_authorize_resource :job, :through :user, shallow: true
    
      def index
        render json: @jobs
      end
    
      def show
        render json: @job
      end
    
      # Removed the rest of the actions
    
    end
```

And my `routes.rb` looks like: 

```ruby
    resources :jobs, only: [:show, :index] do
      resources :workers, except: [:new, :edit]
    end
    
    resources :users, except: [:new, :edit] do
      resources :jobs, except: [:new, :edit]
    end
```

Being logged with `user: 1` when I `GET /users/1/jobs` I get the list of jobs that the user has.

Since jobs can be seen by other users, if I try to see a job from user 1 with id 2, logged in with user 2 like `GET /jobs/2`

I'm getting: 

`<ActiveRecord::RecordNotFound: Couldn't find Job with 'id'=2 [WHERE "jobs"."deleted_at" = ? AND "jobs"."user_id" = ?]>`

Because its using the logged in user to retrieve the job which is wrong, because the job has been created for another user.

Even using `load_and_authorize_resource :user, except: :show` it still trying to filter by the logged user. 

Shouldn't the line above prevent filtering by the user if it is not  present as a parameter?

Thanks

**Comment by alexeitsb** [comment]
@mustela should not you have shallow: true on your routes?
