### ISSUE TITLE
RSpec: be_able_to doesn't handle array properly

### ISSUE THREAD

**Issue by tungel** [CanCanCommunity/cancancan#300]
I have a spec test like this:
```
require "spec_helper"
require "cancan/matchers"

describe "User" do
  describe "abilities" do
    subject(:ability){ Ability.new(user) }
    let(:user){ nil }

    context "when is a user_test" do
      let(:user){ FactoryGirl.create(:user_test) }
      it{ should_not be_able_to([:export_jobs], Job) }
      it{ should_not be_able_to(:export_jobs, Job) }
    end
  end
end
```

In `ability.rb`:
```
...
can :manage, Job
cannot [:export_jobs], Job
...
```

When I run `rspec`, the test `it{ should_not be_able_to(:export_jobs, Job) }` passed; but `it{ should_not be_able_to([:export_jobs], Job) }` failed. From a debugger terminal, I can do:
```
[2] pry(#<RSpec::>)> ability.can?(:export_jobs, Job)
=> false
[3] pry(#<RSpec::>)> ability.can?([:export_jobs], Job)
=> true
```

This is weird behavior. My guess is that, the cancan/matchers doesn't handle array properly

https://github.com/CanCanCommunity/cancancan/blob/172fbd88965fe44ca4192a2f65a547bc546a1a9e/lib/cancan/matchers.rb#L12

**Comment by Senjai** [comment]
Cancan does not support checking multiple permissions in one can? call. You get true in the second call because your asking the equivilant of: `ability.can?([], Job)`, because [] does not match a rule, it falls back to can :manage, Job. Which is why you get true.
