### ISSUE TITLE
accessible_by requires an Ability. Why?

### ISSUE THREAD

**Issue by yjukaku** [CanCanCommunity/cancancan#301]
I just ran into an issue where I was incorrectly passing in a user into the `Article.accessible_by(...)` method.  I was getting the following error:

```
undefined method `model_adapter' for #<User:0x007fa3c52ab118>
````  

I eventually figured out that I should be passing in an `Ability` to the `accessible_by` method.  Is there any reason why this is the case? Most (all?) of the other cancancan methods take in a User (or whatever) instance it seems like.

Obviously changing this to only accepting ActiveModel subclasses would be a major breaking change, but allowing passing in either an Ability instance or User (or whatever) instance OR at least adding a type check + error message would be beneficial, IMO.  I can do this in a PR if needed.

**Comment by Senjai** [comment]
Accessible by is just a scope on a model. It requires an ability because it can't possibly know what the default ability is. Some applications have multiple abilities, and you can use accessible_by outside of a controller which would mean `current_ability` is not defined.

**Comment by yjukaku** [comment]
Good points!

Still, would some better error message be OK? Maybe a simple check like `ability is_a? Ability` with an appropriate error message if not?

**Comment by Senjai** [comment]
I feel like that would be overly defensive. The interface is pretty clearly defined. I don't think it would add much value, but I'm not sure if others feel differently.

**Comment by yjukaku** [comment]
Yeah, I guess it's a fine line between being defensive and paranoid.  I personally feel like the error message is too vague to help identify the issue, which is when I would prefer to improve the error message.
 
Obviously with Ruby being duck-typed, we don't want to keep type checking everything, but I think since this is an external facing API that requires a defined class/subclass to be passed in, it wouldn't be un-rubyish.

Anyways, it's up to you! I understand both ways.
