### ISSUE TITLE
load_and_authorize_resource does not enforce authorization

### ISSUE THREAD

**Issue by ewamarciniak** [CanCanCommunity/cancancan#303]
I have multiple customers in the database and each of them can have multiple admins but I want to keep those customers separate and prevent from viewing each others information. I have added the following code to the ability model:
```
if admin_user.has_role? :admin
    can [:read, :show, :edit, :update, :new_tester, :create_tester, :delete_tester], Customer, id: admin_user.customer_id
end
```
When checking in the console, the abilities are set correctly.
Unfortunately even though I have added ```load_and_authorize_resource``` in the controller, admin users are able to view pages (such as edit) for other customers. This is not an expected behaviour- could you please tell me if this is a bug?

This is how my controller looks like:
```
class Admin::CustomersController < Admin::AdminController
  load_and_authorize_resource
  skip_authorize_resource :only => :increase_click_counter

  def edit
  ...
  end
  ...
end
```

**Comment by coorasse** [comment]
Please refer to [Stackoverflow for questions](http://stackoverflow.com/questions/ask?tags=cancancan). Thanks.

**Comment by ewamarciniak** [comment]
I have submitted this as a question on Stackoverflow but nobody was able to help me. 
[http://stackoverflow.com/questions/36355060/cancan-load-and-authorize-resource-does-not-enforce-authorization?noredirect=1#comment60330184_36355060](url)

 Surely I would think that something that functionality that is not working as expected should be classified as a bug?
