### ISSUE TITLE
Raising exceptions in custom ability method breaks can? and cannot? methods

### ISSUE THREAD

**Issue by Yanchek99** [CanCanCommunity/cancancan#305]
Following the guide found here https://github.com/CanCanCommunity/cancancan/wiki/Custom-Ability-Methods

When raising exceptions in custom ability methods it breaks the can? and cannot? functions.  Meaning when using those the exception does not get translated to false but is instead thrown.  Should the can? and cannot? functions recuse from exceptions and translate to false?  Or is there a better was to pass custom messages for custom ability methods over raising an exception?

**Comment by Senjai** [comment]
It's important to note our Wiki is publicly editable and was largely copied from the legacy cancan repo. I don't think this exhibits good practice as AccessDenied is typically thrown by the `authorize!` method in controllers. We shouldn't be throwing it within the ability.

I have removed the page you linked to as I believe it represents outdated information or poor practice. The crux of the page I believe was to indicate that you can define methods other than initialize on your ability class, which should be commonly understood.

**Comment by Yanchek99** [comment]
@Senjai, Thank you for removing the page however this brings up a second issue for me.  If raising exceptions in the ability class is not recommended, then what is the best way to pass along custom error messages?  Example:  A user can't destroy a post because (custom message): 'Sorry but you are not the author of this post.' , and also, A user can't destroy a post because (custom message): 'Sorry but this post is too old to delete, please archive instead.' 

The above may need to be a second issue but was the reason i was raising exceptions in the first place.

**Comment by Senjai** [comment]
Custom messages aren't something that are currently explicitly supported. There is an ongoing debate on how best to implement them or even if they should be a responsibility of the library. You can rescue Access Denied in your controller and handle it as you see fit, but I don't recommend it.

"Sorry but this post is too old to delete" is not an authorization problem. It's a data problem. The request shouldn't be hitting your backend in the first place, if it is I would respond with a 422 (if it's an ajax or api request) or an render an error. The interface for doing this shouldn't be active on the frontend for this scenario.
