### ISSUE TITLE
Block code in ability throws CanCan::AccessDenied

### ISSUE THREAD

**Issue by dilnavazkt** [CanCanCommunity/cancancan#309]
I have defined two abilities in the ability class for publish method.

    can :publish, Story, :user => user
    cannot :publish, Story do |story|
      story.slides.count <  3
    end

when i check the ability using 
`can? :publish, story `
everything is working fine. But when I try to execute the publish method, cancan is throwing access denied.

    Started POST "/user/stories/56fcd3da83877f0d9500005b/publish" for 127.0.0.1 at 2016-04-01 09:43:09 +0530
    Processing by User::StoriesController#publish as HTML
      Parameters: {"authenticity_token"=>"1lbc+Rlfmr8xs8y45UkIrKLTpHD1ZAIx0bQMNBfcZwpxV7V+9wa9gkvNJRYh1waG1ofvv0v0IXpjknOrzRiC9Q==", "story_id"=>"56fcd3da83877f0d9500005b"}
      User Load (0.1ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 2  ORDER BY `users`.`id` ASC LIMIT 1
    D, [2016-04-01T09:43:09.231775 #3506] DEBUG -- : MONGODB | localhost:27017 | my_app_development.find | STARTED | {:filter=>{"_id"=>BSON::ObjectId('56fcd3da83877f0d9500005b')}, :project=>nil, :skip=>nil, :limit=>nil, :flags=>[:slave_ok]}
    D, [2016-04-01T09:43:09.232664 #3506] DEBUG -- : MONGODB | localhost:27017 | my_app_development.find | SUCCEEDED | 0.000928961s
    Completed 500 Internal Server Error in 10ms (ActiveRecord: 0.1ms)

    CanCan::AccessDenied (You are not authorized to access this page.):
      cancancan (1.13.1) lib/cancan/ability.rb:219:in `authorize!'
      cancancan (1.13.1) lib/cancan/controller_additions.rb:338:in `authorize!'
      cancancan (1.13.1) lib/cancan/controller_resource.rb:41:in `authorize_resource'
      cancancan (1.13.1) lib/cancan/controller_resource.rb:10:in `block in add_before_filter'
      activesupport (4.2.3) lib/active_support/callbacks.rb:446:in `instance_exec'
      activesupport (4.2.3) lib/active_support/callbacks.rb:446:in `block in make_lambda'
      activesupport (4.2.3) lib/active_support/callbacks.rb:162:in `call'
      activesupport (4.2.3) lib/active_support/callbacks.rb:162:in `block in halting'
      activesupport (4.2.3) lib/active_support/callbacks.rb:502:in `call'
      activesupport (4.2.3) lib/active_support/callbacks.rb:502:in `block in call'
      activesupport (4.2.3) lib/active_support/callbacks.rb:502:in `each'
      activesupport (4.2.3) lib/active_support/callbacks.rb:502:in `call'
      activesupport (4.2.3) lib/active_support/callbacks.rb:88:in `run_callbacks'
      actionpack (4.2.3) lib/abstract_controller/callbacks.rb:19:in `process_action'
      actionpack (4.2.3) lib/action_controller/metal/rescue.rb:29:in `process_action'
      actionpack (4.2.3) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
      activesupport (4.2.3) lib/active_support/notifications.rb:164:in `block in instrument'
      activesupport (4.2.3) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
      activesupport (4.2.3) lib/active_support/notifications.rb:164:in `instrument'
      actionpack (4.2.3) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
      actionpack (4.2.3) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
      activerecord (4.2.3) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
      actionpack (4.2.3) lib/abstract_controller/base.rb:137:in `process'
      actionview (4.2.3) lib/action_view/rendering.rb:30:in `process'
      actionpack (4.2.3) lib/action_controller/metal.rb:196:in `dispatch'
      actionpack (4.2.3) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
      actionpack (4.2.3) lib/action_controller/metal.rb:237:in `block in action'
      actionpack (4.2.3) lib/action_dispatch/routing/route_set.rb:76:in `call'
      actionpack (4.2.3) lib/action_dispatch/routing/route_set.rb:76:in `dispatch'
      actionpack (4.2.3) lib/action_dispatch/routing/route_set.rb:45:in `serve'
      actionpack (4.2.3) lib/action_dispatch/journey/router.rb:43:in `block in serve'
      actionpack (4.2.3) lib/action_dispatch/journey/router.rb:30:in `each'
      actionpack (4.2.3) lib/action_dispatch/journey/router.rb:30:in `serve'
      actionpack (4.2.3) lib/action_dispatch/routing/route_set.rb:821:in `call'
      warden (1.2.6) lib/warden/manager.rb:35:in `block in call'
      warden (1.2.6) lib/warden/manager.rb:34:in `catch'
      warden (1.2.6) lib/warden/manager.rb:34:in `call'
      rack (1.6.4) lib/rack/etag.rb:24:in `call'
      rack (1.6.4) lib/rack/conditionalget.rb:38:in `call'
      rack (1.6.4) lib/rack/head.rb:13:in `call'
      remotipart (1.2.1) lib/remotipart/middleware.rb:27:in `call'
      actionpack (4.2.3) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
      actionpack (4.2.3) lib/action_dispatch/middleware/flash.rb:260:in `call'
      rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
      rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
      actionpack (4.2.3) lib/action_dispatch/middleware/cookies.rb:560:in `call'
      activerecord (4.2.3) lib/active_record/query_cache.rb:36:in `call'
      activerecord (4.2.3) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
      activerecord (4.2.3) lib/active_record/migration.rb:377:in `call'
      actionpack (4.2.3) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
      activesupport (4.2.3) lib/active_support/callbacks.rb:84:in `run_callbacks'
      actionpack (4.2.3) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
      actionpack (4.2.3) lib/action_dispatch/middleware/reloader.rb:73:in `call'
      actionpack (4.2.3) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
      actionpack (4.2.3) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
      web-console (2.3.0) lib/web_console/middleware.rb:28:in `block in call'
      web-console (2.3.0) lib/web_console/middleware.rb:18:in `catch'
      web-console (2.3.0) lib/web_console/middleware.rb:18:in `call'
      actionpack (4.2.3) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
      railties (4.2.3) lib/rails/rack/logger.rb:38:in `call_app'
      railties (4.2.3) lib/rails/rack/logger.rb:20:in `block in call'
      activesupport (4.2.3) lib/active_support/tagged_logging.rb:68:in `block in tagged'
      activesupport (4.2.3) lib/active_support/tagged_logging.rb:26:in `tagged'
      activesupport (4.2.3) lib/active_support/tagged_logging.rb:68:in `tagged'
      railties (4.2.3) lib/rails/rack/logger.rb:20:in `call'
      actionpack (4.2.3) lib/action_dispatch/middleware/request_id.rb:21:in `call'
      rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
      rack (1.6.4) lib/rack/runtime.rb:18:in `call'
      activesupport (4.2.3) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
      rack (1.6.4) lib/rack/lock.rb:17:in `call'
      actionpack (4.2.3) lib/action_dispatch/middleware/static.rb:116:in `call'
      rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
      railties (4.2.3) lib/rails/engine.rb:518:in `call'
      railties (4.2.3) lib/rails/application.rb:165:in `call'
      rack (1.6.4) lib/rack/content_length.rb:15:in `call'
      puma (3.2.0) lib/puma/configuration.rb:227:in `call'
      puma (3.2.0) lib/puma/server.rb:561:in `handle_request'
      puma (3.2.0) lib/puma/server.rb:406:in `process_client'
      puma (3.2.0) lib/puma/server.rb:271:in `block in run'
      puma (3.2.0) lib/puma/thread_pool.rb:111:in `call'
      puma (3.2.0) lib/puma/thread_pool.rb:111:in `block in spawn_thread'

      Rendered /home/dil/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/templates/rescues/_source.erb (3.6ms)
      Rendered /home/dil/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (1.7ms)
      Rendered /home/dil/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (1.0ms)
      Rendered /home/dil/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (20.0ms)
      Rendered /home/dil/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/web-console-2.3.0/lib/web_console/templates/_markup.html.erb (0.3ms)
      Rendered /home/dil/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/web-console-2.3.0/lib/web_console/templates/_inner_console_markup.html.erb within layouts/inlined_string (0.4ms)
      Rendered /home/dil/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/web-console-2.3.0/lib/web_console/templates/_prompt_box_markup.html.erb within layouts/inlined_string (0.3ms)
      Rendered /home/dil/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/web-console-2.3.0/lib/web_console/templates/style.css.erb within layouts/inlined_string (0.3ms)
      Rendered /home/dil/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/web-console-2.3.0/lib/web_console/templates/console.js.erb within layouts/javascript (25.0ms)
      Rendered /home/dil/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/web-console-2.3.0/lib/web_console/templates/main.js.erb within layouts/javascript (0.2ms)
      Rendered /home/dil/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/web-console-2.3.0/lib/web_console/templates/error_page.js.erb within layouts/javascript (0.3ms)
      Rendered /home/dil/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/web-console-2.3.0/lib/web_console/templates/index.html.erb (44.0ms)

I can't figure out what is triggering the error. If I try without the ability in the block code, the publish method is working. Can someone look into this?

**Comment by coorasse** [comment]
Please refer to [Stackoverflow for questions](http://stackoverflow.com/questions/ask?tags=cancancan). Thanks.
