### ISSUE TITLE
Problem when checking permission on object

### ISSUE THREAD

**Issue by rui-ribeiro** [CanCanCommunity/cancancan#318]
Hi,

I´m using [FlexiRest](https://github.com/andyjeffries/flexirest), is a gem to make flexible API calls.

I want to make a condition check like:

```ruby
 #...
 # @user is a object initiliazed by FlexiRest
 can? :update. @user
```

But that trows a TypeError

```ruby
TypeError - no implicit conversion of nil into Integer:
  cancancan (1.13.1) lib/cancan/ability.rb:379:in `possible_relevant_rules'
  cancancan (1.13.1) lib/cancan/ability.rb:367:in `relevant_rules'
  cancancan (1.13.1) lib/cancan/ability.rb:386:in `relevant_rules_for_match'
  cancancan (1.13.1) lib/cancan/ability.rb:67:in `block in can?'
  cancancan (1.13.1) lib/cancan/ability.rb:66:in `can?'
  cancancan (1.13.1) lib/cancan/controller_additions.rb:380:in `can?'
  actionpack (4.2.5.1) lib/abstract_controller/helpers.rb:67:in `can?'
```

```ruby
def possible_relevant_rules(subject)
      if subject.is_a?(Hash)
        rules
      else
        positions = @rules_index.values_at(subject, *alternative_subjects(subject))
        positions.flatten!.sort!
        positions.map { |i| @rules[i] }
      end
end
```

If I do the following it works
```ruby
can? :update, User
```

I tried with a ActiveRecord object and with works. I [open a issue at FlexiRest ](https://github.com/andyjeffries/flexirest/issues/36) if you want more information. 

Want my object need to have to pass that line of code?

**Comment by rui-ribeiro** [comment]
I found that my code works at version **1.12.0 ** of CanCanCan

**Comment by Senjai** [comment]
@user is probably not initialized in the cancan ability. But there is not enough here to debug what the problem is. I highly suspect it isn't with cancan though. Without flexirest does this still fail?
