### ISSUE TITLE
can on model with conditions gives can to model itself

### ISSUE THREAD

**Issue by moskrin** [CanCanCommunity/cancancan#321]
can :manage, Document, :user_id => user.id

can?(:manage, user.documents.first) == true
can?(:manage, random_document) == false
can?(:manage, Document) == true

This last one is the bothersome part...

**Comment by walterdavis** [comment]
The reason this happens is because it makes the `#new` and `#create` methods work. If you use `load_and_authorize_resource` on your DocumentController, then creating a new @document will automagically set `user_id: current_user.id` on that instance.

**Comment by moskrin** [comment]
Ahh, understood.  Thanks for the clarification.
