### ISSUE TITLE
Limit access to associations?

### ISSUE THREAD

**Issue by km-digitalpatrioten** [CanCanCommunity/cancancan#322]
Hi,

i have a User model which has_and_belongs_to_many association to Company.
I use an ability to filter which users the current_user can see in the list collection and an ability which filters the access to the companies. Both work fine in each controllers.

I now added a condition to the user ability to also show users from the same company. This does also work as defined - but in the list of the results when showing the companies property of the user instance there're all companies of the instance listed i.e. 'Company 1, Company 2, Company 3' when the instance has this three associations, even the current_user is only assigned to 'Company 1' and the ability for companies denies this.

I struggled around with nested associations, but as a nested controller for User <-> Company won't make sense in my opinion i tried if in only could add load_resource statements to the user controller to add a filter for the user.companies association without luck.

Is there a way to filter the association values of a current object without nested resources?

**Comment by Senjai** [comment]
Please try to solve this problem using code first. If you have an attempt, and something does not work as you expect then please come back.
