### ISSUE TITLE
#member_action? fails when the member is fetched by subdomain

### ISSUE THREAD

**Issue by darmenise** [CanCanCommunity/cancancan#323]
I am working on a multi-tenant application in which every user has its subdomain, e.g. `username.example.com`.

The ability model defines the ability for every user to manage itself and the ability for the guest user to only view approved users. (An admin must approve new users in order to publish their subdomain online, the following code is obviously simplified):

```
class Ability
  include CanCan::Ability
  
  def initialize(current_user)
    if current_user.present?
      # User Admin
      can :manage, User do |user|
        user == current_user
      end
      # Guest user
    else
      can :read, User, approved: true
    end
  end
end
```

The route to fetch the user home is:

```
constraints(Constraints::Subdomain) do
    get '', to: 'users#show', as: :user
 end
```

and in the user_controller the user is set by the `set_user` before_action:

```
class UsersController < ApplicationController
  before_action :set_user, only: [:show]
  authorize_resource

  def show
  end

  private

  def set_user
    @user = User.find_by(subdomain: request.subdomain)
   end
end
```

users#show surely is a RESTful member action but CanCan fails to recognise it, setting [member_action?](https://github.com/CanCanCommunity/cancancan/blob/fbff9a114ccb76205b164c85a9b2f7d211e95171/lib/cancan/controller_resource.rb#L140) to `nil`. This leads to a paradox for which the guest is able to access users#show (e.g. username.example.com) for unapproved users **but** in the same view a call to `can? :read, @user` returns `false`!

The workaround that @coorasse was able to find was to call authorize_resource with `singleton: true` but I still think that CanCanCan should be able to understand that a `show` action is a member action by default.

**Comment by coorasse** [comment]
To summarize @darmenise problem, the `member_action?` returns false since the user is retrieved via subdomain and none of the conditions is respected:
1. is not a new action
2. `singleton` is not set
3. there is no `id` or `id_param` param
4. is not a collection action

wouldn't make sense to say that show, edit, update are member actions?
