### ISSUE TITLE
N+1 query when repeating can? method

### ISSUE THREAD

**Issue by alejorivera** [CanCanCommunity/cancancan#328]
Whenever I repeat the same `can?` method in my views, a new request to the database is done asking for the same data.

Is this expected behavior? Is there a way in which it can be avoided? I searched the wiki and SO and couldn't find an answer.

Any help would be much appreciated!

Code sample:

``` erb
<% if can? :update, @project %>
1
<% end %>
<% if can? :update, @project %>
2
<% end %>
<% if can? :update, @project %>
3
<% end %>
```

``` ruby
can [:update], Project do |project|
    (project.is_owned_by_organization? && (project.organization_creator == user)) ||
    project.is_facilitator?(user)
end
```

**Comment by Senjai** [comment]
@alejorivera Cancan doesn't add any additional caching on top of ActiveRecord. While active record may cache certain queries, if it doesn't cancan doesn't do anything particular to help it.

PR's would be welcome to assist with making us more active record friendly but I wouldn't advise for adding any kind of cache layer to cancan itself.

Instead I recommend fragment or view caching if this is a performance problem for you.
