### ISSUE TITLE
Delete the notation  for the Rails version 2.3

### ISSUE THREAD

**Issue by Kohtaro-NISHI** [CanCanCommunity/cancancan#329]
https://github.com/CanCanCommunity/cancancan#1-define-abilities
This section describes a pattern for Rails 2.3.

> In Rails 2.3, just add a new class in app/models/ability.rb with the following contents:
>```ruby
> class Ability
>   include CanCan::Ability
>
>   def initialize(user)
>   end
> end
> ```

However , rails doesn't support the less than version 3 .

 http://guides.rubyonrails.org/maintenance_policy.html
> 4 Severe Security Issues
For severe security issues we will provide new versions as above, and also the last major release series will receive patches and new versions. The classification of the security issue is judged by the core team.

> Currently included series: 4.2.Z, 4.1.Z, 3.2.Z.

So , I suggest removing this description from the README.

**Comment by Senjai** [comment]
Sure, did you want to send a PR?
