### ISSUE TITLE
Get inaccessible ids?

### ISSUE THREAD

**Issue by Ashviniv** [CanCanCommunity/cancancan#331]
We can find all the accessible ids for the user by using `accessible_by` method. But is there a method which will return all the inaccessible ids for the same user?

I know we can get it from the database by firing one more `not` query  with `accessible_by`.
 I just want to know the other way to do the same thing.

**Comment by Senjai** [comment]
Why would you need inaccessible ids? This is potentially an unbounded list of ids and usually whenever you need to do this, a better solution is usually available. Either way just add another do the not query if you must.
