### ISSUE TITLE
Drop support for Rails < 4.2

### ISSUE THREAD

**Issue by oliverklee** [CanCanCommunity/cancancan#332]
According to http://guides.rubyonrails.org/maintenance_policy.html , Rails 3.2, 4.0 and 4.1 have reached their end of life (as Rails 5.0 has been released). So I propose to stop supporting it, allowing for faster builds on Travis, code removal and simpler code.

If this is okay, I can provide a PR for this.

**Comment by Senjai** [comment]
@oliverklee Aye, I'm well aware.

I've been looking forward to this for quite a while. A PR would be great if you wanted to tackle that.
