### ISSUE TITLE
Describing abilities for AdminUser and User models

### ISSUE THREAD

**Issue by dikey94** [CanCanCommunity/cancancan#335]
Hi!
I have two separated user models: AdminUser and User. The AdminUser model is beeing used for active_admin.

My ability.rb
```
def initialize(user)
        can :show, OutlineAssignation do |assignation|
            user.admin? || assignation.user == user
        end
    end
```

All assignations can be readed when admin is logged in OR when assignation.user is logged in. CanCanCan can't see my current admin. What can I do?

```
undefined method `admin?' for nil:NilClass
```

**Comment by Senjai** [comment]
You're passing in a nil user to your initialize and not checking to see if the user is defined.
