### ISSUE TITLE
Defining can :id => user.id on a custom controller action allows access to other users

### ISSUE THREAD

**Issue by Carpela** [CanCanCommunity/cancancan#338]
Real problem here. 

I have a custom controller action (not a default one). 
I have the following 
User has an STI equiavelent StiUser
can :custom_action, StiUser, :id => user.id

When logged in as user 1, I can access the :custom_action page for user 2. 
There are no overarching permissions. 
I've tried 
cannot :manage, StiUser
before declaring the can ability

It works fine for the default actions (:show...etc). 

But that custom action is opening a breach.

**Comment by Senjai** [comment]
Could you paste an example of code that is not working where we could reproduce this issue?

**Comment by EminenceHC** [comment]
class Ability
  include CanCan::Ability
    def initialize(user)
       user ||= User.new
       can :manage, User, id: user.id
    end
end

This should prevent the logged in user from managing another user but it does not.

**Comment by laertispappas** [comment]
@EminenceHC The above should work. Can you generate a sample app and reproduce it?

**Comment by vishal5963** [comment]
@Carpela I am also facing the same issue. Did you find the solution for the same? I have also posted my question regarding same in stackoverflow. Here is the [link](https://stackoverflow.com/questions/48474298/cancancan-gem-with-sti). Please help me out with this scenario.

**Comment by Pranayi5** [comment]
I am Facing Same Problem but could not find any solution.

**Comment by coorasse** [comment]
Did you add `authorize_resource` in the controller?
