### ISSUE TITLE
Will `check_authorization` work if authorization is done somewhere else?

### ISSUE THREAD

**Issue by gumatias** [CanCanCommunity/cancancan#339]
Hi there!

Does anyone know if `check_authorization` also takes non-controllers into account when checking whether the resource being served has been authorized or not?

Looking at the source code of ControllerAdditions, [it seems like it simply sets an instance variable in the controller itself and checks for that variable to be true](https://github.com/CanCanCommunity/cancancan/blob/develop/lib/cancan/controller_additions.rb#L260). However, some of the authorization checks happens in other places such as services, query objects, etc.

Thanks!

**Comment by Senjai** [comment]
This is controller specific. It uses the authorize! method that sets that instance variable to true before calling authorize! on the ability. You can implement this mechanism in external classes that use cancan if you wish to operate similarly
