### ISSUE TITLE
Hash of conditions has unexpected results

### ISSUE THREAD

**Issue by sscirrus** [CanCanCommunity/cancancan#345]
I want to use a hash condition to narrow WHICH companies the user can update.

    puts (can? :update, Company)         # => false
    puts (can? :update, user.company)  # => false
      
    can :update, Company, id: user.company_id

    puts (can? :update, Company)         # => true
    puts (can? :update, user.company)  # => true

Why are both items returning true? I included the hash condition because I don't want the user to be able to update any company.

**Comment by alexsanford** [comment]
This is by design. It is explained here: https://github.com/CanCanCommunity/cancancan/wiki/Checking-Abilities#checking-with-class

To check whether your user can update any company, you could use `can? :update, Company.new` instead.

**Comment by sscirrus** [comment]
@alexsanford Thank you very much - I have a follow-up on this.
