### ISSUE TITLE
How to include a message on why the action is not authorized?

### ISSUE THREAD

**Issue by thebravoman** [CanCanCommunity/cancancan#347]
I would like to add additional information to the exception thrown to the user on why she/he can not access the resource and I can not find how to do it? Is there a way?

Example:
I have a resource, a user and a subscription. The Subscription has a name

I allow access to a resource only if the user.subscription has a specific name.
```
can :access, Resource do |resource|
    user.subscription.name == "Subscription 1" || user.subscription.name == "Subscription 3"
end
```

I would like to have a message that says "You must have subscription 1 or 3". How to add this info to the exception?

**Comment by alexsanford** [comment]
@thebravoman The message is set when the authorization takes place, normally in the Controller. You can customize the message in a number of ways. See https://github.com/ryanb/cancan/wiki/exception-handling

**Comment by thebravoman** [comment]
Yes, the message can be set in the controller.

But I would like to "access" a resource only of the user has a subscription
X or Y and not subscription Z. This check is made in the Ability class
which understands the logic. But then I should implement a very similar
logic in the controller to find out what are the user subscriptions and if
they need the rules. And this would make the logic redundant and called
twice.

I have the knowledge of what is the reason for access denied directly in
the Ability class the same way I now what is the error on saving an active
record directly in the model.

How would one approach to add a message in the Ability?

**Comment by kartikluke** [comment]
This is something we've been trying to figure out as well. At the moment we have to check the combination of what role a user has, the subject and the action to set the exception message. It'd be better if we could set the message in the ability.rb where these rules are set.

**Comment by coorasse** [comment]
Unfortunately is not possible to define messages on ability.rb because rules are composed together when checked and not executed one by one. You have to define the messages on your own somewhere else. Cancancan may not be able to realize which authorization rule is not satisfied. Example:
```
can :read, Book, published: true
can :read, Book, user: user.id
```

is converted in something like:
```
select * from books where published == true and user_id = 1
```

and
```@book.published? || @book.user_id == 1```
