### ISSUE TITLE
has_block errors

### ISSUE THREAD

**Issue by LeMaX10** [CanCanCommunity/cancancan#348]
Good afternoon!

Unfortunately I do not understand what occurred library error. Oddly enough being.

Ruby Version: 2.0.0

Failed to read as follows:

> NoMethodError (undefined method `has_block?' for nil:NilClass):
>  vendor/bundle/ruby/2.0.0/gems/cancancan-1.13.1/lib/cancan/controller_resource.rb:72:in`load_collection?'
>  vendor/bundle/ruby/2.0.0/gems/cancancan-1.13.1/lib/cancan/controller_resource.rb:33:in `load_resource'
> vendor/bundle/ruby/2.0.0/gems/cancancan-1.13.1/lib/cancan/controller_resource.rb:25:in`load_and_authorize_resource'
>  vendor/bundle/ruby/2.0.0/gems/cancancan-1.13.1/lib/cancan/controller_resource.rb:10:in `block in add_before_filter'

Ability:

```
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if user.admin?
        can :manage, :all
    else
        can :read, :all
    end
  end
end
```

**Comment by sheperson** [comment]
What does you controller look like?
