### ISSUE TITLE
Cancan ability block like this is not working ?

### ISSUE THREAD

**Issue by prdpspkt** [CanCanCommunity/cancancan#349]
I'm using this block in ability.rb
`can [:edit, :update, :destroy], :all, created_by: user.id`

There is a model called Person with table column created_by with data type integer. created_by stores the id of the user which created it. I only want to give update and destroy permission to those user who created. but this gives following error
`undefined method created_byfor #<Person::ActiveRecord_Relation:0x00000004c13eb0>
Did you mean?  create
`
Can you please tell what mistake I made.
Thanks

**Comment by SofaKing18** [comment]
@prdpspkt mistake: ActiveRecord_Relation is array of records, so you need to access needed element
example:
Table.where(id:5)[0].created_by

**Comment by coorasse** [comment]
Please refer to [Stackoverflow for questions](http://stackoverflow.com/questions/ask?tags=cancancan). Thanks.
