### ISSUE TITLE
Ability with Mongoid Criteria sets attribute value incorrectly on create

### ISSUE THREAD

**Issue by alexsanford** [CanCanCommunity/cancancan#351]
I have the following model:

``` ruby
class Property
  include Mongoid::Document

  # ...

  field :hidden, type: Boolean, default: false

  # ...

end
```

And the following ability:

``` ruby
class Ability
  include CanCan::Ability

  def initialize(user)

    # ...

    can :manage, Property, :hidden.ne => true

    # ...

  end
end
```

When I create a new Property object through a `create` action with `load_and_authorize_resource` it sets `hidden` to `true`.

I think it is because of the way that `ControllerResource#assign_attributes` works. In this code:

``` ruby
92:  def assign_attributes(resource)
93:    resource.send("#{parent_name}=", parent_resource) if @options[:singleton] && parent_resource
94:    initial_attributes.each do |attr_name, value|
95:      resource.send("#{attr_name}=", value)
96:    end
97:    resource
98:  end
```

The value for `attr_name` is a `Mongoid::Criteria` object. Specifically:

`#<Mongoid::Criteria::Queryable::Key:0x007f836ebfdd50 @name=:hidden, @strategy=:__override__, @operator="$ne", @expanded=nil, @block=nil>`.

Unfortunately, calling `to_s` on the criteria gives us its `name`, which is `:hidden`. So line 95 actually sets `hidden` to `true`, which is exactly what we don't want.

Any thoughts?

**Comment by coorasse** [comment]
The cancancan gem does not support Mongoid anymore. Please refer to https://github.com/CanCanCommunity/cancancan-mongoid. Thanks.
