### ISSUE TITLE
Query with ids hash not working

### ISSUE THREAD

**Issue by francesco-loreti** [CanCanCommunity/cancancan#355]
Version: 1.15.0
I have two model: User and Role
In ability I can manage all User and I want manage Role

Not work if I write:
`can :manage, User`
`can :manage, Role, user: { id: User.ids } or { id: User.pluck(:id)  }`

Working only if I write:
`can :manage, User`
`users = User.all`
`users.each do |user|`
`can :manage, Role, user_id: user.id`
`end`

This is a simple example. For more nested Models it's very difficult with many cicles inside.
Please verify and tell me the solution

**Comment by coorasse** [comment]
Please refer to [Stackoverflow for questions](http://stackoverflow.com/questions/ask?tags=cancancan). Thanks.
