### ISSUE TITLE
How to prevent Ensure Authorize from blowing up when resource list is empty?

### ISSUE THREAD

**Issue by gumatias** [CanCanCommunity/cancancan#358]
Hi!

We've been using [Ensure Authorize](https://github.com/ryanb/cancan/wiki/Ensure-Authorization#conditionally-check-authorization) a lot and we absolutely love it!

We're wondering what's the best way to handle empty results when the resource needs to be authorized.

Example: Let's say user hits a `/friends` endpoint which returns a list of users and we `authorize!` on each friend/user. However, the user doesn't have any friends yet so `authorize!` will never get called. Hence, `AuthorizationNotPerformed` will be thrown.

Assuming the above makes sense - The only workaround we found so far is to perform a fake authorization or manually set `@_authorize = true`.

Are there any other recommendations?

Thanks!

**Comment by gmcnaughton** [comment]
We use `check_authorization` in combination with [`load_and_authorize_resource`](https://github.com/ryanb/cancan/wiki/authorizing-controller-actions), which automatically calls `authorize!` for you.

There are plenty of reasons why you might not want to use `load_and_authorize_resource` but let's look at how it handles the case you mentioned!

When you visit `/friends`, say that hits a `FriendsController#index` action.  `load_and_authorize_resource` essentially does this in a `before_action`:

    authorize! :index, Friend
    @friends = Friend.accessible_by(current_ability)

It uses `authorize!` to verify that you're allowed to index Friends at all, then it uses `accessible_by` to make sure `@friends` only has records you're allowed to see.  It always calls authorize, even though the list of friends may end up empty.

Hope that helps!
