### ISSUE TITLE
Subject array checking

### ISSUE THREAD

**Issue by bradlis7** [CanCanCommunity/cancancan#372]
I created this helper method to look at arrays of subjects. It might be helpful to add to the project.

    def can_any?(action, subjects)
        subjects.any? { |s| can? action, s }
    end

`can_all?`, `authorize_any!`, and `authorize_all!` would also be useful.

**Comment by coorasse** [comment]
can you show me a real use-case where this would be useful?

**Comment by bradlis7** [comment]
In my view, I want to show `event.attendees`, and allow the user to update it if they have rights. Admins can update all, and users can update their own, and sometimes they won't be included, so I don't want to render the form if there's not an editable field.

    <% if can_any? :update, event.attendees %>
      <%= render partial: "_edit_all", locals: { attendees: event.attendees } %>
      <%# returns a remote form with status radio buttons for the attendees they can update %>
    <% else %>
      <%= render partial: "_show_all", locals: { attendees: event.attendees } %>
    <% end %>

If my case is too rare, that's fine. I'll just keep the helper function in my ApplicationHelper.

**Comment by coorasse** [comment]
I think you should better use `event.attendees.accessible_by?(current_ability, :update).any?` which will even be more performant because will just execute one DB query. Let me know if this is the solution to your problem

**Comment by bradlis7** [comment]
That's probably a better solution in some cases, but I have some can blocks that don't allow me to check using `accessible_by`. Plus, I need to fetch all the subjects in this case for view or edit, depending on role.

**Comment by coorasse** [comment]
I think your need is too specific to be added to the library. I think the problem can be solved anyway.
Thanks for your explanation.
