### ISSUE TITLE
Small typo in Defining Abilities wiki page

### ISSUE THREAD

**Issue by jesusabarca** [CanCanCommunity/cancancan#383]
Hi, I found a small typo in the `Defining Abilities` wiki page, section [`Hash of Conditions`](https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities#hash-of-conditions). There's this line of code:
```
can :read, Project, active: true, :user_id user.id
```
but should read:
```
can :read, Project, active: true, user_id: user.id
```

I tried to fix it myself, but I didn't find a way to propose the change, if there is a way let me know ;)

**Comment by asampatoor** [comment]
That's from the Wiki page. AFAIK we cannot send a PR for a Wiki page. It should be changed by the owner.

**Comment by coorasse** [comment]
done. thanks
