### ISSUE TITLE
several issues with Ability#possible_relevant_rules with empty Ability

### ISSUE THREAD

**Issue by bertBruynooghe** [CanCanCommunity/cancancan#384]
def possible_relevant_rules(subject)
      if subject.is_a?(Hash)
        rules
      else
        positions = @rules_index.values_at(subject, *alternative_subjects(subject))
        positions.flatten!.sort!
        positions.map { |i| @rules[i] }
      end
    end

1. If the subject is not a hash, and no rules have been added, we call `values_at` on `nil`
So maybe we should do:

        positions = (@rules_index || {}).values_at(subject, *alternative_subjects(subject))

2. But than, `flatten!` returns nil since nothing has changed, so we call `sort!` on nil
So let's do this instead:

        positions =positions.flatten.sort

3. But now, `@rules[i]` fails, because the values_at created an array with all nils, so maybe we should do:

        positions = positions.compact.flatten.sort

Or we can change the first line of `relevant_rules` to:

        def relevant_rules(action, subject)
            return [] unless @rules && @rules.first

**Comment by coorasse** [comment]
what is the issue? I cannot understand, from your description, which problem you are trying to solve. Do you have a failing example?
