### ISSUE TITLE
Bug in ActiveRecord adapter not rejecting empty conditions

### ISSUE THREAD

**Issue by heaven** [CanCanCommunity/cancancan#389]
If you define the next abilities:
```ruby
cannot :manage, :all

can :read, Model, Model.published do |instance|
  instance.published?
end
```

You will get the next error:
```
CanCan::Error (Unable to merge an Active Record scope with other conditions. Instead use a hash or SQL for read Market::Job ability.)
```

Here's the source:
https://github.com/CanCanCommunity/cancancan/blob/develop/lib/cancan/model_adapters/active_record_adapter.rb#L84

The `conditions` variable will contain a proc and an empty hash. Replacing
```ruby
conditions = @rules.map(&:conditions).compact
```
with
```ruby
conditions = @rules.map(&:conditions).select(&:present?)
```
fixes the problem.

**Comment by coorasse** [comment]
PR is welcome!

**Comment by artemasmith** [comment]
Hi, if I get it right, here [PR](https://github.com/CanCanCommunity/cancancan/pull/419), that fix this bug.

**Comment by coorasse** [comment]
closing due to lack of feedback. Feel free to re-open or create a PR. Thanks
