### ISSUE TITLE
Check if current resource is protected or not

### ISSUE THREAD

**Issue by iamdriz** [CanCanCommunity/cancancan#390]
I have the following controller which I use to protect certain areas of my app:
~~~
class AdminController < ApplicationController
  load_and_authorize_resource
end
~~~
And some example controllers:
~~~
class HomeController < ApplicationController
  def index
  end
end

class PostsController < AdminController
  def index
  end
end
~~~

So `HomeController` **doesn't** protect its methods using CanCan but `PostsController` **does** because it's inheriting from `AdminController` which has the `load_and_authorize_resource`

What I want to do is check if the request resource is protected or not.

I can access the controller and action via params. I can't use the standard can? and cannot? helpers as they will check if the current_user has permission rather than if the action itself has a protection on it.

So for example:
~~~
class ApplicationController < ActionController::Base

  before_action :check_protected

  def check_protected
    if can? params[:action].to_sym, Object.const_get(params[:controller].classify)
      # resource is protected
    else
      # resource is not protected
    end
  end

end
~~~
^^ This won't work because it will always say false when no `current_user` or if the user doesn't have permission. **I need to check if the resource itself is protected with CanCan** rather than if the current_user has permission or not.

I also tried:
~~~
def check_protected
    if CanCan::ControllerResource.new(self).skip?(:authorize)
      # resource is not protected
    else
      # resource is protected
    end
end
~~~

But this only works for skipped methods and returns false for controllers that don't use CanCan e.g. the HomeController, so doesn't work as intended.

Is there a simple way to find out if the current resource has CanCan on it or not?

One hack was to add `skip_authorize_resource` to the HomeController, but it requires adding to every controller as trying to add it to a parent for all unprotected controllers doesn't work, so it's pretty nasty. Reported an issue https://github.com/CanCanCommunity/cancancan/issues/391 as I think it's another issue that `skip_authorize_resource` isn't inherited.

**Comment by iamdriz** [comment]
The only way around this I have found, is to add `skip_authorize_resource` to all the controllers I don't want authentication on.

**Comment by coorasse** [comment]
closing in favor of https://github.com/CanCanCommunity/cancancan/issues/391
