### ISSUE TITLE
skip_authorize_resource not inheritable

### ISSUE THREAD

**Issue by iamdriz** [CanCanCommunity/cancancan#391]
Any reason why `skip_authorize_resource` isn't inheritable?
For example I have an `ApplicationController` with it in and a `PagesController` that inherits from `ApplicationController` like so:
~~~
class ApplicationController < ActionController::Base
  skip_authorize_resource
end
class PagesController < ApplicationController
  def index
  end
end
~~~
The methods inside PagesController don't skip! So PagesController isn't inheriting `skip_authorize_resource`.

But doing this:
~~~
class ApplicationController < ActionController::Base
  skip_authorize_resource
end
class PagesController < ApplicationController
  skip_authorize_resource #shouldn't this have been inherited from ApplicationController?

  def index
  end
end
~~~
Does work... why isn't `skip_authorize_resource` inherited? As I'd prefer to avoid having to add that line to all my subcontrollers if possible.

The reason for doing it is because of this issue: https://github.com/CanCanCommunity/cancancan/issues/390

**Comment by BKSpurgeon** [comment]
@iamdriz  hello  - i could not discern the different between the two code examples. would you pls elaborate?

**Comment by iamdriz** [comment]
@BKSpurgeon Sorry forgot to add the correct code. Basically as you can see I've had to add the `skip_authorize_resource` to both controllers. But expected `PagesController` to have inherited it from `ApplicationController` but it doesn't.

**Comment by BKSpurgeon** [comment]
I'll try and look into it. i can't guarantee success tho. pls bear with me.

**Comment by iamdriz** [comment]
@BKSpurgeon `skip_authorize_resource` basically just needs to be inheritable same as the `load_and_authorize_resource` methods.

**Comment by BKSpurgeon** [comment]
@iamdriz bro gimme till the weekend i have not forgotton. then i'll tell you whether i could or couldn't do it

Ben

**Comment by iamdriz** [comment]
@BKSpurgeon You have any luck with it?

**Comment by BKSpurgeon** [comment]
@iamdriz bro don't wait by the phone.........i've simply been inundated......i can't promise to find the solution  -- i've yet to seriously look at the gem -- by Monday you'll know for sure whether i can solve it or not. i hope i can. btw can github  do PMs?

**Comment by enneid** [comment]
workaround: 
```
class ApplicationController < ActionController::Base
 def inherited(subclass)
      subclass.load_and_authorize_resource instance_name: "resource"
      subclass.skip_authorize_resource only: :update_status
    end
end
```

**Comment by coorasse** [comment]
is this issue solved in cancancan 2.0?

**Comment by BKSpurgeon** [comment]
to fix would probably need a significant work around of existing code base.

**Comment by iamdriz** [comment]
@coorasse I've only tested this on CanCanCan 2.0 so I'd say not.

**Comment by kraflab** [comment]
Looks like this was already solved here: https://github.com/CanCanCommunity/cancancan/commit/1f786270b5b2a64669a2dfa2ddb4ed981cd36d99 ?

**Comment by coorasse** [comment]
should be fixed, agree.
