### ISSUE TITLE
strange unauthorized errors.

### ISSUE THREAD

**Issue by djmaximaldonado** [CanCanCommunity/cancancan#404]
Hi, 
I am having a strange error, and I have no idea how to fix it. If I modify the code of a controller or model, when I refresh the browser, cancancan throws "unauthorized" and send me to the home page. It always occurs with all my controllers-models.  

It happens with the "superadmin" role, and in the ability.rb the superadmin can :manage, :all , so I dont understand why give me unauthorized. The behavior which I saw, is that the first time that the page is reloaded after a change, the user loses all permissions. If I reload the page again, the users recovers his permissions. 

Any ideas about what is happening ?
Thks!

**Comment by coorasse** [comment]
Please refer to [Stackoverflow for questions](http://stackoverflow.com/questions/ask?tags=cancancan). Thanks.

**Comment by djmaximaldonado** [comment]
:(

**Comment by andynu** [comment]
For posterity. Here was his SO question. Turned out to be a typo. 

https://stackoverflow.com/questions/43376157/strage-authorization-error-with-cancan
