### ISSUE TITLE
cancancan breaks spring + rspec on rails 3.2.x

### ISSUE THREAD

**Issue by vovimayhem** [CanCanCommunity/cancancan#405]
I'm having a problem running "springified" rspec on a rails 3.2.22.5 app, and through a process of elimination I isolated the problem to the cancancan gem.

This is the error I'm getting when running rspec with the app already preloaded with spring:
```
Failure/Error: DatabaseCleaner.clean_with(:truncation)

ActiveRecord::StatementInvalid:
  PG::ConnectionBad: PQsocket() can't get socket descriptor:           SELECT tablename
            FROM pg_tables
            WHERE schemaname = ANY (current_schemas(false))
```

I've setup a sample app running with docker compose to run the test in a reproduceable way:

https://github.com/IcaliaLabs/cancancan-test (Follow instructions on readme)

**Comment by vovimayhem** [comment]
I'm suspecting attempting a connection on code load is to blame.

**Comment by vovimayhem** [comment]
I found the problem to be how the module `CanCan::ModelAdditions` is loaded into `ActiveRecord::Base` on [`lib/cancan/model_adapters/active_record_adapter.rb:147`](https://github.com/CanCanCommunity/cancancan/blob/734c70cb824c58e1efb1473401186abeab023c54/lib/cancan/model_adapters/active_record_adapter.rb#L147)

I remember this is better off done in a railtie - somehow.

I've also seen a related issue with exactly this same code location: #342

**Comment by vovimayhem** [comment]
Dudes, your'e dropping support for Rails 3.x?

**Comment by vovimayhem** [comment]
OK I saw it on #292 - Dropping support for 3.2.x for good.

Sad (for me) - Let me know if your'e up for just one more release on 1.x

Forking out & continuing on my own.

**Comment by coorasse** [comment]
Up for a new 1.x release. PR is welcome!

**Comment by vovimayhem** [comment]
There it is. I just cherry-pick'd @kuldeepaggarwal commit. Credit to whom credit is due :)
