### ISSUE TITLE
empty string in Rails 5 parameters will cause load_resource to raise error

### ISSUE THREAD

**Issue by darwin67** [CanCanCommunity/cancancan#408]
I'm seeing `load_resource` raising errors when the value for the specified key is `nil` on the request.

### Example
Controller
```ruby
class UserController < ApplicationController
  load_resource :user, only: [:create, :destroy]

  def create; end
  def destroy; end
end
```
Request
```
POST :create, params: { user_id: nil }
```

In Rails 5, param values passed to the controller would all be interpreted as strings. Therefore, if `user_id` in the request above will look like `{ user_id: '' }` inside the controller. This will cause `load_resource` to raise an error because CanCan will try to do a `User.find('_id')`

https://github.com/CanCanCommunity/cancancan/blob/v1.15.0/lib/cancan/controller_resource.rb#L136-L146

**Comment by coorasse** [comment]
closed in version 2.0. Thanks
