### ISSUE TITLE
I18n::ArgumentError with i18n v0.8.2+

### ISSUE THREAD

**Issue by cbeer** [CanCanCommunity/cancancan#415]
### Steps to reproduce

https://gist.github.com/cbeer/140cb717506e97181644c59faaef92b2

Using i18n v0.8.2+, calling `unauthorized_message` causes an exception.

Upstream, they introduced a new check in 0.8.2: https://github.com/svenfuchs/i18n/pull/236.

Cancancan is explicitly passing a `nil` key: https://github.com/CanCanCommunity/cancancan/blob/2d21842d4415913cb9d15d71bfa3165087be29c4/lib/cancan/ability.rb#L225.

### Expected behavior

The unauthorized message should be provided.

### Actual behavior

An exception is thrown:

```
I18n::ArgumentError: I18n::ArgumentError
    /Users/cabeer/.gem/ruby/2.4.1/gems/i18n-0.8.3/lib/i18n.rb:152:in `translate'
    /Users/cabeer/.gem/ruby/2.4.1/gems/cancancan-2.0.0/lib/cancan/ability.rb:226:in `unauthorized_message'
```

### System configuration
**Rails version**: 5.0.2

**Ruby version**: 2.3.4

**CanCanCan version** 1.17.0

**Comment by radar** [comment]
I have just released I18n 0.8.4 which should fix this issue. Please try it out :)

**Comment by clemens** [comment]
This might be just my opinion but I think it's more CanCanCan's fault than i18n's: A call to `I18n.translate` with `nil` doesn't semantically make sense. It literally says "Give the translation of nothingness". I think what CanCanCan means to do here is use a fallback chain, but it takes a shortcut by piggybacking on the `default` option. What it should instead do is build up an array of potential keys and then shift off the first element as the starting key – similar to what simple_form does here: https://github.com/plataformatec/simple_form/blob/master/lib/simple_form/inputs/base.rb#L173-L189. Then i18n could be fixed accordingly as well.

**Comment by coorasse** [comment]
I agree with @clemens , PR is welcome!

**Comment by coorasse** [comment]
is the problem with i18n solved now @cbeer ?

**Comment by clemens** [comment]
I guess it is solved by the i18n update but (IMO) it's not fixed in the right way ...
