### ISSUE TITLE
Missing from cause SQL exception when plucking columns

### ISSUE THREAD

**Issue by derekrockwell** [CanCanCommunity/cancancan#42]
After switching from CanCan, I noticed (Rails 3.2.17) that my queries of the below were failing:

```ruby
SomeModel.where(admin_id: Admin.accessible_by(current_ability, :read))
```

Would throw an exception of the form:

>
ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  missing FROM-clause entry for table "customers"
LINE 1: ..." ON "roles"."id" = "users_roles"."role_id" WHERE "customers...
                                                             ^
: SELECT "users"."id" FROM "users" INNER JOIN "users_roles" ON "users_roles"."user_id" = "users"."id" INNER JOIN "roles" ON "roles"."id" = "users_roles"."role_id" WHERE "customers"."id" IN (1) AND (((roles.name = 'admin') AND (roles.resource_type IS NULL) AND (roles.resource_id IS NULL)))

```Admin``` is using Rolify to generate the admin role in the query above and the query is scoped by the current customer_id as defined by the ability:

```ruby
can [:read, :update], Admin, customers: {id: user.customer_ids}
```

The query itself actually succeeds however and returns records, and as a workaround I have been able to do:

```ruby
SomeModel.where(admin_id: Admin.accessible_by(current_ability, :read).map(&:id))
```

But it obviously has performance implications opposed to using raw SQL. 

Reverting to CanCan 1.6.10 seems to work as well.

**Comment by Senjai** [comment]
That "Workaround" should be the proper solution. I wouldn't call it a workaround in this case.
