### ISSUE TITLE
`find_by` accepting a `Proc/Lambda`?

### ISSUE THREAD

**Issue by RonaldKlaus** [CanCanCommunity/cancancan#422]
Hello!

I have models:
```
class Rating < ActiveRecord::Base
  belongs_to: :user
  belongs_to: :movie
end

class Movie < ActiveRecord::Base
  has_many :ratings
end
```

It would be nice to load the `@rating` like

```
class RatingsController
  load_resource :movie
  load_and_authorize_resource through: :movie, find_by: -> { {user_id: current_user.id} }, singleton: true

  def show; end
end
```
And `find_by: -> {...}` should work in the `controller` scope where I can use methods like `current_user`.

What do you think?

**Comment by coorasse** [comment]
Hello Ronald,
is this solving your issue? (https://github.com/CanCanCommunity/cancancan/wiki/Authorizing-controller-actions#override-loading)

**Comment by coorasse** [comment]
I think this also should fit your needs: https://github.com/CanCanCommunity/cancancan/wiki/Authorizing-controller-actions#custom-find. Feel free to reopen if I misunderstood your needs.

**Comment by RonaldKlaus** [comment]
Hej people! Thanks for your answers :)

Overloading would do the job. Your were right. But I thought it would be more flexible to expand the `find_by` option to use not only a parameter but a `hash`, like `ActiveRecord` does. So it would generate a query like `Movie.ratings.find_by(user_id: current_user.id)`.

**Comment by coorasse** [comment]
I better see your point now. I'd be glad to accept a PR which implements it!
