### ISSUE TITLE
can :read  NOT equals can [:index,:show] !

### ISSUE THREAD

**Issue by qx** [CanCanCommunity/cancancan#425]
It's easy to reproduct.  I want to know what's "read" stands for???? is there any doc?

**Comment by coorasse** [comment]
You can check the wiki: https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities

Please refer to [Stackoverflow for questions](http://stackoverflow.com/questions/ask?tags=cancancan). Thanks.
