### ISSUE TITLE
rails g cancan:ability throws 'Could not find generator cancan:ability'

### ISSUE THREAD

**Issue by rsteveyoung** [CanCanCommunity/cancancan#428]
I've installed and run properly a rails app with devise, after config cancancan in Gemfile and run bundle install everything goes well. But when try to: $ rails g cancan:ability the application throws the next error:

```
Shell >> $ rails g cancan:ability
Running via Spring preloader in process 10554
Expected boolean default value for '--markerb'; got :erb (string)
Could not find generator 'cancan:ability'. Maybe you meant 'channel', 'scss:assets' or 'css:assets'
```

### Expected behavior
Might create the ability model class:  app/models/ability.rb

### System configuration
**Rails version**: 5.0.6

**Ruby version**: 2.3.3 

**CanCanCan version**: 1.16.0 (also tried with: 2.0.0)

**Comment by BenAkroyd** [comment]
This doesn't resolve the issue, but rails g cancan:ability just copies the below file into your models folder. If this is holding you up just create the file and copy and paste.
https://github.com/CanCanCommunity/cancancan/blob/develop/lib/generators/cancan/ability/templates/ability.rb

**Comment by coorasse** [comment]
I cannot reproduce the issue. Can you provide a simple example to reproduce it? Maybe a github repo with a project where this happens would be nice. I cannot really say what is the issue...

**Comment by rsteveyoung** [comment]
@coorasse, I finally solve it using @BenAkroyd 's workaround, thanks !!

**Comment by Dorian** [comment]
I reproduced it, on a fresh rails 5.2 app, reloading spring fixed it, e.g. `spring stop`

**Comment by vovka** [comment]
Run `spring stop`

**Comment by OfficeYAportatil** [comment]
Hi Alessandro!

I just got the same issue.

This is my Gemfile:

`source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.2'

gem 'any_login'
gem 'bcrypt', '~ > 3.1.16'
gem 'bootsnap', '>= 1.4.4', require: false
gem 'coffee-script'
gem 'devise'
gem 'devise-async'
gem 'disposable_mail', '~ > 0.1'
gem 'effective_obfuscation'
gem 'email_verifier'
gem 'haml'
gem 'jbuilder', '~ > 2.7'
gem 'puma', '~ > 5.0'
gem 'pwned'
gem 'rails', '~ > 6.1.3'
gem 'sass-rails', '>= 6'
gem 'sqlite3', '~ > 1.4'
gem 'strong_password', '~ > 0.0.6'
gem 'turbolinks', '~ > 5'
gem 'webpacker', '~ > 5.0'

group :development, :test do
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'guard'
  gem 'guard-minitest'
end

group :development do
  gem 'brakeman'
  gem 'consistency_fail'
  gem 'flog'
  gem 'fly'
  gem 'guard-annotate'
  gem 'guard-brakeman'
  gem 'guard-bundler', require: false
  gem 'guard-coffeelint' # coffeelint --makeconfig > coffeelint.json
  gem 'guard-consistency_fail' # falla el init
  gem 'guard-haml_lint'
  gem 'guard-livereload', '~ > 2.5', require: false
  gem 'guard-migrate'
  gem 'guard-puma'
  gem 'guard-railsbp'
  gem 'guard-reek'
  gem 'guard-rubocop'
  gem 'guard-rubycritic' 
  gem 'guard-shell'
  gem 'listen', '~ > 3.3'
  gem 'rack-mini-profiler', '~ > 2.0'
  gem 'rails_best_practices'
  gem 'reek', require: false
  gem 'rubocop', require: false
  gem 'rubocop-i18n'
  gem 'rubocop-minitest', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-rails', require: false
  gem 'rubycritic', require: false
  gem 'spring'
  gem 'web-console', '>= 4.1.0'
end

group :test do
  gem 'capybara', '>= 3.26'
  gem 'selenium-webdriver'
  gem 'simplecov', require: false
  gem 'webdrivers'
end
`

What I have done so far is: 

1) add cancancan to my Gemfile
2) run bundle install
3) rails g cancan:ability
and then I get the error.

**Comment by OfficeYAportatil** [comment]
Sorry, about the last post. I was on my 5 minutes of **ridiculum lapsus** . I just discover the errors:
1) when switching git branches, I run the command `rails g cancan:ability` in a branch where `gem "cancancan"` was not included in the Gemfile
2) the gem "effective_obfuscation" caused that method aliasing did not work.
