### ISSUE TITLE
CanCanCan, JWT, RSpec failure

### ISSUE THREAD

**Issue by danejorgensen** [CanCanCommunity/cancancan#429]
### Steps to reproduce

I have a rails engine that serves an API.  The API uses a JWT to authenticate the user in the ApplicationController.

ApplicationController has a before_action :authenticate_request! method that will set the current_user.  The child/resource controller has the load_and_authorize_resource.

https://gist.github.com/danejorgensen/890bc6daddfcf8f9ff66b44b4d7ed637

### Expected behavior
When I run `rspec` (3.5.0), an unauthenticated request should return a 401.

### Actual behavior
When I run `rspec`, a 500 error (NoMethodError) is returned since the current_user is nil in Ability.rb

The interesting part of this is if you run the test directly like `rspec spec/requests/alert_responses_spec.rb` the tests will pass.  If you run the full test suite, all of the tests will fail with a 500.

The behavior is the same if you run the test suite with a random seed.  The tests do not rely on anything external and the order does not matter.

I have tried the tests as controller and request tests with no difference in behavior.

What appears to happen, is if you run the test directly, it calls the before_action and then the load_and_authorize_resource (in that order) and it works.  If you run the full test suite, it calls load_and_authorize_resource first, and then fails with a 500 since there isn't a current_user yet from the before_action.

Calling the API directly from curl or a javascript frontend works correctly.

I'm wondering if anyone has any feedback or tips for testing CanCanCan with JWT authentication.

### System configuration
**Rails version**: 4.2.5

**Ruby version**: 2.3.4

**CanCanCan version**: 2.0.0

**RSpec version**: 3.5.0

**Comment by coorasse** [comment]
Please refer to [Stackoverflow for questions](http://stackoverflow.com/questions/ask?tags=cancancan). Thanks.
