### ISSUE TITLE
WIKI error Page 'Role Based Authorization'

### ISSUE THREAD

**Issue by Malstrom** [CanCanCommunity/cancancan#432]
In your wiki you purpose to do this:
`rails generate migration add_role_to_users role:string`
But the column type needs to be an integer for work not string then:
`rails generate migration add_role_to_users role:integer`

**Comment by Schwad** [comment]
Howdy @malstrom thanks for bringing this up. It's a large wiki, could you copy in the link to the specific page you're referring to?

**Comment by Malstrom** [comment]
Sorry, here https://github.com/CanCanCommunity/cancancan/wiki/Role-Based-Authorization

**Comment by coorasse** [comment]
Why does it have to be an integer?

**Comment by Malstrom** [comment]
I wrote it in first my post, role must be integer

**Comment by coorasse** [comment]
As per my comment above: why cannot it be a string? Thanks for clarifying.

**Comment by coorasse** [comment]
I close for stale. Feel free to reopen.
