### ISSUE TITLE
Document Nested Resources : through_association option in the wiki

### ISSUE THREAD

**Issue by rafasoares** [CanCanCommunity/cancancan#434]
Using CanCanCan 2.0.0 (not sure about other versions), when I use an association with a name that doesn't match the resource name (using AR's option `:class_name`), CanCanCan gives me an `undefined method` error, which is understandable.

Looking in [the source code](https://github.com/CanCanCommunity/cancancan/blob/develop/lib/cancan/controller_resource.rb#L201), I found out about the undocumented `:through_association` option, which solves the problem. I wonder why it's not in the [Wiki](https://github.com/CanCanCommunity/cancancan/wiki/Nested-Resources)...

Anyway, if you could update the Wiki, it would be great for anyone else who encounters this issue.

I have "forked" the Wiki and made a note in the Nested Resources page, in case you want you update your Wiki with it: https://github.com/rafasoares/cancancan-wiki/commit/213eaa309fc641241fbab6529d93d022ef4f2606

Thanks for your time and your awesome work.

I hope I have helped.

**Comment by coorasse** [comment]
Nice addition. Thank you @rafasoares
