### ISSUE TITLE
Using #load_resource with "inherited_resources" gem and "has_scope" gem doesn't #apply_scopes automatically since CanCanCan version 2.0

### ISSUE THREAD

**Issue by Looooong** [CanCanCommunity/cancancan#435]
### Steps to reproduce

```rails
class BooksController < ApplicationController
  inherit_resources
  load_resource
  has_scope :order, default: 'id'

  def index
    current_scopes # Scopes applied by 'has_scope'
    [...]
  end
end
```

### Expected behavior
**Before action**, `#apply_scopes` should be called automatically on collection/resource instance.
Then calling `#current_scopes` should returns a hash to show what scopes and values have been applied (in this case is `{ "order" => "id" }`).

### Actual behavior
CanCanCan 1.17: Works as expected.
CanCanCan 2.0: `#apply_scopes` is not called automatically, and `#current_scopes` returns empty Hash.

### System configuration
**Rails version**: 4.2.8

**Ruby version**: 2.3.3

**CanCanCan version**: 2.0

**inherited_resources version**: 1.7.2

**has_scope version**: 0.7.1

**Comment by coorasse** [comment]
InheritedResource is not supported anymore.
