### ISSUE TITLE
NotFound during load_and_authorize should raise AccessDenied

### ISSUE THREAD

**Issue by jeremywadsack** [CanCanCommunity/cancancan#437]
### Steps to reproduce

In a Rails application, if a record is not found during `load_and_authorize_resource` it raises `ActiveRecord::NotFound` before it checks _authentication_ in the `authorize` step.

This means that secured routes can have their resources discovered without even being signed in:

```
$ curl -I https://app.example.com/restricted_resource/does-not-exist
HTTP/1.1 404 Not Found

$ curl -I https://app.example.com/restricted_resource/does-exist
HTTP/1.1 302 Found
Location: https://app.example.com/sessions/new
``` 

In the example above, I use slugs for identifying resources, which is commonly done to hide database ID's. This could expose details about which slugs exist and which don't. Even with database ID's this could expose details about which records exist (although that is probably a lower risk).

### Expected behavior
Changing `cancancan`'s behavior to raise `AccessDenied` during the `load` phase would provide consistent behavior which could be handled by the application. 

I think it probably only makes sense to always do this when `load_resource` is called from the `load_and_authorize` context. Do developers use `cancancan`'s `load_resource` method for non-secured controllers?

### Actual behavior
`load_and_authorize_resource` directly calls `load_resource` which raises `ActiveRecord::NotFound` when `#find` or `#find_by` fails to match a record.

### System configuration
**Rails version**: 4.2.8
**Ruby version**: 2.3.1
**CanCanCan version** 1.10.1

### Comments

I'm happy to submit a pull request for this but I wanted to get feedback on this and make sure I understand this correctly.

I recognize that even with changed status codes there might still be timing attacks that could detect this information (no record and an exception takes less time than populating a ruby object from a database record), but those would be harder to build, I think.

I've noticed it's fairly common for sites to return a 404 status code (and template) for "unauthorized". This doesn't feel right and it's confusing to customers to see a 404 page that says "by the way you might need to sign in to get that". It seems better to err on the side of "you don't have permission to access that" even if it's not a valid resource.

**Comment by coorasse** [comment]
CanCanCan, as Rails, raises a 404 to not disclose the existence of a resource. Either I don't understand the issue or IMHO the behaviour is intended.

**Comment by jeremywadsack** [comment]
@coorasse Raising a 404 when a protected resource is requested but not allowed is one solution, that's not my experience with how it works. 

See the `curl` examples in my original post — it returns a 302 redirect due to "access denied". 

The README [suggests sending a `:forbidden` for `AccessDenied`](https://github.com/CanCanCommunity/cancancan/blob/e594ee66df4dee36cf2cb0b67c8be88ee7b3ecbb/README.md#4-handle-unauthorized-access). The [wiki page on exception handling](https://github.com/CanCanCommunity/cancancan/wiki/exception-handling) discusses handling `AccessDenied` with a redirect or 403, not a 404.

I tested _not_ handling `CanCan::AccessDenied` in the `application_controller` and it allows `CanCan::AccessDenied` to be raised and returns a 500 status code and server error page, not a 404 response.

To restate the issue, when a protected resource is requested there can be three possible responses:

1. It exists, you have access, here it is (status 200)
2. It does not exist (currently status 404)
3. It exists, but you do not have access (currently raises `CanCan::AccessDenied`)

The problem is that 2 and 3, in a brute-force attack, could expose details about what information does and does not exist in with in a restricted resource. Ideally those two instances return the same response.

**Comment by coorasse** [comment]
I would suggest to update the README and Wiki in order to point out this issue and suggest returning 404. What do you think?

**Comment by coorasse** [comment]
The Documentation has been updated with a relevant section regarding your point: https://github.com/CanCanCommunity/cancancan/wiki/Exception-Handling#danger-of-exposing-sensible-information

**Comment by jeremywadsack** [comment]
@coorasse Thank you for adding that change. I'm sorry I hadn't had time to get to it.

**Comment by pelcasandra** [comment]
I agree on returning 404 for protected resources. 

If any user tries to access protected resources from other users it makes sense to return 404 for those. 

However, the problem i'm seeing with `CanCan::AccessDenied` always returning 404 is that it implies also returning 404 for authentication errors.

This can lead to some confusion to users as they would not have correct feedback when his credentials are wrong. 

A solution could be to return 401 unless is authenticated and 404 if is authenticated and the resource does not belong to him.

```ruby
  rescue_from CanCan::AccessDenied do |exception| 
    if user_signed_in?
       render nothing: true, status: :not_found       # 404
    else
       render nothing: true, status: :unauthorized    # 401
    end
  end
```

**Comment by jeremywadsack** [comment]
@pelcasandra I would also prefer to return a 401 when a user is not logged in but the change you suggests exposes the original security issue. Adapting the example in my original post:

```
$ curl -I https://app.example.com/restricted_resource/does-not-exist
HTTP/1.1 404 Not Found

$ curl -I https://app.example.com/restricted_resource/does-exist
HTTP/1.1 401 Unauthorized
```
From this, a non-signed-in user can begin to detect the paths for resources that exist on the system through brute force requests.

In addition sending a 401 status code to a web browser would cause it to pop up the basic authentication dialog for username and password. I'm presuming you're suggesting returning that to an API.

**Comment by guites** [comment]
I noticed that the documented solution to prevent exposing sensitive information results in a blank page when the protected URL is accessed via html.

```ruby
class ApplicationController < ActionController::Base
  rescue_from CanCan::AccessDenied do |exception|
    respond_to do |format|
      format.json { render nothing: true, status: :not_found }
      format.html { redirect_to main_app.root_url, notice: exception.message, status: :not_found } # <!--- non 3XX status is defined here
      format.js   { render nothing: true, status: :not_found }
    end
  end
end
```

This seems to happen because the `redirect_to` method only works for 3XX status codes, and the redirect is not performed on other codes. From the docs (source: https://api.rubyonrails.org/v7.1.2/classes/ActionController/Redirecting.html):

>The status code can either be a standard [HTTP Status code](https://www.iana.org/assignments/http-status-codes) as an integer, or a symbol representing the downcased, underscored and symbolized description. Note that the status code must be a 3xx HTTP code, or redirection will not occur.

This means that this difference between a 404 status with a blank page vs. 404 status with proper html could still be used to detect existing resources. Example:

```
$ curl -I 'http://127.0.0.1:3000/restricted_resource/does-exist' 
...
HTTP/1.1 404 Not Found
Content-Length: 0
```

(note the Content-Lenght: 0, meaning that a blank page was displayed since the redirect doesn't work)

```
curl -I 'http://127.0.0.1:3000/restricted_resource/does-not-exist'
HTTP/1.1 404 Not Found
Content-Length: 1722
```

(note the Content-Length: 1722, meaning that the redirect to the default html page worked).

This also caused confusion as I didn't understood right away why my app wasn't redirecting properly.

If anyone else is having this problem, my suggested solution is raising a not found exception, which makes rails correctly redirect to the default 404 page in all cases:

```ruby
class ApplicationController < ActionController::Base
  rescue_from CanCan::AccessDenied do |exception|
    respond_to do |format|
      format.json { render nothing: true, status: :not_found }
      format.html { raise ActiveRecord::RecordNotFound } # <!-- lets your app config handle the 404 normally
      format.js   { render nothing: true, status: :not_found }
    end
  end
end
```

(
to drive the point home, the requests now have the following response and content length:

```
$ curl -I 'http://127.0.0.1:3000/restricted_resource/does-exist' 
...
HTTP/1.1 404 Not Found
Content-Length: 1722
```

and 

```
curl -I 'http://127.0.0.1:3000/restricted_resource/does-not-exist'
HTTP/1.1 404 Not Found
Content-Length: 1722
```
).

If you guys think this is not obvious (I'm not from a rails background), I'll gladly open a PR with a note on the docs about this behavior. Thanks.
