### ISSUE TITLE
Rails API release

### ISSUE THREAD

**Issue by kevTheDev** [CanCanCommunity/cancancan#446]
Hi,

I see in the changelog there is some unreleased stuff to support rails api applications.

Was just wondering what the status is / likelihood of this getting an official release soon?

Many thanks for your continuing work and maintenance on this project.

Kev

**Comment by arturoherrero** [comment]
Same here, please push a new release.

Thank you.

**Comment by Schwad** [comment]
@coorasse thanks so much for self-assigning to this issue, really looking forward to the next minor. I see we had two minors and a major in the first half of the year, just to timetable do you reckon we could expect this wrapped in another minor by year-end? :)

**Comment by coorasse** [comment]
yes

**Comment by coorasse** [comment]
available in cancancan 2.1.0
