### ISSUE TITLE
After Upgrading From cancan 1.6.10 To cancancan 2.0.0 Three Tests Failing

### ISSUE THREAD

**Issue by ahcarpenter** [CanCanCommunity/cancancan#450]
### Steps to reproduce
So I have the following custom ability class:

```ruby
module Authx
  module Ability
    def initialize_authx_ability(user)
      return unless user.permissions
      user.permissions.each do |permission|
        can permission.parameterize.underscore.to_sym
      end
      # binding.pry
      link_authx_permissions
    end

    def link_authx_permissions(user = nil)
      # To be overwritten by the application, so that it can properly link the authx permissions into the general
      # cancan permissions.
    end
  end
end
```

As part of my test for the `User` model I have the following:

```ruby
describe User do
  before do
    class MyAppAbility
      include CanCan::Ability
      include Authx::Ability
      def initialize(user)
        initialize_authx_ability(user)
      end

      def link_authx_permissions(_user = nil)
        can :read, :all if can? :authx_user_access
      end
    end
  end

  it "should load abilities that cancan can use" do
    VCR.use_cassette("services/user/authenticate_success") do
      user = User.authenticate_with_credentials(Auth.params)
      ability = MyAppAbility.new(user)

      expect(ability.can?(:authx_user_access, nil)).to be_truthy
      expect(ability.can?(:voucher_access, nil)).to be_truthy
      expect(ability.can?(:fpu_central_access, nil)).to be_falsey
    end
  end
end
```

The user variable, after authenticating, contains the correct symbol in it's permissions hash (e.g. `:authx_user_access`) and can be seen when tracing through the `initialize_authx_ability` method. 

### Actual behavior
However after calling `can :authx_user_access` in the `initialize_authx_ability` method. `expect(ability.can?(:authx_user_access, nil)).to be_truthy` is returning a falsey value.

### Expected behavior
`expect(ability.can?(:authx_user_access, nil)).to be_truthy` returns a truthey value.

Any thoughts as to where I may be going wrong?

### System configuration
**Rails version**:
N/A

**Ruby version**:
2.4.0

**CanCanCan version**
2.0.0

**Comment by ahcarpenter** [comment]
UPDATE: So ensure that the subject is passed resolves the issue, but aren't user's expecting to have to make no changes with an upgrade? Or am I off there?

**Comment by coorasse** [comment]
Please refer to [Stackoverflow for questions](http://stackoverflow.com/questions/ask?tags=cancancan). Thanks.
