### ISSUE TITLE
cancancan 2.1.0 ignores params of new action

### ISSUE THREAD

**Issue by znz** [CanCanCommunity/cancancan#453]
### Steps to reproduce

```
git clone https://github.com/znz/example-cancancan-2_1_0-ignores-params-of-new
cd example-cancancan-2_1_0-ignores-params-of-new
bundle install
rails db:migrate
rails test:system
```

### Expected behavior

Use params of new action as default value.

### Actual behavior

Ignore params since cancancan 2.1.0.

### System configuration
**Rails version**: 5.1.4

**Ruby version**: ruby 2.3.5p376 (2017-09-14 revision 59905) [x86_64-darwin16]

**CanCanCan version** 2.1.0

**Comment by znz** [comment]
This caused by `params.is_a?(Hash) ? params : nil` in `CanCan::ControllerResource#resource_params_by_namespaced_name`.

**Comment by coorasse** [comment]
release in 2.1.1
