### ISSUE TITLE
Doesn't raise exception if resource is not found

### ISSUE THREAD

**Issue by camelmasa** [CanCanCommunity/cancancan#456]
### Steps to reproduce

Use `load_and_authorize_resource` method on Rails app, like below:

```rb
class UsersController < ApplicationController
  load_and_authorize_resource find_by: :uuid

  def show
  end
end
```

And then you access to not exist user path. (e,g, http://localhost:3000/users/not_exist_user_uuid)

I think this line  https://github.com/CanCanCommunity/cancancan/commit/33df7eb51a85692e702dc0e2a7252471bfe271ef#diff-38607cbe9e3608bd14d9367c9cf91eefL110 changed behavior

The line will raise exception if resource is not found.

### Expected behavior

Raise exception if resource is not found

### Actual behavior

Doesn't raise exception if resource is not found

### System configuration
**Rails version**: 5.1.4

**Ruby version**: 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin16]

**CanCanCan version** 2.1.1

**Comment by camelmasa** [comment]
@coorasse Let me know if the change is not specification. I'd like to create PR 😃

**Comment by lostapathy** [comment]
I can confirm that there is a behavior regression here between cancancan 2.1.0 and 2.1.1.  I'd go ahead and write a test and make that PR.

**Comment by coorasse** [comment]
go for it. thanks for the catch

**Comment by camelmasa** [comment]
@lostapathy Oh, I created PR for this. Thanks. 

@coorasse I created PR for fixing this. Could you review PR when you have time 🕐  https://github.com/CanCanCommunity/cancancan/pull/461

**Comment by coorasse** [comment]
I know understand better the issue. Maybe we could replace `find_by` with `find_by!` so we keep raising an exception but we don't reintroduce dynamic finders. what do you think?

**Comment by lostapathy** [comment]
+1 @coorasse Without testing it, that sounds like a good plan.

Should also keep the change to call .find_by! directly rather than invoking it via .send

**Comment by camelmasa** [comment]
@coorasse @lostapathy Sounds good 👍 I'll update files.

**Comment by camelmasa** [comment]
> Maybe we could replace find_by with find_by! so we keep raising an exception but we don't reintroduce dynamic finders.

@coorasse Did you mean we can change `find_resource_using_find_by` like below ❓ 

```rb
    def find_resource_using_find_by
      if resource_base.respond_to? "find_by!"
        resource_base.find_by!(@options[:find_by].to_sym => id_param)
      else
        resource_base.send(@options[:find_by], id_param)
      end
    end
```

**Comment by camelmasa** [comment]
I confirmed latest version 2.1.2 is released. The version fixed this issue. Close.
