### ISSUE TITLE
can dashboard is not working

### ISSUE THREAD

**Issue by andrew-aladev** [CanCanCommunity/cancancan#458]
``` ruby
can :dashboard
```

This will add a rule with
```ruby
actions = [:dashboard]
subjects = []
match_all = false
```

In this case when we tried to call `relevant?` it will provide `false`:
```ruby
action = :dashboard
subject = nil
matches_action? - true
matches_subject? - false
```

The problem is here:
```ruby
@subjects = Array(subject)
```

`Array(nil)` will provide just an empty array.

**Comment by andrew-aladev** [comment]
I see that you wanted to obtain several/single `actions` and `subjects` by using `Array([:a, :b]) -> [:a, :b]`, `Array(:a) -> [:a]`.

We couldn't fix it with `@actions = [action]; @subjects = [subject]`. We need to use something like:

```ruby
@actions = action.is_a?(Array)? action : [action]
@subjects = subject.is_a?(Array)? subject : [subject]
```

**Comment by coorasse** [comment]
this is intended. using `can` without a subject is not allowed. see [here](https://github.com/CanCanCommunity/cancancan/pull/402) the change and [here](https://github.com/CanCanCommunity/cancancan/issues/413#issuecomment-314063045) a proposed solution for RailsAdmin.
