### ISSUE TITLE
CanCan::Ability#merge copies only rules

### ISSUE THREAD

**Issue by npetkov** [CanCanCommunity/cancancan#468]
I'm a bit confused about how the `Ability#merge` method works. Looking at the source code, the only thing it does is to transfer the rules form the argument to the receiver. If the argument defines aliased actions, they won't be copied, thus breaking the rules. I doubt this is a bug, but it nevertheless seems like inconsistent behaviour to me. If this is done by design (it may be tricky to merge alias actions), please provide some insight into the matter.

### Steps to reproduce

Please see the provided [gist](https://gist.github.com/npetkov/e7e6ff57cddacae62c19babdaeaeb7e6).

### Expected behavior

The created ability should include the aliased actions.

### Actual behavior

The created ability doesn't include anything except the rules, as this is how the `merge` method works now.

### System configuration
**Rails version**:

5.1

**Ruby version**:

2.4.1

**CanCanCan version**

2.1.1

**Comment by afdev82** [comment]
Yes, I already opened this issue for that: https://github.com/CanCanCommunity/cancancan/issues/280.
