### ISSUE TITLE
After adding gem 2.1.2 to Gemfile, Rails API jBuilder response is not returned

### ISSUE THREAD

**Issue by Pepan** [CanCanCommunity/cancancan#469]
### Steps to reproduce
- Add gem 'cancancan', '~> 2.0' to gemfile
- Rebuild, restart
- Try response from get action

### Expected behavior
I should return json response from Jbuilder view (it does without cancancan in Gemfile)

### Actual behavior
It responds with OK status but empty response of text mime type

### System configuration
**Rails version**: 5.1.4

**Ruby version**: 2.4.1

**CanCanCan version**: 2.1.2

- after reverting to version 2.0 and adding "include CanCan::ControllerAdditions" by hand to "ApplicationController" it works again ...

**Comment by coorasse** [comment]
I think #457 may address your issue. Could you please point to `gem 'cancancan', git: 'https://github.com/Eric-Guo/cancancan', branch: :develop` and tell me if it works there?

**Comment by Pepan** [comment]
Hi! Its working! Using git: 'https://github.com/Eric-Guo/cancancan', branch: :develop
:)

**Comment by Schwad** [comment]
Is this flagged up for an incoming release? If so maybe we can close this issue when that release comes out. I see #457 is merged :)

**Comment by coorasse** [comment]
Fixed in 2.1.3
