### ISSUE TITLE
Using accessible_by with overriding roles

### ISSUE THREAD

**Issue by lesliev** [CanCanCommunity/cancancan#47]
I am having trouble using cancancan to select records based on abilities.

My ability.rb file looks like this:

``` ruby
    can :read, Business if user.admin?

    can :read, Business, Business.user_related(user) do
      Business.user_related(user).any?
    end
```

My controller tries this:

``` ruby
@businesses = Business.accessible_by(current_ability, :read)
```

If I comment out the top rule, everything seems to work. That is, I can load businesses produced by the Business.user_related scope. But if I include the top rule I get the error: "Unable to merge an Active Record scope with other conditions. Instead use a hash or SQL for read Business ability."

If the user is an admin, cancancan doesn't need to consult the database at all - they have access to all businesses. How can I express this in ability.rb?

**Comment by robertokl** [comment]
+1 on the "example should be in the docs".
