### ISSUE TITLE
Initial attributes rewrite loaded parent relation

### ISSUE THREAD

**Issue by Able1991** [CanCanCommunity/cancancan#472]
If I have a rule related to the parent resource, I have something that the value of the rule erases the realation with the parent resource
My rules:
```ruby
user.related_objects.each do |relatet_object|
 can :manage, ChildObject, { :user_id => user.id, :object_id => relatet_object.object_id}
end
```
Controller code:
```ruby
load_and_authorize_resource :object
load_and_authorize_resource :child_object, :through => :object
```
I have two objects with ids 1 and 2, at the time of build the resource, the correct reference to the parent is first specified, but it is replaced by the initial attributes, which according to the created rules will be:
```ruby
{ :user_id => 1, :object_id => 1}.merge({ :user_id => 1, :object_id => 2}) => { :user_id => 1, :object_id => 2}
```
https://github.com/CanCanCommunity/cancancan/blob/e88a26793d9452804155f3fa0e027c3c76294787/lib/cancan/ability.rb#L188-L196

https://github.com/CanCanCommunity/cancancan/blob/8fc2a2dbefc542749650da6b957335e8075b34a3/lib/cancan/controller_resource_builder.rb#L9-L22

Perhaps it is worth not to consider the initial attribute if it has already been set?

**Comment by coorasse** [comment]
Please write a gist to reproduce the issue. https://gist.github.com/coorasse/3f00f536563249125a37e15a1652648c

**Comment by Able1991** [comment]
Look
https://gist.github.com/Able1991/b593faa741474ef9d216ed03f5f11f42

**Comment by coorasse** [comment]
Hi, I analysed your gist and the definition of the abilities was the issue. If you define the abilities like that:
```
can :read, Library, id: user.library_ids
can :read, Book, library_id: user.library_ids
can :manage, Book, library: { library_users: {user_id: user.id, manage: true} }
```

the tests pass. Please feel free to re-open providing another non-working test. Thank you!

**Comment by Able1991** [comment]
> Hi, I analysed your gist and the definition of the abilities was the issue. If you define the abilities like that:
> 
> ```
> can :read, Library, id: user.library_ids
> can :read, Book, library_id: user.library_ids
> can :manage, Book, library: { library_users: {user_id: user.id, manage: true} }
> ```
> 
> the tests pass. Please feel free to re-open providing another non-working test. Thank you!

I know that you can pass an array, but this is not an explicit behavior, therefore a ticket was created
