### ISSUE TITLE
CaCanCan or abilities

### ISSUE THREAD

**Issue by anquegi** [CanCanCommunity/cancancan#473]
### Steps to reproduce

In CanCanCan For Rails < 4.2 use: gem 'cancancan', '~> 1.10'

when I have an User with this characteristics

      when Role.superadmin
        can :manage, :all
        cannot :manage, Incident
        can :manage, Incident, client_id: user.client_ids_including_descendants(false)
        can :manage, Incident, id: user.incident_id_by_support_request
       end

### Expected behavior
This only works the last condition, and should be and or, but it also have no sense because the first is for all, the second cannot for all, but how can I achieve this, without the clauses 

        can :manage, :all
        cannot :manage, Incident

it works as expected, but I need the first for other objects than can manage this user

### System configuration
**Rails version**:
3.2.4.22
**Ruby version**:
2.1.6
**CanCanCan version**

**Comment by coorasse** [comment]
Please refer to [Stackoverflow for questions](http://stackoverflow.com/questions/ask?tags=cancancan). Thanks.
