### ISSUE TITLE
accessible_by bug after upgrading to rails 5.2

### ISSUE THREAD

**Issue by lizzyaustad** [CanCanCommunity/cancancan#478]
### Steps to reproduce

1. Upgrade to Rails 5.2 (currently at '5.2.0.beta2' version)
2. Call `accessible_by` (or run active_record_adapter spec)

Gist: https://gist.github.com/lizzyaustad/4096f904f6d0b409462f7fdf7c60b65e

### Expected behavior
Should be able to use `accessible_by` without raising exception

### Actual behavior
An exception is raised: 
```
ActiveRecord::StatementInvalid: SQLite3::MismatchException: datatype mismatch: SELECT  "articles".* FROM "articles" WHERE ((secret='t') OR ("articles"."published" = ?)) LIMIT ?
```

This is due to [a change in Rails 5.2](https://github.com/rails/rails/blob/213796fb4936dce1da2f0c097a054e1af5c25c2c/activerecord/lib/active_record/relation/predicate_builder.rb#L55) that creates a BindParam node for the attribute. The BindParam node moves the intended value for the query under `.value_before_type_cast` instead of the previous `.val` it had before with the Casted node, resulting in a query like the one above, where the `?` value does not get filled in: `("articles"."published" = ?)) LIMIT ?` 

### Possible fixes

If this error persists with the official release of Rails 5.2, [this change](https://github.com/lizzyaustad/cancancan/commit/2edaeea8ccffa8bf8ecd6d012bc59105cbfa7ab0#diff-20ac589324d94d717930010cddec29b8) in active_record_4_adapter.rb could fix the issue on the cancancan side.

### System configuration
**Rails version**: 5.2.0.beta2

**Ruby version**: 2.3.0

**CanCanCan version** 2.0.0

**Comment by kylekeesling** [comment]
I'm seeing what seems to be the same error, using postgresql

**Comment by jeffpereira** [comment]
The error is based on the pieces of code that turn ActiveRecord queries into SQL, so the issue will exist on any SQL based DB. @kylekeesling

**Comment by kylekeesling** [comment]
Ok good to know. I just wanted to make sure I provided the right context for what I was seeing.

**Comment by andrewculver** [comment]
@lizzyaustad Thanks very much for your for your PR. It allowed us to move forward using Rails 5.2.0-rc1 in the meantime.

**Comment by toao** [comment]
I'm seeing deprecation warnings apparently triggered by accessible_by: ```DEPRECATION WARNING: expand_hash_conditions_for_aggregates is deprecated and will be removed from Rails 6.0``` with rails 5.2

**Comment by coorasse** [comment]
This issue should be solved with the latest version of CanCanCan

**Comment by capjuancode** [comment]
Was this resolve and from what version, I currently have it on 1.17.0

**Comment by raoulalwani** [comment]
@capjuancode you probably already figured this out, but for one app we just upgraded on, we went from 1.15 to 2.3.0. Leaving this here for anyone else who might stumble across it. 

For reference, this issue arose when upgrading to Rails 5.2
