### ISSUE TITLE
accessible_by with :manage "all"

### ISSUE THREAD

**Issue by NomNomCameron** [CanCanCommunity/cancancan#483]
`Model.accessible_by(current_ability)` causes:

`The accessible_by call cannot be used with a block 'can' definition. The SQL cannot be determined`

Is there currently not a way to return all records for a model when this permission is in the ability class?

**Comment by NomNomCameron** [comment]
I feel like the anticipated results of `accessible_by` for an ability class that doesn't explicitly have sql or resource conditions to go off of would be to return all the records?

**Comment by coorasse** [comment]
Please refer to [Stackoverflow for questions](http://stackoverflow.com/questions/ask?tags=cancancan). Thanks.
