### ISSUE TITLE
Ability precedence regression upgrading from 1.17.0 to 2.1.3

### ISSUE THREAD

**Issue by oboxodo** [CanCanCommunity/cancancan#485]
While upgrading from 1.17.0 to 2.1.3 we had some tests failing and apparently they fail because we define admin abilities like this:

```ruby
can :manage, :all
# Not even Admins are allowed to do this if there's no selected object.
cannot :show_dashboard, nil
```

### Steps to reproduce

Here's a gist which reproduces the problem. As you can see, using cancancan version 1.17.0 all 4 tests pass, but changing to 2.1.3 the last test fails.

https://gist.github.com/oboxodo/13dccd70edfaa2fda95b5ceb2bf46804

### Expected behavior
Restricting a `can :manage, :all` with subsequent `cannot` calls should work.

### Actual behavior
The `cannot` call seems to no have effect at least when the object is specified as `nil`.

### System configuration
**Rails version**: 5.0.6

**Ruby version**: 2.4.3

**CanCanCan version**
1.17:0: works
2.1.3: doesn't work

**Comment by coorasse** [comment]
The problem is with `cannot :show_dashboard, nil`. You should explictly pass a subject, therefore I suggest you to change it to `cannot :show, :dashboard`
