### ISSUE TITLE
unauthorized_message does not correctly localize namespaced models

### ISSUE THREAD

**Issue by ahharvey** [CanCanCommunity/cancancan#486]
CanCanCan's unauthorized_message method does not correctly localize namespaced models. 

### Steps to reproduce

1. Create `Namespace::Model` model and controller.
2. Set `load_and_authorize_resource` on the controller. 
3. Define a localized model name in `config/locales`, e.g., "Custom Name".
3. Call any controller action with an unauthorised user. 
4. CanCanCan generates flash "not authorized for namespace/model" 
5. CanCanCan is expected to generate flash "not authorized for Custom Name".

 ### Fix

The problem appears to be the [unauthorized_message method in ability.rb](https://github.com/CanCanCommunity/cancancan/blob/develop/lib/cancan/ability.rb#L181-L187).

This method uses:
`variables[:subject] = (subject.class == Class ? subject : subject.class).to_s.underscore.humanize.downcase`

It would appear that this issue could be resolved by editing `unauthorized_message` to use: 
`variables[:subject] = subject.model_name.human`

I'm happy to submit a patch if someone can confirm this is a valid issue and fix?

**Comment by coorasse** [comment]
That's a valid issue. Please open a PR with a regression test.

**Comment by coorasse** [comment]
Fixed by https://github.com/CanCanCommunity/cancancan/pull/462. Will be released in 3.0.0
