### ISSUE TITLE
Add details on traversing associations to Wiki

### ISSUE THREAD

**Issue by BookOfGreg** [CanCanCommunity/cancancan#497]
This is not an issue but I was wanting to help with the Wiki;

In the [hash of conditions](https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities#hash-of-conditions) section, it's not immediately obvious how to traverse AR associations.

For instance, if a `user` had  an `account`, and that has_many `services`, which has_many `parts`, the ability would look like this in order to meet the associations in the middle:

```ruby
# Associations
class User; belongs_to :account; end
class Account; has_one :user; has_many :services; end
class Service; belongs_to :account; has_many :parts; end
class Part; belongs_to :service; end

# Ability
can :manage, Part, service: { account: user.account }
```

But it took me longer than I care to admit to find out 😁

**Comment by coorasse** [comment]
Added a section regarding this point: https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities#traverse-associations

Thanks! 👏
