### ISSUE TITLE
Any way to use ActiveRecord `where` as conditions?

### ISSUE THREAD

**Issue by eunjae-lee** [CanCanCommunity/cancancan#498]
Hi, all.

Is there any way to use `where` as conditions?

```ruby
class Ability
  include CanCan::Ability

  def initialize(current_user)
    can :read, App, App.where(company: current_user.company)
                       .not.where(status: 3)
  end
end
```

Hash conditions is good, but sometimes I want to express things that cannot be done in hash.
(Does anyone know how to declare `not` condition in hash?)

And I don't want to use block because as far as I know, it's just ruby code iterating each record and checking. That's not query executed on database.
I want a database-y way.

If cancan accepts `where` clauses as conditions, I think it would be much better.
What do you think?
If I'm thinking wrong, please let me know.

Thanks.

**Comment by eunjae-lee** [comment]
Okay, I admit I've never read [Best Practice](https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities%3A-Best-Practices) page. I read [Defining Abilities](https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities) a lot, but since the link was broken, I thought it was still on progress of writing.

![image](https://user-images.githubusercontent.com/499898/38916669-dc28b0f8-431a-11e8-99be-107cc6e4fa4e.png)

Now I know CanCanCommunity prefers hash way.
Then could somebody advise me how to express that code in hash way?

**Comment by eunjae-lee** [comment]
@coorasse Thanks for the link.
When I tried `App.where(...)` thing,

this worked
```
>> App.accessible_by(MyAbility.new(user)).count
28
```

but this didn't
```
>> MyAbility.new(user).can? :read, app1
CanCan::Error: The can? and cannot? call cannot be used with a raw sql 'can' definition. The checking code cannot be determined for :read #<App...
```

**Comment by coorasse** [comment]
The scope works, of course, only for associations. If you want to use it on a single instance you need to define also  the block part. Example:

```
can :read, Photo, Photo.unowned do |photo|
      photo.groups.empty?
    end
```

I close this since is no bug, 
Please refer to [Stackoverflow for questions](http://stackoverflow.com/questions/ask?tags=cancancan). Thanks.
