### ISSUE TITLE
skip_load_and_authorize_resource behaves abnormally

### ISSUE THREAD

**Issue by orbit-dna** [CanCanCommunity/cancancan#500]
Controllers derived from one controller may overwrite each other's skip_load_resource (and skip_authorize_resource).

### Steps to reproduce

Build these things in a rails app:

models: Foo, Bar

controllers:
``` ruby
class ApplicationController < ActionController::Base
  load_resource
  skip_load_resource only: :index
end

class FoosController < ApplicationController
  def new
    render plain: @foo.class.name
  end
end

class BarsController < ApplicationController
  skip_load_resource only: :new
  def new
    render plain: @bar.class.name
  end
end
```

then follow these steps:
1. start rails with RAILS_ENV=development. At this time, neither FoosController/BarsController is loaded.
2. access FoosController#new, get 'Foo'.
3. access BarsController#new, get 'NilClass'.
4. access FoosController#new, get 'NilClass'.

### Expected behavior
step 4 should render 'Foo'

### Actual behavior
step 4 rendered 'NilClass'

### System configuration
**Rails version**: 5.2.0

**Ruby version**: 2.4.3

**CanCanCan version**: 2.2.0

### more detail
The problem is here:
https://github.com/CanCanCommunity/cancancan/blob/9258979745b944c39a5aa047f0599b719145dee0/lib/cancan/controller_additions.rb#L287-L289
https://github.com/CanCanCommunity/cancancan/blob/9258979745b944c39a5aa047f0599b719145dee0/lib/cancan/controller_additions.rb#L295
and
https://github.com/CanCanCommunity/cancancan/blob/9258979745b944c39a5aa047f0599b719145dee0/lib/cancan/controller_additions.rb#L209

A controller using `skip_load_resource` will get his `_cancan_skipper` (by create or inherit). Then all his subclasses will inherit this same `_cancan_skipper`, and the `skip_load_resource` in these subclasses will operate this same `_cancan_skipper`. 
see: http://api.rubyonrails.org/classes/Class.html#method-i-class_attribute

I would like to post a gist, but cannot findout how to test controllers with a simple way as example in 'https://gist.github.com/coorasse/3f00f536563249125a37e15a1652648c'.

**Comment by kraflab** [comment]
Maybe instead of using a class attribute, the `cancan_skipper` method should be something like this?
```ruby
def cancan_skipper
  @cancan_skipper ||= parent_cancan_skipper || default_cancan_skipper
end

def parent_cancan_skipper
  parent_skipper = superclass.try(:cancan_skipper)
  parent_skipper.dup if parent_skipper
end

def default_cancan_skipper
  { authorize: {}, load: {} }
end
```
Maybe there is a simpler shorthand for this.

**Comment by coorasse** [comment]
I updated the gist with an example of a test for controllers. PR is welcome for this issue

**Comment by stoodfarback** [comment]
I don't have a test or pr, but here's a quick patch I used to fix this for myself. Maybe it'll be useful for others.

```
module CanCanSkipperFixInheritance
  def self.included(klass)
    klass.extend(ClassMethods)
  end

  module ClassMethods
    def inherited(klass)
      super
      klass._cancan_skipper = cancan_skipper.deep_dup
    end
  end
end

class ActionController::Base
  include(CanCanSkipperFixInheritance)
end
```

**Comment by coorasse** [comment]
I am closing due to lack of interest. Please anyone, open a PR if interested in solving this issue. For now I close it. Thank you!
