### ISSUE TITLE
`can?` gives me weird return and is it intended?

### ISSUE THREAD

**Issue by eunjae-lee** [CanCanCommunity/cancancan#501]
### Steps to reproduce

```ruby
class MyAbility
  include CanCan::Ability
end

>> ability = MyAbility.new
>> ability.can :read, App, { company: user.company }
>> ability.can? :read, App
true
```

### Expected behavior
It should be able to read some apps only under my company.

### Actual behavior
It is able to read whole App class itself. It sounds like it is able to read any instances of App class.
Is this intended or a bug?

### System configuration
**Rails version**: 4.1.16

**Ruby version**: 2.2.4

**CanCanCan version**
tested in both 1.10 and 2.2.0

**Comment by coorasse** [comment]
Yes. Is intendend and explained here: https://github.com/CanCanCommunity/cancancan/wiki/Checking-Abilities#checking-with-class

Unfortunately the wiki is big and information are sparse and sometimes difficult to find.

**Comment by eunjae-lee** [comment]
@coorasse Sorry I didn't see that. Thanks for helping me through this.
