### ISSUE TITLE
Bad singularize version of controller : uninitialized constant

### ISSUE THREAD

**Issue by newfylox** [CanCanCommunity/cancancan#502]
### Steps to reproduce

* create a model named `CloudDrive`
* create a controller named `CloudDrivesController`
* use `authorize_resource` helper inside the controller

### Expected behavior
`authorize_resource` should find a model named `CloudDrive` to associate to `CloudDrivesController`

### Actual behavior
`authorize_resource` is looking for a model named `CloudDrife` because the `singularize` version is wrong

https://github.com/CanCanCommunity/cancancan/blob/e633592294f931c710c7a2bb591ffc4b4b32bfef/lib/cancan/controller_resource.rb#L304

### System configuration
**Rails version**: 5.0.4

**Ruby version**: 2.4.1

**CanCanCan version :** 1.17.0

**Comment by kraflab** [comment]
This is an issue with rails inflections.  Maybe this can help you :slightly_smiling_face:
https://github.com/rails/rails/issues/4997#issuecomment-3927414
