### ISSUE TITLE
LoadError with namespaces

### ISSUE THREAD

**Issue by JrmKrb** [CanCanCommunity/cancancan#504]
As I explain here https://github.com/rails/rails/issues/32800, there is a few cases `safe_sanitize` can still raise an exception, `LoadError`in that case, and I believe it should not in the below mentionned case.

I believe we should have something like this:
```ruby
    def namespaced_name
      begin
        [namespace, name].join('/').singularize.camelize.safe_constantize || name
      rescue LoadError
        name
      end
    end
```
instead of
```ruby
    def namespaced_name
      [namespace, name].join('/').singularize.camelize.safe_constantize || name
    end
```
as we expect `safe_constantize` to not raise any exception

### Steps to reproduce

Define model `FirstModule::MyModel` in `app/models/first_module/my_model.rb`
Define controller `SecondModule::FirstModule::MyModelsController` in `app/controllers/second_module/first_module/my_models_controller.rb` with a `new` action and route

Call `load_and_authorize_resource :my_model, class: "FirstModule::MyModel"` in the controller.

Go to this route, `LoadError: Unable to autoload constant MyModel, expected [...]/app/models/first_module/my_model.rb to define it`

### Expected behavior
`namespaced_name` should return `"my_model"`

### Actual behavior
 `namespaced_name` raises a `LoadError` as `safe_sanitize` should not.

### System configuration
**Rails version**: 5.2.0

**Ruby version**: 2.4.2

**CanCanCan version** 2.2.0

**Comment by coorasse** [comment]
Does this issue still exist in Rails 6.0 where zeitwerk is in use? Could you provide a gist to reproduce?
