### ISSUE TITLE
Negated matcher of "be_able_to" has unexpected behavior

### ISSUE THREAD

**Issue by oliver-xapix-io** [CanCanCommunity/cancancan#505]
### Steps to reproduce

I forked this repo, but couldn't get the test suite running within 10 mins. I am at work, so I cannot spend too much time on this. Here's my report and monkey patch.

```
# app/models/ability.rb

can(:read, User)
``` 

```
# rspec/models/ability_spec.rb

ability = Ability.new(user)
expect(ability).to_not` be_able_to(%i[read update], User)
```

### Expected behavior

It should fail because `:read` ACTUALLY IS allowed. 

### Actual behavior

It passes.

### Monkey patch

The logic for negation over a list needs to be different.

```
# cancancan/lib/cancan/matchers.rb

Kernel.const_get(rspec_module)::Matchers.define :be_able_to do |*args|
  #...
  
  match_when_negated do |ability|                                                                                                  
    actions = args.first                                                                                                           
    if actions.is_a? Array                                                                                                         
      break false if actions.empty?                                                                                                
      actions.all? { |action| ability.cannot?(action, *args[1..-1]) }                               
    else                                                                                                                           
      ability.cannot?(*args)                                                                                                       
    end                                                                                                                            
  end

  #...
end                                                                                                                              
```

### System configuration

**Rails version**: any

**Ruby version**: any

**CanCanCan version**: any

**Comment by coorasse** [comment]
You are saying "expect not to be able to read and update the User". This is logically true since you are not allowed to update, therefore you cannot do both operations. The matcher uses a AND and not a OR.

**Comment by stowersjoshua** [comment]
I personally agree with @oliver-xapix-io.
Primarily because it would be the cleanest way of testing for excluded permissions.

Perhaps we can add a second matcher for this? Maybe something like `be_unable_to`? 
@coorasse - If you're open to it, I don't mind writing the PR.

**Comment by stowersjoshua** [comment]
I made the mistake of writing a "fix" before checking if this had already been discussed. It would feel like a waste not to, so I [made a PR](https://github.com/CanCanCommunity/cancancan/pull/602) in case you reconsider.
