### ISSUE TITLE
can :update and can :edit is not the same

### ISSUE THREAD

**Issue by tmaier** [CanCanCommunity/cancancan#507]
### Steps to reproduce

According to [wiki/Action Aliases](https://github.com/CanCanCommunity/cancancan/wiki/Action-Aliases) `:edit` is an alias of `:update`.

I do have the following ability:

```ruby
can :edit, Account
can :update, User
```

### Expected behavior

The following four tests should pass:

```ruby
      it { is_expected.to be_able_to(:edit, account) }
      it { is_expected.to be_able_to(:update, account) }
      it { is_expected.to be_able_to(:edit, user) }
      it { is_expected.to be_able_to(:update, user) }
```

### Actual behavior

The `account` related tests fail.
The `user` related tests pass.

### System configuration
**Rails version**: 4.2

**Ruby version**: 2.4.4

**CanCanCan version**: 2.1.3

I am working now on a Gist.

**Comment by coorasse** [comment]
Is the other way around. If you give `update` permissions, you are also able to `edit`.

**Comment by tmaier** [comment]
Yes, this is what I can see as well.

However, this is not obvious.
An alias is usually something which works in both ways.

If this will stay, it would be great to get at least a warning in the logs

**Comment by umar-vs** [comment]
I want to use only edit functionality??
How i can do this
