### ISSUE TITLE
load_and_authorize_resource and new with params causes ActiveModel::ForbiddenAttributesError

### ISSUE THREAD

**Issue by znz** [CanCanCommunity/cancancan#51]
I create example app: https://github.com/znz/rails4-cancancan-example

In the app, `http://localhost:3000/comments/new?comment%5Bpost_id%5D=1` causes `ActiveModel::ForbiddenAttributesError`.

In `lib/cancan/controller_resource.rb`,
`resource_params` called from `build_resource` returns `params['comment']` directly instead of `comment_params` (includes `permit`) because `param_actions` does not include `:new`.

For now, I will use `post_id=1` instead of `comment[post_id]=1` and set `comment.post_id = params[:post_id]` in `CommentController#new`.

**Comment by adampal** [comment]
Thanks @victorpolko, after hours of digging your answer solved my problem.
`load_and_authorize_resource` relies on a standard name for you whitelist params method.  It needs to be singular!
