### ISSUE TITLE
Ability#merge should change binding

### ISSUE THREAD

**Issue by Haniyya** [CanCanCommunity/cancancan#517]
### Steps to reproduce

Define an ability with a rule that, through a closure, depends on another ability defined later.

Merge said ability into your main ability and expect the main ability to be able to use the rule.

For clarity, here's a gist: 

https://gist.github.com/Haniyya/0eed93d93796ecba13dabc855faf51e8

### Expected behavior
I would expect `Ability` to be able to `do_stuff`. But the closure in the definition of `do_stuff` still has the `BasicAbility` as the `self` value and thus returns false. 

I may be wrong in this but I'd expect merge to overwrite the context of said closure. 

### Actual behavior
The closure references the wrong ability and fails the check.

### System configuration
Rails 5.1.0

Ruby 2.5.0

CanCanCan 2.2.0

**Comment by Haniyya** [comment]
Since changing bindings is pretty difficult, it'd be better to just `instance_eval` the blocks in the context of the new ability.

**Comment by coorasse** [comment]
Could you open a PR to address this issue?

**Comment by coorasse** [comment]
I am closing this issue due to a lack of feedback. A PR to address it is welcome. Thanks.
