### ISSUE TITLE
CanCanCan throwing ActiveModel::UnknownAttributeError setting non existing attribute

### ISSUE THREAD

**Issue by bighoax** [CanCanCommunity/cancancan#520]
### Steps to reproduce

I have a very simple controller that uses a service to import mobile users, this was working fine prior to rails 5 upgrade, so I m certain it's not the service code. This is my controller :

```
    module Admin
      module MobileUsers
        class ImportsController < Admin::BaseController
          load_and_authorize_resource class: MobileUser
    
          def create
            binding.pry
            importer = ::MobileUserImportService.new(resource_params)
            success  = importer.perform
            unless success
              @error = importer.error
              render :create, status: 400
            end
          end
    
          private
    
          def resource_params
            params.permit(:file)
          end
        end
      end
    end
```

When I try to execute my rspec test for create action I get this error:

```
     ActiveModel::UnknownAttributeError:
           unknown attribute 'file' for MobileUser.
```

And the code execution doesn't even stop at `binding.pry` inside `create` method. I've looked over this link from cancancan:

https://github.com/CanCanCommunity/cancancan/wiki/Strong-Parameters

But it didn't resolve my issue, the strong params method doesn't seem to be issue here (I've tried naming the method `create_params`, `import_params`, and even tried custom_name for sanitizer, all resulted in same issue).

**Does anyone have experience with this, how to resolve it?** I mean I could try and add virtual attribute file on my `MobileUser` and hopefully that would resolve it, but it doesn't seem like a good fix.

This happened only after I've transitioned to rails 5.

### Expected behavior
Should execute my service code

### Actual behavior
Raises error:

```
     ActiveModel::UnknownAttributeError:
           unknown attribute 'file' for MobileUser.
```

### System configuration
**Rails version**:
5.0.0
**Ruby version**:
2.3.4
**CanCanCan version**
1.17.0

**Comment by bighoax** [comment]
The issue was that I needed to change `load_and_authorize_resource` to `authorize_resource` as I really don't need an actual object for create action

**Comment by errawn** [comment]
ok
