### ISSUE TITLE
Authorize! on non model backed controllers

### ISSUE THREAD

**Issue by dannio** [CanCanCommunity/cancancan#53]
Hi all,

I've tried to use cancancan on my rails app and so far it's fine. However, once I tried to apply it to non model backed controllers with non restful resources, I run into several issues.

I use authorize_resource :class => false, which according to the documentation should be calling: 

authorize! 

on every action in the controller for me automatically.

unfortunately this is not the case and the authorization is only done if I call authorize on every single action in the controller.

Is there a way around this?

DOESN'T WORK:
class DashboardsController < ApplicationController
authorize_resource :class => false
  def home
  end

WORKS:
class DashboardsController < ApplicationController
authorize_resource :class => false
  def home
    authorize! :home, :dashboard
  end

**Comment by Thadeu** [comment]
load_and_authorize_resource :class => false resolved my problem
