### ISSUE TITLE
Not getting nested resource loaded on :index

### ISSUE THREAD

**Issue by kinsbrunner** [CanCanCommunity/cancancan#531]
Hi guys,

I am facing a very weird problem as, for some reason, I am getting more results than expected ones. There are Schools (parent). Each School has many Communications (children), each of them is related to a Family through a Recipient. 

I am expecting to get ONLY those Communications where current_user's Family is a Recipient but, for some reason, I am getting ALL the Communications from that School. From the :index action, I am accessing into Communications through @school.communications but this is always nil. When accessing into School through @school, it works fine.

It is really annoying that the written tests are all working as expected and that, through Console, I am simulating the rules ad they are also working.

Suggestions and solutions are very welcome!
Regards.
Alejandro.

**Communications controller:**
```
    before_action :authenticate_user!
    load_and_authorize_resource :school
    load_and_authorize_resource :communication, through: :school

    # GET /schools/:school_id/communications
    def index
      json_response_ser(@school.communications.order(:created_at), CommunicationFullSerializer)
    end

  def json_response_ser(object, serializer, status = :ok)
    # helper that responds with JSON and an HTTP status code (200 by default)
    render json: object, status: status, each_serializer: serializer
  end
```

**Some of the abilities definition:**
```
    # School: can only read the School where is assigned to
    can :read, School do |s|
      s.families.include?(user.origin.try(:family))
    end

    # Communication: can read all the Communications where the Family was recipient
    can :read, Communication do |c|
      user.origin.try(:family).communications.include?(c)
    end
```

### System configuration
**Rails version**: 5.2.0
**Ruby version**: 2.3.1p112
**CanCanCan version**: 2.2.0

Just to share some further details, when debugging through console, I am doing:

```
coms = Communication.where(school_id: 2) --> returns 9 results
coms.map{ |c| Ability.new(user).can?(:index, c)} ---> returns [true, true, true, true, true, false, false, false, false]
```
This is exctly the desired behaviour but, for some reason, when calling action through API, it is returning the 9 communications instead of only 5.
Looking further on the console, I have found that the when calling the action it is selecting those Communicactions which belong to the school while, when testing ability throgh console it is also taking into account the fact to bring those which are relevant for the current family (expected behaviour).

As a temporary workaround, I have implemented the following code which returns the expected results but which does quite a lot of additional accesses into DB:

```
        @school.communications.map do |c|
          @coms.push(c) if can?(:read, c)
        end
        json_response_ser(@coms, CommunicationFullSerializer)
```

![image](https://user-images.githubusercontent.com/16242832/45258751-f3675500-b393-11e8-87ce-30508200d2fd.png)

Please help! It will be really appreciated!

**Comment by coorasse** [comment]
Please refer to [Stackoverflow for questions](http://stackoverflow.com/questions/ask?tags=cancancan). Thanks.
