### ISSUE TITLE
Typo on Defining Abilities page

### ISSUE THREAD

**Issue by dapawn** [CanCanCommunity/cancancan#542]
There is a typo in the first code snippet on the 'Defining Abilities' page at:
`https://github.com/CanCanCommunity/cancancan/wiki/defining-abilities`

The line:
`    can :read, :all . # permissions for every user, even if not logged in `
should be:
`    can :read, :all   # permissions for every user, even if not logged in    `
(no period after `:all`)

**Comment by coorasse** [comment]
thanks 🙇
