### ISSUE TITLE
Nil error on creating a record through a scoped relationship using just `:manage`

### ISSUE THREAD

**Issue by mikeyduece** [CanCanCommunity/cancancan#544]
### Steps to reproduce
When having a scoped set of record that a user can `:manage`, it causes a nil error. 

```ruby
def initialize(user)
  can(:manage, user.current_arena.events.pluck(:id))
end
```

### Expected behavior
Expected behavior is that it allows the user the ability to create an event scoped to that arena without issue

### Actual behavior
When signed is a user with this permission, it throws a nil error when attempting to create a record scoped for the current arena.

### System configuration
**Rails version**:  4.2.6

**Ruby version**: 2.5.0

**CanCanCan version**: 2.3.0

### My fix

I simply define a set of permission associated with the user and the arena and check those to see if they can create or whatever. Could maybe also check for a role on the user as well using Rolify or something.

```ruby
def initialize(user)
  can(:create, Event) if user.can_create_events? # A boolean set in a seperate record. Developer can check against any permissions check they want.

  can(:manage, user.current_arena.events.pluck(:id)) if user.can_manage_events?
end
```

**Comment by coorasse** [comment]
You are not passing a list of records but a list of `ids`. Is as if you write `can :manage, [1,2,3]`, so basically as if you give permission to the user to manage some integers.
Please refer to [Stackoverflow for questions](http://stackoverflow.com/questions/ask?tags=cancancan). Thanks.

**Comment by mikeyduece** [comment]
Sorry, oversight on my part, I forgot to state it as a potential addition to the wiki on defining abilities. I'm aware of why it was erroring out. It took me a long while to figure out why I wasn't able to create. I was not able to find anywhere in the documentation or on SO about needing a separate `:create` if using scoped records. So I thought I'd make a suggestion on adding to the wiki.
