### ISSUE TITLE
protected method `authorize!' called

### ISSUE THREAD

**Issue by bramski** [CanCanCommunity/cancancan#545]
### Steps to reproduce
Looks like most recent cancancan is not including a method in the ControllerResource class.
<img width="1420" alt="screen shot 2018-11-12 at 11 20 26 am" src="https://user-images.githubusercontent.com/421781/48370037-fd942100-e66c-11e8-8e93-f2bb4fd040ff.png">

**Rails version**: 5.1.6

**Ruby version**: 2.5.1

**CanCanCan version**: 2.3.0

**Comment by coorasse** [comment]
Everything seems to work fine and the method is available. You are probably overriding the method?

**Comment by coorasse** [comment]
I close this due to lack of feedback. Please feel free to re-open in case you encounter the issue again. I cannot help more.
