### ISSUE TITLE
wiki update: Ability in Database Example is out-of-date with Rails 4.x +

### ISSUE THREAD

**Issue by davidtolsma** [CanCanCommunity/cancancan#546]
### Current Example https://github.com/CanCanCommunity/cancancan/wiki/Abilities-in-Database
class Ability
  include CanCan::Ability

  def initialize(user)
    can do |action, subject_class, subject|
      user.permissions.find_all_by_action(aliases_for_action(action)).any? do |permission|
        permission.subject_class == subject_class.to_s &&
          (subject.nil? || permission.subject_id.nil? || permission.subject_id == subject.id)
      end
    end
  end
end

### Expected behavior
The current example does not work with Rails 4.1 + since the dynamic finders have been removed

### Actual behavior
class Ability
  include CanCan::Ability

  def initialize(user)
    can do |action, subject_class, subject|
      user.permissions.where(action: aliases_for_action(action)).any? do |permission|
        permission.subject_class == subject_class.to_s &&
          (subject.nil? || permission.subject_id.nil? || permission.subject_id == subject.id)
      end
    end
  end
end

### System configuration
**Rails version**: 5.2

**Ruby version**: 2.5

**CanCanCan version**: 2.3.0

**Comment by coorasse** [comment]
Thank you! 🙇
