### ISSUE TITLE
I can no longer cache current_ability in memcached (work with  CanCan 1.4 )

### ISSUE THREAD

**Issue by cyrilus** [CanCanCommunity/cancancan#547]
### Steps to reproduce
Before I have this code to store ability in cache with cancan 1.4  because it slows down the loading of pages, because I have many custom actions in many controllers, each page reloads all the features 
I have try with dalli cache or redis from rails 5.2

def current_ability
    Rails.cache.fetch("#{current_user.profil.cache_key}::ability") do
      super
    end
  end

But now with cancancan 2.0.0
I get this error 
ActionView::Template::Error (can't dump hash with default proc)

So I can't use cache like redis or memcached anymore

What I understand is that ability can't not be marshalled anymore.

Thanks

**Comment by coorasse** [comment]
A copy of your `ability.rb` would be useful. CanCanCan may slow down the app if the `ability.rb` file is not written properly. You may also want to look into https://medium.com/@coorasse/cancancan-that-scales-d4e526fced3d
