### ISSUE TITLE
Add link to cancan-inherited_resources on wiki page

### ISSUE THREAD

**Issue by TylerRick** [CanCanCommunity/cancancan#549]
It looks like the wiki is not editable to normal humans like myself (which surprised me greatly as I've never seen a project that locked it down before; I had to do a double take to see if the edit link was just somewhere else on the page).

May I suggest, first of all, adding some instructions on https://github.com/CanCanCommunity/cancancan/wiki for what the preferred way of making/requesting edits to the wiki is? I've cloned the wiki repo but I don't think there's a way to submit a MR directly to it, is there?

Here is a patch from `git format-patch` for your consideration.

[0001-Mention-cancan-inherited_resources.patch.txt](https://github.com/CanCanCommunity/cancancan/files/2645697/0001-Mention-cancan-inherited_resources.patch.txt)

(Rather than making it sound like it's simply not _possible_ in versions later than 2.)

Thanks!

**Comment by coorasse** [comment]
Thanks. Help is always appreciated also from normal human beings.
