### ISSUE TITLE
Unnecessary & slow query executed when using scope as condition

### ISSUE THREAD

**Issue by albb0920** [CanCanCommunity/cancancan#552]
### Steps to reproduce
gist: https://gist.github.com/albb0920/09ff9e790d8d3d2b29dcfe98ca7f5c9e

When using a scope as condition, `conditions_empty?` in conditions_matcher.rb will check the condition against an empty hash with operator `==`, which will cause ActiveRecord to load the relation.

Code path
- "activerecord-5.2.0/lib/active_record/associations/collection_proxy.rb:46:in `load_target'"
- "activerecord-5.2.0/lib/active_record/associations/collection_proxy.rb:988:in `=='"
- "cancancan-2.3.0/lib/cancan/conditions_matcher.rb:90:in `conditions_empty?'"
- "cancancan-2.3.0/lib/cancan/rule.rb:46:in `only_block?'"
- "cancancan-2.3.0/lib/cancan/ability.rb:198:in `any?'"
- "cancancan-2.3.0/lib/cancan/ability.rb:198:in `has_block?'"
- "cancancan-2.3.0/lib/cancan/controller_resource.rb:74:in `load_collection?'"

Changing conditions_empty? as followed fixed my problem.
```
def conditions_empty?
  (@conditions.is_a?(Hash) && @conditions == {}) || @conditions.nil?
end
```

### Expected behavior
Using scope as condition should not trigger query in load_resource

### Actual behavior
Using scope as condition triggers a query in load_resource

### System configuration
**Rails version**:
5.2.0

**Ruby version**:
2.5.1

**CanCanCan version**
2.3.0

**Comment by coorasse** [comment]
You should write the rule as `can :read, Book, user_id: user.id`. This way you don't need to load the association at all.

**Comment by albb0920** [comment]
I believe loading records from association is unintentional,
as you can see in my description, all it want is to check whether `@conditions` is an empty hash,
which shouldn't trigger the association to load records.

The example in my gist is just to demonstrate this bug.

As for why we're use associations, 
we actually have a stored procedure in DB for authorization for a few models, that way we can share authorization logic between multiple app.
It is wrapped as a scope and used in conjunction with other scopes.

In other projects, I also find using scopes makes the ability file much easier to read.

It's just a one line fix, should I submit a PR?

**Comment by albb0920** [comment]
The problem is it will load all records from DB when going through cancancan, which is very very slow.
I do pagination in my controller, this will cause it to do DB query twice.

As I said, I need to call a stored procedure. IIUC, I can't use the hash syntax.
My options seems to be the SQL syntax or using association.

**Comment by coorasse** [comment]
The syntax I proposed you executes exactly the same query on DB.

**Comment by albb0920** [comment]
Sorry, I should quote which part I'm replying

> I don't see why you shouldn't load the association since you want to retrieve the `@books`

The problem is it will load all records from DB when going through cancancan, which is very very slow.
I do pagination in my controller, this will cause it to do DB query twice.

> The syntax I proposed you executes exactly the same query on DB.
I can't use this syntax because in the real case I'm using cancan, I need to write custom SQL.
Or maybe I'm missed something.

I'm actually doing something like this
```ruby
class Post < ApplicationRecord
  def self.readable_by_user(user)
      where(                                                                                                                           
        %{EXISTS (SELECT 1 FROM authorized_for_resource(?, ?, "#{table_name}".id))},                                                   
        user.id,                                                                                                                       
        to_s                                                                                                                           
      )                                
  end
end
```

```ruby
can :index, Post, Post.readable_by_user(user) do
end
```

**Comment by coorasse** [comment]
and `Post.accessible_by(user).page(3)` returns all the records? Is this the problem?

**Comment by albb0920** [comment]
It won't return all the records, it will fire another query with correct offset and limit.
So there will be two queries, one without limit and offset from cancancan, and I with limit and offset from my application.

Like this:

![image](https://user-images.githubusercontent.com/276340/53313038-79e80280-38f2-11e9-90bc-d4a1a11441bc.png)

**Comment by Matchlighter** [comment]
I'm running into this issue as well. I use a pattern like this to defer authorization to a different model (I think I got it from the Wiki) `can :manage, Rule, { context: RelatedObject.accessible_by(self, :manage) }`, but it is blowing up loading the entirety of `RelatedObject.accessible_by(self, :manage) }` when there is no need.

**Comment by coorasse** [comment]
This will be fixed in the next release
