### ISSUE TITLE
User with two roles

### ISSUE THREAD

**Issue by djmaximaldonado** [CanCanCommunity/cancancan#555]
Hi, 
I have 4 roles on my app.
I would like to kwnow if a user can have two roles ( for example role 1 and rol 2 at the same time ) .

Sorry if it isnt the right place to make the question.

Thanks, Maxi.

**Comment by coorasse** [comment]
Please refer to [Stackoverflow for questions](http://stackoverflow.com/questions/ask?tags=cancancan). Thanks.
