### ISSUE TITLE
Wiki: Update how best practices work for hash conditions

### ISSUE THREAD

**Issue by onebree** [CanCanCommunity/cancancan#562]
### Steps to reproduce

Check out the third list item on the following page:

https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities%3A-Best-Practices#use-hash-conditions-as-much-as-possible

> 3. Hash conditions are OR'd in SQL, giving you maximum flexibilty.
> 
> Even though ActiveRecord treats chained scopes as SQL ANDs, CanCanCan treats hash conditions for a given model/action pair as SQL ORs.

This text was misinterpreted by me and a team mate, until we checked the actual SQL query for a permission with: `User.accessible_by(current_ability, :read).to_sql`

Maybe this can be reworded or clarified?

### Issue

This chunk of text can be misinterpreted as meaning:

> Within the hash condition, each key-value pair will be joined with `OR` in the final SQL query for that specific ability definition

### Suggestion

This chunk of text should be reworded to convey the following:

> Every time you define an ability with `can`, each `can` chains together with `OR` in the final SQL query for that model

**Comment by coorasse** [comment]
👍  Thank you. I updated that part with your suggestion and simplified it, even more, to stick to the point.
