### ISSUE TITLE
Before_action @key set to random numeric (object_id)?

### ISSUE THREAD

**Issue by spiffistan** [CanCanCommunity/cancancan#563]
### Steps to reproduce

When controller testing for loaded filters, using `load_and_authorize_resource`, I noticed that the added `before_action` filters has a random numeric key set (perhaps the object_id of the proc?), making it impossible to deduce which filters have been loaded.

```ruby
#<ActiveSupport::Callbacks::Callback:0x00007ffc25f406e0
      @chain_config=
       {:scope=>[:kind],
        :terminator=>
         #<Proc:0x00007ffc25f2ef80 (lambda)>,
        :skip_after_callbacks_if_terminated=>true},
      @filter=#<Proc:0x00007ffc25f40a28>,
      @if=[],
      @key=70360472618260,
      @kind=:before,
      @name=:process_action,
      @unless=[]>
```

### Expected behavior
The key should probably be set to `:load_and_authorize_resource`

### Actual behavior
The @key is set to 70360472618260, probably the `object_id` of the proc.

### System configuration
**Rails version**: 5.2.0

**Ruby version**: 2.5.3

**CanCanCan version**: 2.3.0

**Comment by coorasse** [comment]
How would you set this key? Could you share a code example? Thanks

**Comment by spiffistan** [comment]
On further inspection, upon looking at the [source in Rails](https://github.com/rails/rails/blob/master/activesupport%2Flib%2Factive_support%2Fcallbacks.rb#L368), it seems to set the identifier to object_id specifically when the callback is a Proc. 

I suppose it has to be solved upstream in Rails, perhaps by supplying an optional argument `key` to the before_action method or something like that.

**Comment by coorasse** [comment]
Good. I thought the same. I'll close this issue for now. Thank you for your contribution, is always appreciated!
