### ISSUE TITLE
defining ability for HABTM 

### ISSUE THREAD

**Issue by chrisgeek** [CanCanCommunity/cancancan#572]
I have the following,but it does not seem to work,is it that cancancan gem doesn't work properly with a HABTM association? the code below returns no assessments, but i have assessments related to the user in my db

``class User < ActiveRecord::Base
  has_and_belongs_to_many :assessments
end``

``class User < ActiveRecord::Base
  has_and_belongs_to_many :users
end``

```class Ability
  include CanCan::Ability
  def initialize(user)
    # a user can only manage assessments related to it 
   can :manage, Assessment, users: { id: user.id }
  end
end```

**Comment by coorasse** [comment]
Hi, from #576 I can see that HABTM works just fine. If you have any issue, please fill a gist (is provided in the issue template) to reproduce it.
