### ISSUE TITLE
Include conditions in permissions?

### ISSUE THREAD

**Issue by kbighorse** [CanCanCommunity/cancancan#574]
`Ability#permissions` can be misleading when a rule has conditions, it only shows broad `can` or `cannot` `:read` on a class, for example. Is there a way to dynamically show permitted conditions within a class for a given ability? End goal is to avoid returning records that the user cannot read, for example, given any arbitrary user.

**Comment by coorasse** [comment]
Can you share a gist where you show your issue? Is provided in the issue template. This will help me to better understand your issue. Thanks.

**Comment by kbighorse** [comment]
My issue was addressed by this:
https://github.com/CanCanCommunity/cancancan/wiki/Fetching-Records

(I failed to see the link to more wiki pages..)
Thanks for your attention.
