### ISSUE TITLE
Regression in 3.0.0: ArgumentError using symbol-to-proc

### ISSUE THREAD

**Issue by jaredbeck** [CanCanCommunity/cancancan#584]
### Steps to reproduce

https://gist.github.com/jaredbeck/83607c9c98222f0496356ac04e51f981

### Expected behavior
Symbol-to-proc should work as in 2.3.0

### Actual behavior
Symbol-to-proc causes ArgumentError

### System configuration
See gist

**Comment by coorasse** [comment]
already reported in #583. Fix is coming in 3.0.1 version. Thank you!

**Comment by jaredbeck** [comment]
> already reported in #583. Fix is coming in 3.0.1 version. Thank you!

Thanks Alessandro
