### ISSUE TITLE
Apply accessible_by to all controller actions unless overrideen

### ISSUE THREAD

**Issue by etcook** [CanCanCommunity/cancancan#585]
Apologies in advance if this is answered somewhere in the docs, but I couldn't find anything in issues or the documentation when searched.

The automatic scoping to accessible_by for the index action was a welcome change. Is there a way to permanently apply accessible_by across all controller actions unless overridden for extra security?

Apologies in advance if this is covered in the documentation or an issue. I was not able to find it answered.

### System configuration
**Rails version**:

5.0.7.2

**Ruby version**:

2.4.5

**CanCanCan version**

3.0.1

**Comment by coorasse** [comment]
Please refer to [Stackoverflow for questions](http://stackoverflow.com/questions/ask?tags=cancancan). Thank you 🙇 .

**Comment by etcook** [comment]
> Please refer to [Stackoverflow for questions](http://stackoverflow.com/questions/ask?tags=cancancan). Thank you 🙇 .

@coorasse Apologies. I meant for this to be less a discussion of how to do it, but more if it doesn't exist, should we have that option, and if so, whether you'd accept a PR for it.

Thanks!

**Comment by coorasse** [comment]
No worries. Your use case is not clear to me: if it's a feature request, please try to provide me with some code and context to better understand your request.
