### ISSUE TITLE
Rule's inspect method fails when the rule is created through a SQL array

### ISSUE THREAD

**Issue by frostblooded** [CanCanCommunity/cancancan#589]
### Steps to reproduce
Define ability with a SQL array and call #inspect.

### Example

```
CanCan::Rule.new(true, :read, Watermelon, ['visible=?', true], {}, {}).inspect
```

### Expected behavior
The method displays the rule in a string format.

### Actual behavior
There is an error:

```
 TypeError:
       no implicit conversion of nil into String
     # ./lib/cancan/rule.rb:37:in `+'
     # ./lib/cancan/rule.rb:37:in `inspect'
     ...
```

### System configuration
Rails version:
5.1.7 (not relevant)
Ruby version:
2.4.6 (not relevant)
CanCanCan version
3.0.1

**Comment by coorasse** [comment]
fixed in 3.0.2
