### ISSUE TITLE
Class vs instance permissions incorrect

### ISSUE THREAD

**Issue by tomasc** [CanCanCommunity/cancancan#595]
### Steps to reproduce

```ruby
class TestAbility
  include CanCan::Ability

  def initialize(owner)
    cannot :read, DummySubject
    can :read, DummySubject, id: 123
  end
end

@ability = TestAbility.new(user)
@dummy_subject = DummySubject.new(id: 123)
```

### Expected behavior

```ruby
@ability.can?(:read, DummySubject) # => false
@ability.can?(:read, @dummy_subject) # => true
```

The user should not be able to `:read` any object of the `DummySubject` class.
But, it should be able to `:read` a specific one.

### Actual behavior

```ruby
@ability.can?(:read, DummySubject) # => true
@ability.can?(:read, @dummy_subject) # => true
```

Adding any conditional rule automatically makes the whole class readable. That seems logically incorrect.

### System configuration
**Rails version**:
6.0.0.rc1

**Ruby version**:
2.6.3p62

**CanCanCan version**
3.0.1

**Comment by coorasse** [comment]
Hi @tomasc , thanks for opening the issue. The explanation on why this happens is here: https://github.com/CanCanCommunity/cancancan/wiki/Checking-Abilities#checking-with-class
The current behaviour is considered correct.

**Comment by tomasc** [comment]
Hi @coorasse thanks for the explanation, that is helpful.
