### ISSUE TITLE
accessible_by with hash of conditions causes Not unique table/alias

### ISSUE THREAD

**Issue by Nghi93** [CanCanCommunity/cancancan#596]
### Steps to reproduce

Problem occurs with cancancan 3.x when a hash condition is defined, which
does a LEFT JOIN but the exact same table is already joined due to some eager loading or something else.

https://gist.github.com/Nghi93/c00d9dd83d3e51af5512cf4d36ed340f

### Expected behavior
In cancancan 2.x it does not do a second LEFT JOIN on the same table.

### Actual behavior
In cancancan 3.x it does a second unnecessary LEFT JOIN on the same table.

ActiveRecord::StatementInvalid: Mysql2::Error: Not unique table/alias: 'claim_files': SELECT DISTINCT `claims`.* FROM `claims` INNER JOIN `claim_files` ON `claims`.`claim_file_id` = `claim_files`.`id` LEFT OUTER JOIN `claim_files` ON `claim_files`.`id` = `claims`.`claim_file_id` WHERE `claim_files`.`policy_id` = 1 AND `claim_files`.`some_attribute` = 'a'

Maybe the LEFT OUTER JOIN could be done with an alias?
In cancancan 2.0 it seems the second join is omitted.

### System configuration
**Rails version**: 5.2.0

**Ruby version**: 2.5.5

**CanCanCan version** 3.0.1

**Comment by Nghi93** [comment]
Workaround:
Claim.includes(claim_file: :policy).accessible_by(current_ability) # seems cleaner anyway

We had a few other cases in which we had to change `includes`, `join` to left_joins in order to avoid the error above.

**Comment by ghiculescu** [comment]
can you please check if https://github.com/CanCanCommunity/cancancan/pull/600 fixes this for you

**Comment by fsateler** [comment]
The latest commit on #605 should fix this
