### ISSUE TITLE
Getting error after updating from cancan to cancancan and rails 3.2 to rails 4.0.13

### ISSUE THREAD

**Issue by rahul8sharma** [CanCanCommunity/cancancan#609]
undefined method `defined_enums' for #<Class:0x0055b914f8d8d8>

Getting error on this line:

`- if can? :update, @campaign`

**Comment by dannemanne** [comment]
I suspect this is because the Enum module (that defines `defined_enums`) was added to ActiveRecord in version 4.1. Maybe it will work if you can go straight to 4.1, but maybe try to jump right ahead to 4.2 since that is officially the oldest version supported by CanCanCan according to the Readme

**Comment by coorasse** [comment]
Please refer to [Stackoverflow for questions](http://stackoverflow.com/questions/ask?tags=cancancan). Thank you 🙇 .
