### ISSUE TITLE
Slug / FriendlyID + load_and_authorize_resource

### ISSUE THREAD

**Issue by dwyn** [CanCanCommunity/cancancan#611]
Hiya!  So Ive implemented [slugs](https://rubygems.org/gems/slug) on the pokemon model in [this app](https://github.com/dwyn/pokemonfun). 

In the routes file I have `resources :pokemons, param: :slug`

In the `pokemons_controller.rb` I am attempting to utilize `load_and_authorize_resource`, but unfortunately it isn't working. Im fairly certain it has something to do with my routes using `:slug` in params instead of `:id`

FWIW, I also tried  `load_and_authorize_resource :find_by => :slug` and that didn't work either. I am open to any suggestions!

**Comment by coorasse** [comment]
Please refer to [Stackoverflow for questions](http://stackoverflow.com/questions/ask?tags=cancancan). Thank you 🙇 .
