### ISSUE TITLE
how to use Abilities in Database

### ISSUE THREAD

**Issue by crodrigr** [CanCanCommunity/cancancan#616]
### Steps to reproduce

Please describe accurately how to reproduce the issue and post all necessary code.

Hi,

I am tring to use cancancan with abilities in database. I did to create table permmisios and relation to user, but I don't to know what valules action, subject_class and subject_id, but document, not have example. I need full document about abilites in database. Thanks. 

If you provide a Gist to reproduce the issue this will make the debug much easier.

Please copy the following Gist and edit it to reproduce your issue: https://gist.github.com/coorasse/3f00f536563249125a37e15a1652648c

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### System configuration
**Rails version**: 6

**Ruby version**: 2.6.5

**CanCanCan version* 3.0.2

**Comment by crodrigr** [comment]
please help me, how to use cancancan with abilities in Database

**Comment by coorasse** [comment]
Please refer to [Stackoverflow for questions](http://stackoverflow.com/questions/ask?tags=cancancan). Thank you 🙇 .
