### ISSUE TITLE
Checking Abilities - Checking with Class - THIS IS REALLY REALLY WRONG!

### ISSUE THREAD

**Issue by Pepan** [CanCanCommunity/cancancan#617]
### Steps to reproduce

Read wiki https://github.com/CanCanCommunity/cancancan/wiki/Checking-Abilities#checking-with-class or use it in your code ...

### Expected behavior
I personally prefer just pass class to block, let's developer deal with it. It is much better than just treat everything as **true** ... it leads to unsolvable problems.

#### For example
There is conditioning block that user manager of "something" is able to access items of this "something" (_you are not able to specificities it without knowing "something"!!! so you cannot have condition before **can**_)
``` Ruby
    can %i[read edit update destroy], Company do |company|
      @user.has_role? :manager, company&.account
    end
```  

this leads to whatever user asks for ```can? :index, Company``` will get response **true** ... what the heck? For example *guest*!!! 

Does developer said that? No! So why should *guest* have access to code after this last ```can?``` ????

### Actual behavior
```can? :index, Company``` responds true for any user who is asking even if it is not specified in Abilities.
there is nothing like 
``` Ruby
    can %i[read edit update destroy], Company if user.present?
```  
just
``` Ruby
    can %i[read edit update destroy], Company do |company|
      @user.has_role? :manager, company&.account
    end
```  
which have condition inside which should prevent anyone to access records except one who passed the block with true

### System configuration
**Rails version**: Rails 6.0.2.1

**Ruby version** :ruby 2.6.5-p114

**CanCanCan version**: 3.0.2

**Comment by Pepan** [comment]
related issue https://github.com/CanCanCommunity/cancancan/issues/401 - with weird answer ... I will do monkey patch - but why every one should want reliable system must monkeypatch???

problem is this method where `@base_behavior` is hardcoded as **true**
/ruby-x.x.x/gems/cancancan-3.0.2/lib/cancan/conditions_matcher.rb:21
```
    def matches_block_conditions(subject, *extra_args)
      return @base_behavior if subject_class?(subject)

      @block.call(subject, *extra_args.compact)
    end
```
not clever :/

**Comment by coorasse** [comment]
Calm down and open a pull request like everyone else or use the magic fork button and make your `reallyreallyrightcancancan` gem. 
There is no space for wining here, only people putting a lot of time and effort into maintaining a library used by thousands. 
The fact that you cannot understand it doesn't make it REALLY REALLY WRONG.

**Comment by Pepan** [comment]
I created PR with refactor https://github.com/CanCanCommunity/cancancan/pull/624
