### ISSUE TITLE
Array(subject) calling #to_a or #to_ary and issuing big queries

### ISSUE THREAD

**Issue by Aryk** [CanCanCommunity/cancancan#631]
I was scratching my head why "select * from users" was being run whenever I would check an ability.

I did pass in the "User" model into the ability along with a proc and I was doing a simple can? check. Should not be executing a query I thought.

I then noticed that you guys are trying to cast subjects to arrays. I think what you were intending was Array.wrap, which does this without any duck-typed method:

In Rule#initialize:

```ruby
 @subjects = Array(subject)
```

Array(subjects) calls #to_a to #to_ary on the `subject` which can cause all sorts of problems if you intend subject to not only be AR objects.

In Sequel (which is used by a lot of people), calling User.to_a returns all the records from memory.

Can we change this to Array.wrap or a simple:

```ruby
    @subjects = subject.is?(Array) ? subject : [subject]
```

**Comment by coorasse** [comment]
This should be tackled in 3.2.0. Feel free to re-open if the problem persists.
