### ISSUE TITLE
Typo in the Wiki

### ISSUE THREAD

**Issue by psychoslave** [CanCanCommunity/cancancan#632]
There's a repetition in https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities : `because because`. And it looks like the wiki is not in an edit access for all mode. :smile:

**Comment by joaocv3** [comment]
Removing the duplicated word:

https://github.com/CanCanCommunity/cancancan/pull/644

**Comment by coorasse** [comment]
thanks
