### ISSUE TITLE
Version 3.1.0 not created on github but is on rubygems

### ISSUE THREAD

**Issue by skangg** [CanCanCommunity/cancancan#637]
Current version of cancancan on github is 3.0.2 while on rubygem it is 3.1.0. 

It seems like there is a potential that someone forgot to create the release on github.

**Comment by tmikoss** [comment]
Also, the changelog does not reflect the 3.1.0 release. This makes me wary of upgrading - it appears as if the 3.1.0 is not an official release.

**Comment by coorasse** [comment]
Forgot to push the version bump. sorry for the confusion.
