### ISSUE TITLE
Hash conditions containing symbols problem

### ISSUE THREAD

**Issue by Silex** [CanCanCommunity/cancancan#65]
Hello,

I found this blog post that explain the problem I'm having:

http://www.tigraine.at/2014/03/13/cancan-beware-of-symbol-conditions

Basically, if you look at the following rules:

``` ruby
can :manage, Item, user: { role: :admin }  #1
can :manage, Item, user: { role: 'admin' } #2
```

With both rules `Item.accessible_by(current_ability)` will return the correct results. But only the 2nd rule will work with `can? :manage, Item.accessible_by(current_ability).first`

This is because the symbols are not translated to a string the usual way rails does.

Not sure if really a bug or a not.

[EDIT] I believe this is a bug, just because of the unexpected behavior.

**Comment by freemanoid** [comment]
I think this is **not a bug**. There is a [similar issue][1] in Squeel gem.
There is a note in [rails docs][2]:
```
The values cannot be symbols. For example, you cannot do Client.where(status: :active).
```
Thus it's not a bug, actually it's just a trick that you can **sometimes** use symbols as values. 
Related issue: https://github.com/activerecord-hackery/squeel/issues/67

[1]: https://github.com/activerecord-hackery/squeel#symbols-as-the-value-side-of-a-condition-in-normal-where-clauses
[2]: http://edgeguides.rubyonrails.org/active_record_querying.html#hash-conditions
[3]: https://github.com/rails/docrails/commit/50c5005bafe7e43f81a141cd2c512379aec74325
