### ISSUE TITLE
CanCanCan 3.2 requires ActiveRecord adapter

### ISSUE THREAD

**Issue by starpeak** [CanCanCommunity/cancancan#671]
When I update CanCanCan on a Rails project, that does use Mongoid instead of AR, I get the following error on startup:

.../gems/ruby-2.6.6/gems/cancancan-3.2.0/lib/cancan/config.rb:6:in `valid_accessible_by_strategies': uninitialized constant CanCan::ModelAdapters::ActiveRecordAdapter (NameError)

It does not matter if I include cancancan-mongoid or not. In my optinion it should check if AR is used on the config valid_accessible_by_strategies like it does on the loading of files in cancan.rb

**Comment by coorasse** [comment]
@ghiculescu caused by https://github.com/CanCanCommunity/cancancan/blob/3c17def3a058c7f20175388998c82690d6eebe6d/lib/cancan/config.rb#L6, right? Would you mind offering a patch for the mongoid people? :) I think we don't need these configurations for Mongoid.

**Comment by ghiculescu** [comment]
Sorry about that @starpeak!

https://github.com/CanCanCommunity/cancancan/pull/674

**Comment by ghiculescu** [comment]
@coorasse should we aim for a 3.2.1 release with https://github.com/CanCanCommunity/cancancan/pull/673 + #674 ?
