### ISSUE TITLE
Handling soft-deletes

### ISSUE THREAD

**Issue by gingerlime** [CanCanCommunity/cancancan#700]
This is just a general question rather than a bug report.

We're using `load_and_authorize_resource` successfully, and it works great in most cases. There's one thing that I'm not sure how to tackle.

We implemented soft-delete via a flag. e.g.

```ruby
can [:show, :destroy, :index, :create, :update], Entry, :deleted => false
```

The "problem" (more of an ergonomics issue) is that if a user deletes an entry, and then goes to the entry page, they will get a Forbidden 403 error. Technically it's true that they're not allowed to see it. However, a 404 would be a "nicer" way to treat an entry that (from a user perspective) was deleted...

Is there an elegant way to handle it?

**Comment by tejaszambre** [comment]
Well if the user is **allowed** to access the page then its obvious to give 404.
But in the case if user is **not allowed**, then giving 404 will not help, as it tells if the record exists or not. What I am trying to say is 404 will give a little more information which user is not supposed to get.
So 403 is the elegant way to handle it.

**Comment by gingerlime** [comment]
I'm not sure I understand what you're saying. The record is deleted, but we simply mark it as deleted rather than delete it, and the user can no longer access it. 404 seems like the semantically correct thing to return, rather than 403.

Btw, github returns a 404 if you access a repo that is private and if you're not allowed to access it. It helps avoid even knowing if the private repo exists or not.

**Comment by tejaszambre** [comment]
You were focusing only on the deleted user, so I got confused.
>However, a 404 would be a "nicer" way to treat an entry that (from a user perspective) was deleted...

However if you are saying to show 404 in both cases(deleted or not) for the unauthorised user, Then yes it makes sense now.

**Comment by gingerlime** [comment]
I was talking about a resource (I called it Entry) being deleted. I think if the user is not authorized to access it, then 403 is definitely semantically correct. However if the resource gets deleted, then a 404 makes more sense. I wouldn't say it fits both cases.

**Comment by tejaszambre** [comment]
What I am trying to say is, It should be the same for both cases(entry deleted or not deleted).
Now 404 or 403 may depend on some cases, one of which is given below.

Talking about Github, there exists a case where you are allowed to access some repositories of the user(public repositories). So 
Github gives 404 for a private repository for both cases(existing or non-existing) which makes sense.

To conclude, if user entry contains something which should be shared with others, then 404 makes sense otherwise we should consider 403.

**Comment by coorasse** [comment]
This should hopefully help you solving your situation: https://github.com/CanCanCommunity/cancancan/blob/develop/docs/handling_access_denied.md#danger-of-exposing-sensible-information

**Comment by gingerlime** [comment]
Thank you @coorasse.

I ended up using something like this in the specific controller

```ruby
class XyzController < ApplicationController
...
  rescue_from CanCan::AccessDenied do
    raise ActiveRecord::RecordNotFound
  end
end
