### ISSUE TITLE
Dynamically modify hash can ability

### ISSUE THREAD

**Issue by arthurwozniak** [CanCanCommunity/cancancan#710]
Hi,

I am having troubles rewriting block ability into hash. Rewrite would have positive performance impact in my scenario, however I am probalby reaching limits of cancancan.

### Steps to reproduce

Lets consider following models

```ruby
class Recipe
   # name: string
   # description: string
   has_many :ingredients
   # ...
end

class CompanyBranchRecipe
   belongs_to :company_branch
   belongs_to :recipe

   # enabled: boolean
   # owner: boolean
end

class Ability

attr_accessor :scoped_company_branch_ids

end
```

Motivation for model `CompanyBranchRecipe` is case when you have one enity which wants to share record from `Recipe` to another entity. If you load `recipes` for one entity, it is exactly the same as if you load it for second entity unless `enabled` flag.

I want to limit unregistered users from seeing `enabled==false` recipes.

Old code with block

```ruby
can :read, Recipe do |recipe|
  recipe.company_branch_recipes(company_branch_id: scoped_company_branch_ids, enabled: true)
end
```

New hash condition

```ruby
can :read, Recipe, company_branch_recipes: { company_branch_id: scoped_company_branch_ids, enabled: true }
```

I have tried to change statement like
```ruby
can :read, Recipe, company_branch_recipes: { company_branch_id: -> { scoped_company_branch_ids }, enabled: true }
```
hoping lambda is evaliated in runtime, but is is nullified by `ActiveRecord::Sanitization#sanitize_sql`. 

One possibility is to define ability after scoping, but it prevents of multiple scoping in one request. It is not problem for me, but I would like to figure out universal solution which would allow to user to change accessible records dynamically. Lets discuss! 

### Expected behavior
User can read recipes enabled for `scoped_company_branch_ids` entities.

### Actual behavior
User cannot read no recipe, because `scoped_company_branch_ids` is `nil` at moment of instantiation of rules. Value is assigned in runtime of API. 

### System configuration
**Rails version**: 6.0.3

**Ruby version**: 2.7.2

**CanCanCan version**: 3.2.1

**Comment by arthurwozniak** [comment]
So I have so far ended up with quite ugly, but working solution. I really dislike that SQL hacking with two abilities, but it seems to be cleanest way by now

```
class Ability
  include CanCan::Ability

  attr_reader :scoped_company_branch_ids

  def initialize
    # This condition enables reading of Recipes without company branch scope. Thus we match Recipe.company_branch_id and CompanyBranchRecipe.company_branch_id.
    # !!! WARNING: It assumes SQL JOIN to company_branch_recipes
    can %i[index read], Recipe, ["'{}'=? AND company_branch_recipes.enabled=TRUE AND company_branch_recipes.company_branch_id=recipes.company_branch_id", scoped_array_class] do |recipe|
      recipe.enabled_for? scoped_company_branch_ids
    end
    # This condition enables reading of Recipes with company branch scope.
    # !!! WARNING: It assumes SQL JOIN to company_branch_recipes
    can %i[index read], Recipe, ['company_branch_recipes.enabled=TRUE AND company_branch_recipes.company_branch_id=ANY(?)', scoped_array_class] do |recipe|
      recipe.enabled_for? scoped_company_branch_ids
    end
  end

  def scoped_array_class
    @scoped_array_class ||= ScopedArrayClass.new self
  end

  def scoped_company_branch_ids=(value)
    @scoped_company_branch_ids= Array.wrap value
  end

  class ScopedArrayClass
    def initialize(ability)
      @ability = ability
    end

    def value_for_database
      "{#{@ability.scoped_company_branch_ids.join ','}}"
    end
  end
end
```

**Comment by coorasse** [comment]
I think your use case is complex enough to justify a solution based on pure SQL + block. This is usually where I end up when stuff gets complicated.

```
can :read, Recipe, "SQL conditions" do
  # condition on single recipe
end
```

so yrs, what you actually did.
