### ISSUE TITLE
Version 3.2.2

### ISSUE THREAD

**Issue by reedstonefood** [CanCanCommunity/cancancan#715]
On [rubygems](https://rubygems.org/gems/cancancan), the latest version is 3.2.2, released a few weeks ago.

However, the version number on the default branch [in this repository](https://github.com/CanCanCommunity/cancancan/blob/develop/lib/cancan/version.rb) says 3.2.1. And the readme only mentions up to 3.2.1.

What is the explanation for this? I'm a little worried there may have been a security breach.

**Comment by coorasse** [comment]
https://github.com/CanCanCommunity/cancancan/releases/tag/3.2.2
