### ISSUE TITLE
Cancancan Wiki is gone

### ISSUE THREAD

**Issue by hsonthach** [CanCanCommunity/cancancan#732]
### Steps to reproduce

I have just checked the wiki page for some nice documentation, which is used to be at https://github.com/CanCanCommunity/cancancan/wiki there, but now it gone, I wonder why.

### Expected behavior
It should have shown the wiki page

### Actual behavior
It redirected me to github repository of cancancan

**Comment by coorasse** [comment]
Documentation is now part of the repository. You can find it [here](https://github.com/CanCanCommunity/cancancan/tree/develop/docs)

**Comment by Judahmeek** [comment]
The Changelog links, especially for the v2 to v3 upgrade instructions, still point to the now non-existent wiki.
