### ISSUE TITLE
Upgrade from 2.x to 3.x Guide

### ISSUE THREAD

**Issue by bueti** [CanCanCommunity/cancancan#734]
Not really an issue with CanCanCan but I'm in the process of upgrading a Rails 5.2 app and I'm looking into upgrading CanCanCan as well. 
Unfortunately the upgrade guide (https://github.com/CanCanCommunity/cancancan/wiki/Migrating-from-CanCanCan-2.x-to-3.0) (and wiki?) no longer exists.
Is this still available somewhere?

**Comment by coorasse** [comment]
Yes: https://github.com/CanCanCommunity/cancancan/blob/develop/docs/migrating.md

**Comment by giladshanan** [comment]
The changelog has a broken link that should be updated (https://github.com/CanCanCommunity/cancancan/blob/develop/CHANGELOG.md#300)
