### ISSUE TITLE
SQL error when two rules refer to the :read action with hash parameters

### ISSUE THREAD

**Issue by Silex** [CanCanCommunity/cancancan#76]
Hello,

When you have the following:

``` ruby
# Models
class Item
  has_many :permissions, as: :subject
end
class Permission
  belongs_to :user
  belongs_to :subject, polymorphic: true
  # db field 'action'
end

# Ability
alias_action :read, :update, :destroy, to: :modify
can :read,   Item, permissions: { action: 'read',   user_id: user.id }
can :modify, Item, permissions: { action: 'modify', user_id: user.id }
```

Trying to do `Item.accessible_by(current_ability)` fails with the following error:

```
Mysql2::Error: Unknown column 'permissions.action' in 'where clause': SELECT `items`.* FROM `items`  WHERE ((`permissions`.`action` = 'modify' AND `permissions`.`user_id` = 14) OR (`permissions`.`action` = 'read' AND `permissions`.`user_id` = 14))
```

To fix it, you can do one of the following:
- Remove the `:read` action from the `:modify` alias
- Remove the `can :read, ...` rule
- Use `can [:read, :update, :destroy], ...` instead of `can :modify`

This only seem to happen with `:read`, I couldn't reproduce with `:update`.

See #74 for more informations.

**Comment by coorasse** [comment]
Seems to me this issue can be closed. Feel free to reopen in case.
