### ISSUE TITLE
RulesCompressor is too aggressive

### ISSUE THREAD

**Issue by c960657** [CanCanCommunity/cancancan#783]
`RulesCompressor` is too aggressive when there are multiple rules with different actions or subjects.

```
  context 'multiple "can catch all" with different subjects' do
    let(:rules) do
      [can(:read, Blog),
       can(:update, Blog)]
    end

    it 'preserves all rules' do
      expect(described_class.new(rules).rules_collapsed).to eq rules
    end
  end

  context 'multiple "can catch all" with different subjects' do
    let(:rules) do
      [can(:read, Blog),
       can(:update, Author)]
    end

    it 'preserves all rules' do
      expect(described_class.new(rules).rules_collapsed).to eq rules
    end
  end
```

In particular, this bug may be triggered by `StiNormalizer` if different rules are defined for different subclasses of the same parent class.

As a workaround I have monkey-patched `RulesCompressor#compress` to just return the uncompressed rules array.

**Comment by c960657** [comment]
I am not sure what kind of optimisations `RulesCompressor` is supposed to do, but database servers are generally good at eliminating redundant parts of a query, so it might be easier and more robust to skip compressing and just include all rules when building the query, i.e. let the database do the compressing.

**Comment by armellarcier** [comment]
+1, RulesCompressor reduces rules for multiple STI models to the last declared one and introduces bugs throughout my app.
Overriding it does fix the problem but seems so bad... Can maintainers @Liberatys @coorasse tell us what could be wrong with the compressor ?
