### ISSUE TITLE
why not have alias_subject

### ISSUE THREAD

**Issue by ff-apujari** [CanCanCommunity/cancancan#96]
a subject can be a class or any instance or simply a symbol
when it is a symbol it can be aliased

we are using symbols for subjects a lot, as we do not have AR models

**Comment by bryanrite** [comment]
I think this is a fairly uncommon setup, to share an ability file between different applications but specify the same permissions on objects that have different names... If you want to try implementing alias_subject, I'd be happy to consider it.
